'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Handshake, Loader2, Pencil, Plus, Trash2, TrendingUp, UserCheck, Users } from 'lucide-react';
import { AdminEmptyState, AdminPage, AdminPageHeader, AdminStat, AdminStats, AdminSurface } from '@/components/admin/AdminPage';

type Stage='Contacto inicial'|'Calificación'|'Propuesta'|'Negociación'|'Cerrado';
type Lead={id:number;name:string;contact:string;email:string;phone:string;company:string;value:number;stage:Stage;probability:number;notes:string;next_action:string;created_at:string;updated_at:string};
type Customer={id:string;user_id:string;name:string;email:string;phone:string;source:string;lifecycle_stage:string;marketing_email:boolean;marketing_whatsapp:boolean;last_order_id:string;last_order_at:string;last_order_total:number;created_at:string;updated_at:string};
type FormData={name:string;contact:string;email:string;phone:string;company:string;value:string;stage:Stage;probability:string;next_action:string;notes:string};
const STAGES:Stage[]=['Contacto inicial','Calificación','Propuesta','Negociación','Cerrado'];const EMPTY_FORM:FormData={name:'',contact:'',email:'',phone:'',company:'',value:'0',stage:'Contacto inicial',probability:'20',next_action:'',notes:''};const fmt=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
function nextStage(stage:Stage){const i=STAGES.indexOf(stage);return i>=0&&i<STAGES.length-1?STAGES[i+1]:null}function tone(stage:string){if(stage==='Cerrado'||stage==='Cliente')return'bg-emerald-50 text-emerald-800';if(stage==='Negociación')return'bg-orange-50 text-orange-800';if(stage==='Propuesta')return'bg-amber-50 text-amber-800';return'bg-black/5 text-[#716b60]'}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-1.5 text-xs font-bold text-[#716b60]"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-11 rounded-xl border border-black/10 bg-white px-3 text-sm text-[#171612] outline-none"/></label>}

export default function CRMPage(){
 const[leads,setLeads]=useState<Lead[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[schemaReady,setSchemaReady]=useState(true);const[filter,setFilter]=useState('Todos');const[modal,setModal]=useState(false);const[editLead,setEditLead]=useState<Lead|null>(null);const[saving,setSaving]=useState(false);const[form,setForm]=useState<FormData>(EMPTY_FORM);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const res=await fetch('/api/admin/crm',{cache:'no-store'});const json=await res.json();setSchemaReady(json.schema_ready??res.ok);setLeads(Array.isArray(json.leads)?json.leads.map((l:any)=>({...l,id:Number(l.id),value:Number(l.value||0),probability:Number(l.probability||20)})):[]);setCustomers(Array.isArray(json.customers)?json.customers.map((c:any)=>({...c,last_order_total:Number(c.last_order_total||0),marketing_email:Boolean(c.marketing_email),marketing_whatsapp:Boolean(c.marketing_whatsapp)})):[]);if(!res.ok&&res.status!==503)throw new Error(json.error||'Error al cargar CRM');if(res.status===503)setError(json.error||'Esquema pendiente de migración');}catch(e){setError(e instanceof Error?e.message:'Error desconocido');}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 function openNew(){setEditLead(null);setForm(EMPTY_FORM);setModal(true)}function openEdit(l:Lead){setEditLead(l);setForm({name:l.name,contact:l.contact,email:l.email,phone:l.phone,company:l.company,value:String(l.value),stage:l.stage,probability:String(l.probability),next_action:l.next_action,notes:l.notes});setModal(true)}
 async function save(){if(!form.name.trim())return;setSaving(true);try{const payload={name:form.name,contact:form.contact,email:form.email,phone:form.phone,company:form.company,value:Number(form.value),stage:form.stage,probability:Number(form.probability),next_action:form.next_action,notes:form.notes};const res=await fetch('/api/admin/crm',{method:editLead?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editLead?{id:editLead.id,...payload}:payload)});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||'Error al guardar');setModal(false);await load()}catch(e){setError(e instanceof Error?e.message:'Error al guardar')}finally{setSaving(false)}}
 async function remove(id:number){if(!confirm('¿Eliminar este lead?'))return;const res=await fetch(`/api/admin/crm?id=${id}`,{method:'DELETE'});if(!res.ok){setError('No se pudo eliminar');return}await load()}async function advance(l:Lead){const stage=nextStage(l.stage);if(!stage)return;await fetch('/api/admin/crm',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:l.id,stage})});await load()}
 const filtered=filter==='Todos'?leads:leads.filter(l=>l.stage===filter);const totalValue=useMemo(()=>leads.reduce((s,l)=>s+l.value,0),[leads]);const negotiating=leads.filter(l=>l.stage==='Negociación').length;const marketing=customers.filter(c=>c.marketing_email||c.marketing_whatsapp).length;
 return <AdminPage><AdminPageHeader eyebrow="Ventas & clientes" title="CRM & Clientes" description="Cuentas registradas, consentimiento comercial, compras y oportunidades en una sola vista." actions={<button onClick={openNew} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#171612] px-4 text-xs font-bold text-[#ffb000]"><Plus className="h-4 w-4"/>Nuevo lead</button>}/>
 {!schemaReady?<div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="h-5 w-5 text-amber-700"/><div><b className="text-sm text-amber-900">Migración de clientes pendiente</b><p className="mt-1 text-xs text-amber-800/70">El próximo deployment ejecuta la migración versionada antes del build. No se crean tablas desde el navegador.</p></div></div>:null}{error?<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>:null}
 <AdminStats><AdminStat label="Clientes registrados" value={customers.length} note="Cuentas privadas vinculadas" icon={UserCheck}/><AdminStat label="Leads" value={leads.length} note="Oportunidades activas" icon={Users}/><AdminStat label="Pipeline" value={fmt.format(totalValue)} note="Valor comercial" icon={TrendingUp}/><AdminStat label="Marketing opt-in" value={marketing} note="Consentimiento opcional" icon={Handshake}/></AdminStats>
 <AdminSurface title="Clientes registrados" description="Datos de contacto necesarios para atención, compra y seguimiento. Las preferencias promocionales se muestran separadas.">{loading?<div className="grid min-h-32 place-items-center"><Loader2 className="h-6 w-6 animate-spin"/></div>:customers.length===0?<AdminEmptyState title="Todavía no hay cuentas sincronizadas" description="Cuando un usuario acepte privacidad y active su perfil aparecerá aquí." icon={UserCheck}/>:<div className="grid gap-3 lg:grid-cols-2">{customers.map(c=><article key={c.id} className="rounded-xl border border-black/10 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-[#171612]">{c.name||'Cliente'}</b><p className="mt-1 text-xs text-[#716b60]">{c.email}</p><p className="mt-1 text-xs text-[#716b60]">{c.phone||'Sin teléfono'}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${tone(c.lifecycle_stage)}`}>{c.lifecycle_stage||'Registrado'}</span></div><div className="mt-3 flex flex-wrap gap-2 text-[10px] font-bold"><span className={`rounded-full px-2 py-1 ${c.marketing_email?'bg-emerald-50 text-emerald-700':'bg-black/5 text-[#8b8378]'}`}>Email {c.marketing_email?'sí':'no'}</span><span className={`rounded-full px-2 py-1 ${c.marketing_whatsapp?'bg-emerald-50 text-emerald-700':'bg-black/5 text-[#8b8378]'}`}>WhatsApp {c.marketing_whatsapp?'sí':'no'}</span></div>{c.last_order_id?<div className="mt-3 border-t border-black/10 pt-3 text-xs text-[#716b60]">Última compra <b className="text-[#171612]">{fmt.format(c.last_order_total)}</b> · {c.last_order_at?new Date(c.last_order_at).toLocaleDateString('es-CL'):'fecha pendiente'}</div>:null}</article>)}</div>}</AdminSurface>
 <AdminSurface title="Pipeline comercial" description="Oportunidades manuales y ventas e-commerce sincronizadas." actions={<div className="flex flex-wrap gap-1.5">{['Todos',...STAGES].map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${filter===s?'bg-[#171612] text-[#ffb000]':'bg-black/5 text-[#716b60]'}`}>{s}</button>)}</div>}>{loading?<div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin"/></div>:filtered.length===0?<AdminEmptyState title="Sin oportunidades" description="Crea un lead o espera una nueva venta." icon={Users}/>:<div className="grid gap-3">{filtered.map(l=><article key={l.id} className="rounded-xl border border-black/10 bg-white p-4"><div className="flex items-start justify-between gap-4"><div><b className="text-sm text-[#171612]">{l.name}</b><p className="mt-1 text-xs text-[#817a6f]">{l.email||l.phone||l.contact||'Sin contacto'}</p></div><b className="text-sm text-[#171612]">{fmt.format(l.value)}</b></div><div className="mt-3 flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${tone(l.stage)}`}>{l.stage}</span><span className="text-[11px] text-[#817a6f]">{l.probability}%</span></div><p className="mt-3 text-xs text-[#716b60]">Próxima acción: {l.next_action||'sin definir'}</p><div className="mt-3 flex gap-2"><button onClick={()=>openEdit(l)} className="inline-flex h-9 items-center gap-1 rounded-xl border border-black/10 px-3 text-xs font-bold"><Pencil className="h-3.5 w-3.5"/>Editar</button>{nextStage(l.stage)?<button onClick={()=>void advance(l)} className="inline-flex h-9 items-center gap-1 rounded-xl bg-[#171612] px-3 text-xs font-bold text-[#ffb000]"><ArrowRight className="h-3.5 w-3.5"/>Avanzar</button>:null}<button onClick={()=>void remove(l.id)} className="ml-auto grid h-9 w-9 place-items-center rounded-xl bg-red-50 text-red-700"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>}</AdminSurface>
 {modal?<div className="fixed inset-0 z-[120] grid place-items-center bg-black/45 p-4"><div className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-[20px] bg-[#fffaf1] p-5"><div className="flex justify-between"><h2 className="text-2xl font-black text-[#171612]">{editLead?'Editar oportunidad':'Nueva oportunidad'}</h2><button onClick={()=>setModal(false)}>Cerrar</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Oportunidad *" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Empresa" value={form.company} onChange={v=>setForm({...form,company:v})}/><Field label="Contacto" value={form.contact} onChange={v=>setForm({...form,contact:v})}/><Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Teléfono" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="Valor" type="number" value={form.value} onChange={v=>setForm({...form,value:v})}/><label className="grid gap-1.5 text-xs font-bold text-[#716b60]"><span>Etapa</span><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value as Stage})} className="h-11 rounded-xl border border-black/10 bg-white px-3">{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><Field label="Probabilidad %" type="number" value={form.probability} onChange={v=>setForm({...form,probability:v})}/><div className="sm:col-span-2"><Field label="Próxima acción" value={form.next_action} onChange={v=>setForm({...form,next_action:v})}/></div><label className="grid gap-1.5 text-xs font-bold text-[#716b60] sm:col-span-2"><span>Notas</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} className="rounded-xl border border-black/10 bg-white p-3"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setModal(false)} className="h-10 rounded-xl border border-black/10 px-4 text-xs font-bold">Cancelar</button><button onClick={()=>void save()} disabled={saving||!form.name.trim()} className="h-10 rounded-xl bg-[#171612] px-4 text-xs font-bold text-[#ffb000]">{saving?'Guardando…':'Guardar'}</button></div></div></div>:null}
 </AdminPage>;
}
