export type StructurePreset = 'partition' | 'house1' | 'house2' | 'large';
export type MetalconOpening = { enabled:boolean; xM:number; widthM:number; heightM:number; sillM:number };
export type MetalconInput = { widthM:number; heightM:number; spacingCm:40|60; osbWidthCm:120|122; preset:StructurePreset; cDepthMm:60|90|100|150; thicknessMm:0.5|0.85|1|1.6; door:MetalconOpening; window:MetalconOpening };

export const STRUCTURE_PRESETS = {
  partition:{label:'Tabique interior',profile:'C 60 / U 61',thickness:'0,50 mm referencial',use:'Separación liviana no portante'},
  house1:{label:'Vivienda · 1 piso',profile:'C 90 / U compatible',thickness:'0,85 mm referencial',use:'Muro estructural sujeto a cálculo'},
  house2:{label:'Vivienda · 2 pisos',profile:'C 90–100 / U compatible',thickness:'≥ 0,85 mm según cálculo',use:'Requiere memoria estructural'},
  large:{label:'Estructura mayor',profile:'C 150 o solución diseñada',thickness:'1,00–1,60 mm o superior',use:'Ingeniería obligatoria'},
} as const;

export function enabledOpenings(input:MetalconInput){return [input.door,input.window].filter(item=>item.enabled)}
export function validateMetalcon(input:MetalconInput){const messages:string[]=[];for(const opening of enabledOpenings(input)){if(opening.xM<0||opening.xM+opening.widthM>input.widthM)messages.push('Un vano queda fuera del largo del panel.');if(opening.sillM+opening.heightM>input.heightM)messages.push('Un vano supera la altura del panel.');if(opening.widthM>1.2)messages.push('Vano mayor a 1,20 m: requiere dintel compuesto o viga dimensionada por cálculo.')}if(input.door.enabled&&input.window.enabled){const a=input.door,b=input.window;if(a.xM<b.xM+b.widthM&&b.xM<a.xM+a.widthM)messages.push('La puerta y la ventana se superponen.')}if(input.preset==='partition')messages.push('El preset tabique interior no debe interpretarse como muro soportante.');if(input.preset==='house2'||input.preset==='large')messages.push('Esta escala exige proyecto y memoria de cálculo estructural.');return Array.from(new Set(messages))}
export function calculateMetalcon(input:MetalconInput){const widthM=Math.max(.8,Math.min(20,input.widthM||0)),heightM=Math.max(1.8,Math.min(5,input.heightM||0)),openings=enabledOpenings(input),baseStuds=Math.floor(widthM*100/input.spacingCm)+1,openingReinforcements=openings.length*4,sheetHeightM=input.osbWidthCm===122?2.44:2.4,grossArea=widthM*heightM,openingArea=openings.reduce((sum,item)=>sum+item.widthM*item.heightM,0),osbSheets=Math.max(1,Math.ceil(Math.max(0,grossArea-openingArea)/((input.osbWidthCm/100)*sheetHeightM)*1.1)),verticalMeters=(baseStuds+openingReinforcements)*heightM;return {baseStuds,openingReinforcements,totalStuds:baseStuds+openingReinforcements,trackMeters:Math.ceil(widthM*2*10)/10,profileMeters:Math.ceil((verticalMeters+openings.reduce((s,o)=>s+o.widthM*2,0))*10)/10,osbSheets,openings:openings.length,warnings:validateMetalcon(input)}}
