'use client';

import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Html, RoundedBox } from '@react-three/drei';
import * as THREE from 'three';
import * as CANNON from 'cannon-es';
import { ArrowLeft, Calculator, Fan, Gamepad2, Leaf, Move, Speaker, Thermometer, VolumeX, X } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { navigateWithTransition } from '@/lib/routeTransition';

type Capacity = 9000 | 12000 | 18000 | 24000;
type ClimateMode = 'frio' | 'ventilacion' | 'seco' | 'auto';
type MoveState = { forward: boolean; back: boolean; left: boolean; right: boolean };
type Panel = 'measure' | 'climate' | null;
type AirOption = { cap: Capacity; label: string; coverage: string; width: number; energy: string; energyColor: string; benefit: string; powerKw: number };

const OPTIONS: AirOption[] = [
  { cap: 9000, label: '9.000 BTU', coverage: 'hasta 18 m²', width: 1.18, energy: 'A++', energyColor: '#58D985', benefit: 'Eficiente', powerKw: .82 },
  { cap: 12000, label: '12.000 BTU', coverage: 'hasta 24 m²', width: 1.34, energy: 'A++', energyColor: '#58D985', benefit: 'Equilibrado', powerKw: 1.08 },
  { cap: 18000, label: '18.000 BTU', coverage: 'hasta 36 m²', width: 1.58, energy: 'A+', energyColor: '#9EDC55', benefit: 'Más potente', powerKw: 1.58 },
  { cap: 24000, label: '24.000 BTU', coverage: 'hasta 48 m²', width: 1.82, energy: 'A', energyColor: '#E7C94F', benefit: 'Máximo confort', powerKw: 2.2 },
];

const MODES: Record<ClimateMode, { label: string; color: string; factor: number }> = {
  frio: { label: 'Frío', color: '#6BC6F4', factor: 1 },
  ventilacion: { label: 'Vent.', color: '#D6E8F2', factor: .3 },
  seco: { label: 'Deshum.', color: '#64CFAF', factor: .66 },
  auto: { label: 'Auto', color: '#B29BE7', factor: .82 },
};

const clamp = (n: number, min: number, max: number) => Math.min(max, Math.max(min, n));
const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
const integer = new Intl.NumberFormat('es-CL', { maximumFractionDigits: 0 });

function Field({ label, value, suffix, step = .1, onChange }: { label: string; value: number; suffix?: string; step?: number; onChange: (n: number) => void }) {
  return <label className="flex min-h-11 items-center justify-between rounded-xl border border-white/10 bg-white/[.055] px-3"><span className="text-[9px] font-black uppercase tracking-[.12em] text-white/45">{label}</span><span className="flex items-center gap-1.5"><input type="number" min={step} step={step} value={value} onChange={(e) => onChange(Math.max(step, Number(e.target.value) || step))} className="w-14 bg-transparent text-right text-sm font-black text-white outline-none" />{suffix ? <small className="text-[9px] text-white/35">{suffix}</small> : null}</span></label>;
}

function Glass({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`border border-white/14 bg-black/58 shadow-[0_20px_60px_rgba(0,0,0,.35)] backdrop-blur-xl ${className}`}>{children}</div>;
}

function AirUnit({ option, roomDepth, roomHeight, mode, fanSpeed }: { option: AirOption; roomDepth: number; roomHeight: number; mode: ClimateMode; fanSpeed: number }) {
  const y = clamp(roomHeight * .76, 1.8, roomHeight - .35); const z = -roomDepth / 2 + .18; const c = MODES[mode].color;
  return <group position={[0, y, z]}>
    <RoundedBox args={[option.width, .38, .28]} radius={.08} smoothness={5} castShadow><meshStandardMaterial color="#E4E1DA" roughness={.34} metalness={.02} /></RoundedBox>
    <mesh position={[0, -.12, .155]} rotation={[.18, 0, 0]}><boxGeometry args={[option.width * .82, .066, .05]} /><meshStandardMaterial color="#1D2024" roughness={.4} /></mesh>
    <mesh position={[option.width * .28, .025, .15]}><planeGeometry args={[option.width * .16, .06]} /><meshBasicMaterial color={c} transparent opacity={.62} /></mesh>
    <Html transform position={[option.width / 2 + .32, .08, .02]} distanceFactor={1.8} style={{ pointerEvents: 'none' }}><div className="w-[138px] rounded-2xl border border-white/14 bg-black/72 p-2.5 text-white shadow-xl backdrop-blur-xl"><div className="flex items-center justify-between"><small className="text-[7px] uppercase text-white/38">Equipo</small><span className="rounded-full px-2 py-1 text-[9px] font-black" style={{ color: option.energyColor, background: `${option.energyColor}18` }}>{option.energy}</span></div><b className="mt-1 block text-sm">{option.label}</b><small className="text-[8px] text-white/48">{option.coverage}</small></div></Html>
    <Airflow roomDepth={roomDepth} roomHeight={roomHeight} mode={mode} fanSpeed={fanSpeed} />
  </group>;
}

function Airflow({ roomDepth, roomHeight, mode, fanSpeed }: { roomDepth: number; roomHeight: number; mode: ClimateMode; fanSpeed: number }) {
  const ref = useRef<THREE.Group>(null); const color = MODES[mode].color;
  useFrame(({ clock }) => { if (!ref.current) return; ref.current.children.forEach((child, i) => { const t = (clock.elapsedTime * (.18 + fanSpeed * .08) + i / 22) % 1; child.position.set(((i % 6) - 2.5) * .13 * (1 + t * .45), -.08 - t * .45, .28 + t * Math.min(roomDepth * .45, 2.2)); ((child as THREE.Mesh).material as THREE.MeshBasicMaterial).opacity = Math.sin(Math.PI * t) * (.08 + fanSpeed * .02); }); });
  return <group ref={ref}>{Array.from({ length: 22 }).map((_, i) => <mesh key={i}><sphereGeometry args={[.025, 7, 5]} /><meshBasicMaterial color={color} transparent opacity={.1} depthWrite={false} /></mesh>)}</group>;
}

function Room({ roomWidth, roomDepth, roomHeight, option, mode, fanSpeed }: { roomWidth: number; roomDepth: number; roomHeight: number; option: AirOption; mode: ClimateMode; fanSpeed: number }) {
  const bedW = Math.min(2.4, roomWidth * .56); const bedD = Math.min(1.9, roomDepth * .4); const windowH = Math.min(1.65, roomHeight * .6);
  return <group>
    <mesh rotation={[-Math.PI / 2, 0, 0]} receiveShadow><planeGeometry args={[roomWidth, roomDepth]} /><meshStandardMaterial color="#744B31" roughness={.78} /></mesh>
    <mesh position={[0, roomHeight + .06, 0]}><boxGeometry args={[roomWidth + .15, .12, roomDepth + .15]} /><meshStandardMaterial color="#A89D91" roughness={.92} /></mesh>
    <mesh position={[0, roomHeight / 2, -roomDepth / 2]} receiveShadow><boxGeometry args={[roomWidth, roomHeight, .12]} /><meshStandardMaterial color="#9B8B7D" roughness={.94} /></mesh>
    <mesh position={[roomWidth / 2, roomHeight / 2, 0]} receiveShadow><boxGeometry args={[.12, roomHeight, roomDepth]} /><meshStandardMaterial color="#4A3228" roughness={.9} /></mesh>

    <group position={[-roomWidth / 2 + .065, .52 + windowH / 2, 0]} rotation={[0, Math.PI / 2, 0]}><mesh><planeGeometry args={[Math.min(roomDepth * .52, 2.8), windowH]} /><meshPhysicalMaterial color="#7994A0" transmission={.55} transparent opacity={.28} roughness={.12} /></mesh><mesh position={[0, 0, -.06]}><planeGeometry args={[Math.min(roomDepth * .56, 3), windowH * 1.08]} /><meshBasicMaterial color="#85513B" /></mesh></group>

    <group position={[0, .45, -roomDepth / 2 + bedD / 2 + .42]}><RoundedBox args={[bedW, .32, bedD]} radius={.1} smoothness={4} castShadow><meshStandardMaterial color="#5F5550" roughness={.92} /></RoundedBox><RoundedBox args={[bedW * .98, .23, bedD * .95]} radius={.08} smoothness={4} position={[0, .25, 0]} castShadow><meshStandardMaterial color="#C7B9A8" roughness={.98} /></RoundedBox><mesh position={[0, .67, -bedD * .46]} castShadow><boxGeometry args={[bedW, .8, .13]} /><meshStandardMaterial color="#6B5E57" roughness={.9} /></mesh></group>

    {[-1, 1].map((side) => <group key={side} position={[side * Math.min(roomWidth / 2 - .55, 1.8), .38, -roomDepth / 2 + .72]}><RoundedBox args={[.56, .5, .52]} radius={.05} smoothness={4}><meshStandardMaterial color="#493129" roughness={.84} /></RoundedBox><pointLight position={[0, .68, .06]} color="#E6A36C" intensity={.24} distance={2.4} /></group>)}

    <group position={[-roomWidth / 2 + .7, .42, roomDepth / 2 - 1.1]}><RoundedBox args={[.82, .48, .78]} radius={.14} smoothness={4}><meshStandardMaterial color="#776C64" roughness={.95} /></RoundedBox></group>
    <AirUnit option={option} roomDepth={roomDepth} roomHeight={roomHeight} mode={mode} fanSpeed={fanSpeed} />

    <hemisphereLight args={['#D6A97E', '#30261F', .3]} />
    <directionalLight position={[-roomWidth * .55, roomHeight + 2, roomDepth * .3]} intensity={.9} color="#DDA570" castShadow shadow-mapSize-width={1024} shadow-mapSize-height={1024} />
    <rectAreaLight position={[-roomWidth / 2 + .22, roomHeight * .62, .1]} rotation={[0, Math.PI / 2, 0]} width={Math.min(roomDepth * .6, 2.8)} height={1.3} intensity={1.15} color="#CE8659" />
    <spotLight position={[roomWidth * .22, roomHeight - .12, .2]} intensity={.48} angle={.58} penumbra={.9} color="#E0A36A" />
  </group>;
}

function Avatar({ moving }: { moving: React.MutableRefObject<number> }) {
  const l = useRef<THREE.Group>(null); const r = useRef<THREE.Group>(null);
  useFrame(({ clock }) => { const a = Math.sin(clock.elapsedTime * 10) * .5 * moving.current; if (l.current) l.current.rotation.x = a; if (r.current) r.current.rotation.x = -a; });
  return <group><mesh position={[0, 1.52, 0]} castShadow><sphereGeometry args={[.16, 18, 14]} /><meshStandardMaterial color="#A36F54" roughness={.85} /></mesh><RoundedBox args={[.44, .7, .24]} radius={.1} smoothness={4} position={[0, 1.02, 0]} castShadow><meshStandardMaterial color="#17191D" roughness={.88} /></RoundedBox><group ref={l} position={[-.12, .67, 0]}><mesh position={[0, -.35, 0]}><capsuleGeometry args={[.082, .56, 5, 10]} /><meshStandardMaterial color="#23252A" roughness={.9} /></mesh></group><group ref={r} position={[.12, .67, 0]}><mesh position={[0, -.35, 0]}><capsuleGeometry args={[.082, .56, 5, 10]} /><meshStandardMaterial color="#23252A" roughness={.9} /></mesh></group></group>;
}

function ThirdPerson({ move, roomWidth, roomDepth }: { move: MoveState; roomWidth: number; roomDepth: number }) {
  const { camera, gl, size } = useThree(); const avatar = useRef<THREE.Group>(null); const yaw = useRef(0); const pitch = useRef(.1); const dragging = useRef(false); const last = useRef({ x: 0, y: 0 }); const keys = useRef(new Set<string>()); const physics = useRef<{ world: CANNON.World; body: CANNON.Body } | null>(null); const moving = useRef(0);
  useEffect(() => { const world = new CANNON.World({ gravity: new CANNON.Vec3(0, 0, 0) }); const body = new CANNON.Body({ mass: 1, position: new CANNON.Vec3(0, .3, roomDepth / 2 - 1), linearDamping: .2 }); body.addShape(new CANNON.Sphere(.22)); world.addBody(body); const wall = (half: [number, number, number], pos: [number, number, number]) => { const b = new CANNON.Body({ mass: 0, position: new CANNON.Vec3(...pos) }); b.addShape(new CANNON.Box(new CANNON.Vec3(...half))); world.addBody(b); }; wall([.08, 1, roomDepth / 2], [-roomWidth / 2, 1, 0]); wall([.08, 1, roomDepth / 2], [roomWidth / 2, 1, 0]); wall([roomWidth / 2, 1, .08], [0, 1, -roomDepth / 2]); physics.current = { world, body }; return () => { physics.current = null; }; }, [roomDepth, roomWidth]);
  useEffect(() => { const canvas = gl.domElement; const kd = (e: KeyboardEvent) => keys.current.add(e.code); const ku = (e: KeyboardEvent) => keys.current.delete(e.code); const down = (e: PointerEvent) => { dragging.current = true; last.current = { x: e.clientX, y: e.clientY }; }; const up = () => { dragging.current = false; }; const look = (e: PointerEvent) => { if (!dragging.current) return; const dx = e.clientX - last.current.x; const dy = e.clientY - last.current.y; last.current = { x: e.clientX, y: e.clientY }; const sens = e.pointerType === 'touch' ? .0065 : .0048; yaw.current -= dx * sens; pitch.current = clamp(pitch.current + dy * sens * .5, -.08, .42); }; window.addEventListener('keydown', kd); window.addEventListener('keyup', ku); canvas.addEventListener('pointerdown', down); window.addEventListener('pointerup', up); canvas.addEventListener('pointermove', look); return () => { window.removeEventListener('keydown', kd); window.removeEventListener('keyup', ku); canvas.removeEventListener('pointerdown', down); window.removeEventListener('pointerup', up); canvas.removeEventListener('pointermove', look); }; }, [gl]);
  useFrame((_, delta) => { const p = physics.current; if (!p || !avatar.current) return; const z = (keys.current.has('KeyW') || move.forward ? 1 : 0) - (keys.current.has('KeyS') || move.back ? 1 : 0); const x = (keys.current.has('KeyD') || move.right ? 1 : 0) - (keys.current.has('KeyA') || move.left ? 1 : 0); const input = new THREE.Vector3(x, 0, -z); const active = input.lengthSq() > 0; moving.current = THREE.MathUtils.damp(moving.current, active ? 1 : 0, 12, delta); if (active) { input.normalize().applyAxisAngle(new THREE.Vector3(0, 1, 0), yaw.current); const speed = keys.current.has('ShiftLeft') || keys.current.has('ShiftRight') ? 5.2 : 3.25; p.body.velocity.x = input.x * speed; p.body.velocity.z = input.z * speed; avatar.current.rotation.y = THREE.MathUtils.damp(avatar.current.rotation.y, Math.atan2(input.x, input.z), 14, delta); } else { p.body.velocity.x *= .42; p.body.velocity.z *= .42; } p.body.velocity.y = 0; p.world.step(1 / 60, Math.min(delta, .045), 2); p.body.position.y = .3; avatar.current.position.set(p.body.position.x, 0, p.body.position.z); const mobile = size.width < 720; const target = new THREE.Vector3(p.body.position.x, 1.04, p.body.position.z); const distance = mobile ? 4 : 4.45; const height = mobile ? 1.65 : 1.78; const desired = target.clone().add(new THREE.Vector3(Math.sin(yaw.current) * distance, height + pitch.current * 1.3, Math.cos(yaw.current) * distance)); camera.position.lerp(desired, 1 - Math.exp(-delta * 10)); camera.lookAt(target.x, target.y + .1, target.z); });
  return <group ref={avatar}><Avatar moving={moving} /></group>;
}

function MovePad({ setMove }: { setMove: Dispatch<SetStateAction<MoveState>> }) { const press = (key: keyof MoveState, value: boolean) => setMove((s) => ({ ...s, [key]: value })); const b = (key: keyof MoveState, label: string, c: string, r: string) => <button onPointerDown={() => press(key, true)} onPointerUp={() => press(key, false)} onPointerCancel={() => press(key, false)} className={`${c} ${r} grid place-items-center rounded-full bg-white/14 text-white active:bg-[#F5871F] active:text-black`}>{label}</button>; return <div className="pointer-events-auto absolute bottom-[158px] left-3 z-40 grid h-[112px] w-[112px] grid-cols-3 grid-rows-3 gap-1 rounded-full border border-white/14 bg-black/48 p-2 backdrop-blur-xl md:hidden">{b('forward', '↑', 'col-start-2', 'row-start-1')}{b('left', '←', 'col-start-1', 'row-start-2')}<span className="col-start-2 row-start-2 grid place-items-center"><Move className="h-4 w-4 text-white/35" /></span>{b('right', '→', 'col-start-3', 'row-start-2')}{b('back', '↓', 'col-start-2', 'row-start-3')}</div>; }

function ClimatePanel({ temperature, setTemperature, fanSpeed, setFanSpeed, mode, setMode }: { temperature: number; setTemperature: (n: number) => void; fanSpeed: number; setFanSpeed: (n: number) => void; mode: ClimateMode; setMode: (m: ClimateMode) => void }) { return <div className="space-y-3"><div className="flex items-center justify-between"><b className="text-sm">Control de clima</b><b className="text-3xl">{temperature}°</b></div><input type="range" min={16} max={28} value={temperature} onChange={(e) => setTemperature(Number(e.target.value))} className="w-full accent-[#F5871F]" /><div className="grid grid-cols-4 gap-1.5">{(['frio', 'ventilacion', 'seco', 'auto'] as ClimateMode[]).map((m) => <button key={m} onClick={() => setMode(m)} className={`rounded-xl border py-2 text-[8px] font-black ${mode === m ? 'border-white/25 bg-white/12 text-white' : 'border-white/7 bg-white/[.035] text-white/40'}`}>{MODES[m].label}</button>)}</div><div className="grid grid-cols-4 gap-1.5">{[1, 2, 3, 4].map((v) => <button key={v} onClick={() => setFanSpeed(v)} className={`flex items-center justify-center gap-1 rounded-xl border py-2 text-[9px] ${fanSpeed === v ? 'border-[#6BC6F4]/40 bg-[#6BC6F4]/12 text-[#6BC6F4]' : 'border-white/7 bg-white/[.035] text-white/40'}`}><Fan className="h-3 w-3" />{v}</button>)}</div></div>; }

export default function AirGameExperienceV4() {
  const router = useRouter(); const [length, setLength] = useState(5.4); const [width, setWidth] = useState(4.4); const [height, setHeight] = useState(2.7); const [people, setPeople] = useState(2); const [selectedCap, setSelectedCap] = useState<Capacity>(12000); const [temperature, setTemperature] = useState(22); const [fanSpeed, setFanSpeed] = useState(2); const [mode, setMode] = useState<ClimateMode>('frio'); const [panel, setPanel] = useState<Panel>(null); const [move, setMove] = useState<MoveState>({ forward: false, back: false, left: false, right: false }); const [intro, setIntro] = useState(true); const [sound, setSound] = useState(false);
  useEffect(() => { const t = window.setTimeout(() => setIntro(false), 3000); return () => window.clearTimeout(t); }, []);
  const calc = useMemo(() => { const area = length * width; const volume = area * height; const requiredBtu = Math.ceil(area * 600 + volume * 55 + people * 600 + 1194); const recommended = (OPTIONS.find((o) => o.cap >= requiredBtu)?.cap || 24000) as Capacity; const option = OPTIONS.find((o) => o.cap === selectedCap) || OPTIONS[1]; const monthlyKwh = option.powerKw * (.9 + fanSpeed * .04) * MODES[mode].factor * 4 * 30; return { area, requiredBtu, recommended, option, monthlyKwh, cost: monthlyKwh * 263 }; }, [fanSpeed, height, length, mode, people, selectedCap, width]);
  useEffect(() => setSelectedCap(calc.recommended), [calc.recommended]); const roomWidth = clamp(width, 2.8, 7.5); const roomDepth = clamp(length, 3.2, 8.5); const roomHeight = clamp(height, 2.2, 3.6);
  return <main className="relative h-[100svh] min-h-[620px] w-full overflow-hidden bg-[#0E0E10] text-white">
    {intro ? <div className="absolute inset-0 z-[100] grid place-items-center bg-[#0A0B0D] px-5"><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl border border-[#EBA665]/25 bg-[#F5871F]/10 text-[#EBA665]"><Gamepad2 className="h-5 w-5" /></div><small className="mt-5 block text-[9px] font-black uppercase tracking-[.22em] text-[#EBA665]">Fabrick Game View V4</small><h1 className="mt-2 text-2xl font-black">Entra a tu habitación</h1><p className="mt-2 text-xs text-white/48">Ahora con cámara corregida y movimiento rápido.</p><div className="mx-auto mt-6 h-1 w-[210px] overflow-hidden rounded-full bg-white/8"><div className="h-full w-full animate-pulse rounded-full bg-gradient-to-r from-[#F5871F] to-[#75DE9A]" /></div></div></div> : null}
    <div className="absolute inset-0"><Canvas shadows dpr={[.8, 1.3]} camera={{ fov: 60, near: .05, far: 50 }} gl={{ antialias: true, alpha: false, powerPreference: 'high-performance' }} onCreated={({ gl }) => { gl.toneMapping = THREE.ACESFilmicToneMapping; gl.toneMappingExposure = .68; gl.outputColorSpace = THREE.SRGBColorSpace; gl.shadowMap.type = THREE.PCFSoftShadowMap; }}><color attach="background" args={['#17120F']} /><fog attach="fog" args={['#17120F', 13, 28]} /><Room roomWidth={roomWidth} roomDepth={roomDepth} roomHeight={roomHeight} option={calc.option} mode={mode} fanSpeed={fanSpeed} /><ThirdPerson move={move} roomWidth={roomWidth} roomDepth={roomDepth} /></Canvas></div>
    <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(3,3,4,.2),transparent_30%,transparent_72%,rgba(3,3,4,.56))]" />

    <header className="pointer-events-none absolute inset-x-0 top-0 z-40 flex justify-between p-3 sm:p-5"><div className="pointer-events-auto flex items-center gap-2"><button onClick={() => navigateWithTransition('/tienda', router)} className="grid h-11 w-11 place-items-center rounded-full border border-white/14 bg-black/48 backdrop-blur-xl"><ArrowLeft className="h-4 w-4" /></button><Glass className="rounded-full px-3.5 py-2"><small className="block text-[7px] font-black uppercase tracking-[.18em] text-[#EBA665]">Calculadora 3D · V4</small><b className="block text-[10px]">{calc.area.toFixed(1)} m² · {integer.format(calc.requiredBtu)} BTU</b></Glass></div><button onClick={() => setSound(!sound)} className="pointer-events-auto grid h-11 w-11 place-items-center rounded-full border border-white/14 bg-black/48 backdrop-blur-xl">{sound ? <Speaker className="h-4 w-4 text-[#75DE9A]" /> : <VolumeX className="h-4 w-4" />}</button></header>

    <aside className="pointer-events-none absolute left-5 top-[110px] z-30 hidden w-[265px] lg:block"><Glass className="pointer-events-auto rounded-[1.5rem] p-3.5"><div className="mb-3 flex items-center gap-2"><Calculator className="h-4 w-4 text-[#EBA665]" /><div><b className="block text-xs">Dimensiones</b><small className="text-[8px] text-white/35">El cuarto cambia en vivo</small></div></div><div className="space-y-1.5"><Field label="Largo" value={length} suffix="m" onChange={setLength} /><Field label="Ancho" value={width} suffix="m" onChange={setWidth} /><Field label="Alto" value={height} suffix="m" onChange={setHeight} /><Field label="Personas" value={people} step={1} onChange={setPeople} /></div><div className="mt-2.5 rounded-xl bg-[#F5871F] px-3 py-2.5 text-center text-sm font-black text-black">{integer.format(calc.recommended)} BTU</div></Glass></aside>
    <aside className="pointer-events-none absolute right-5 top-[110px] z-30 hidden w-[272px] lg:block"><Glass className="pointer-events-auto rounded-[1.5rem] p-4"><ClimatePanel temperature={temperature} setTemperature={setTemperature} fanSpeed={fanSpeed} setFanSpeed={setFanSpeed} mode={mode} setMode={setMode} /><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-white/6 p-2.5"><small className="text-white/35">Consumo</small><b className="block">{Math.round(calc.monthlyKwh)} kWh</b></div><div className="rounded-xl bg-white/6 p-2.5"><small className="text-white/35">Estimado</small><b className="block">{money.format(calc.cost)}</b></div></div></Glass></aside>

    <div className="pointer-events-auto absolute right-3 top-[70px] z-40 flex gap-2 lg:hidden"><button onClick={() => setPanel(panel === 'measure' ? null : 'measure')} className="grid h-10 w-10 place-items-center rounded-full border border-white/14 bg-black/48 backdrop-blur-xl"><Calculator className="h-4 w-4" /></button><button onClick={() => setPanel(panel === 'climate' ? null : 'climate')} className="grid h-10 w-10 place-items-center rounded-full border border-white/14 bg-black/48 backdrop-blur-xl"><Thermometer className="h-4 w-4" /></button></div>
    {panel ? <div className="pointer-events-auto absolute inset-x-3 top-[120px] z-50 lg:hidden"><Glass className="mx-auto max-w-md rounded-[1.4rem] p-3.5"><div className="mb-3 flex justify-between"><b className="text-xs">{panel === 'measure' ? 'Dimensiones' : 'Clima'}</b><button onClick={() => setPanel(null)}><X className="h-4 w-4" /></button></div>{panel === 'measure' ? <div className="grid grid-cols-2 gap-1.5"><Field label="Largo" value={length} suffix="m" onChange={setLength} /><Field label="Ancho" value={width} suffix="m" onChange={setWidth} /><Field label="Alto" value={height} suffix="m" onChange={setHeight} /><Field label="Personas" value={people} step={1} onChange={setPeople} /></div> : <ClimatePanel temperature={temperature} setTemperature={setTemperature} fanSpeed={fanSpeed} setFanSpeed={setFanSpeed} mode={mode} setMode={setMode} />}</Glass></div> : null}

    <div className="pointer-events-none absolute left-1/2 top-[82px] z-30 -translate-x-1/2 rounded-full border border-white/10 bg-black/38 px-3 py-2 text-[7px] font-black uppercase tracking-[.12em] text-white/52 backdrop-blur-xl"><Gamepad2 className="mr-1 inline h-3.5 w-3.5 text-[#EBA665]" />WASD / joystick · Shift corre</div>
    <MovePad setMove={setMove} />

    <section className="pointer-events-none absolute inset-x-0 bottom-3 z-40 flex justify-center px-2.5"><Glass className="pointer-events-auto w-full max-w-[820px] rounded-[1.4rem] p-2"><div className="flex gap-2 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{OPTIONS.map((o) => { const selected = o.cap === selectedCap; const ideal = o.cap === calc.recommended; return <button key={o.cap} onClick={() => setSelectedCap(o.cap)} className={`min-w-[122px] rounded-[1rem] border p-2.5 text-left sm:min-w-[150px] ${selected ? 'border-[#EBA665]/70 bg-[#F5871F]/16' : 'border-white/8 bg-white/[.05]'}`}><div className="mx-auto mb-1 h-8 w-20 rounded-[.5rem] border border-white/20 bg-gradient-to-b from-[#e7e5df] to-[#b9b8b4] shadow-lg"><div className="mx-auto mt-6 h-1 w-[75%] rounded-full bg-[#292c30]" /></div><div className="flex items-end justify-between gap-2"><div><b className={selected ? 'text-[#EBA665]' : ''}>{o.label}</b><span className="mt-1 flex items-center gap-1 text-[8px] text-white/45"><Leaf className="h-3 w-3" style={{ color: o.energyColor }} />{ideal ? 'Ideal para ti' : o.benefit}</span></div><span className="rounded-full px-1.5 py-1 text-[8px] font-black" style={{ color: o.energyColor, background: `${o.energyColor}16` }}>{o.energy}</span></div></button>; })}</div></Glass></section>
  </main>;
}
