'use client';
import Link from 'next/link';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { ArrowLeft, ChevronLeft, ChevronRight, Droplets, Eye, Footprints, Home, Layers3, Menu, Pause, Play, RotateCcw, Table2, X } from 'lucide-react';
import { Suspense, useEffect, useMemo, useState, type ReactNode } from 'react';
import { METALCON_HOUSE_PRESET_ORDER, METALCON_HOUSE_PRESETS, type MetalconHousePresetId } from '@/lib/metalconAssembly';
import { MetalconAssembly3D } from './MetalconAssembly3D';
import MetalconLabEnvironmentV2 from './MetalconLabEnvironmentV2';
import MetalconLabFinishesV2 from './MetalconLabFinishesV2';
import MetalconWalkRig, { type LabMovement } from './MetalconWalkRig';
import { METALCON_LAB_STAGES, METALCON_LAYERS, metalconBreakdown, metalconStageIndex, type MetalconLabLayer, type MetalconLightMode } from './metalconLabData';

type Drawer='layers'|'breakdown'|'systems'|'environment'|null;
const emptyMove:LabMovement={forward:false,back:false,left:false,right:false,turnLeft:false,turnRight:false};
export default function MetalconConstructionLabV2(){
 const[modelId,setModelId]=useState<MetalconHousePresetId>('family-6x8'),[timeline,setTimeline]=useState(100),[playing,setPlaying]=useState(false),[drawer,setDrawer]=useState<Drawer>(null),[light,setLight]=useState<MetalconLightMode>('day'),[cutaway,setCutaway]=useState(true),[autoRotate,setAutoRotate]=useState(false),[walk,setWalk]=useState(false),[movement,setMovement]=useState<LabMovement>(emptyMove);
 const[layers,setLayers]=useState<Record<MetalconLabLayer,boolean>>({structure:true,osb:true,membrane:true,battens:true,insulation:true,gypsum:true,ceiling:true,floor:true,siding:true,roof:true,fixtures:true,sanitary:true,vegetation:true});
 const preset=METALCON_HOUSE_PRESETS[modelId],stageIndex=metalconStageIndex(timeline),stage=METALCON_LAB_STAGES[stageIndex],rows=useMemo(()=>metalconBreakdown(preset),[preset]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setTimeline(v=>{if(v>=100){setPlaying(false);return 100}return Math.min(100,v+1)}),120);return()=>window.clearInterval(id)},[playing]);
 useEffect(()=>{if(!walk)setMovement(emptyMove)},[walk]);
 const toggle=(id:MetalconLabLayer)=>setLayers(v=>({...v,[id]:!v[id]})),play=()=>{setTimeline(v=>v>=100?0:v);setPlaying(true);setAutoRotate(false)},reset=()=>{setPlaying(false);setTimeline(0)},jump=(d:number)=>{setPlaying(false);setTimeline(METALCON_LAB_STAGES[Math.max(0,Math.min(METALCON_LAB_STAGES.length-1,stageIndex+d))].start)};
 return <div className="fixed inset-0 z-[120] overflow-hidden bg-[#020507] text-white">
  <div className="absolute inset-0"><Canvas shadows dpr={[1,1.55]} camera={{position:[9,5.5,10],fov:45,near:.05,far:180}}><Suspense fallback={null}><MetalconLabEnvironmentV2 light={light} vegetation={layers.vegetation} preset={preset}/>{layers.structure?<MetalconAssembly3D preset={preset} spacingCm={40} profileDepthMm={90} displayMode="bracing" assemblyProgress={Math.min(1,timeline/38)}/>:null}<MetalconLabFinishesV2 preset={preset} timeline={timeline} layers={layers} cutaway={cutaway}/><MetalconWalkRig active={walk} movement={movement} bounds={{x:preset.widthM/2+3,z:preset.depthM/2+3}}/>{!walk?<OrbitControls makeDefault target={[0,1.05,0]} enableDamping dampingFactor={.075} autoRotate={autoRotate&&!playing} minDistance={2.6} maxDistance={34} maxPolarAngle={Math.PI*.84}/>:null}</Suspense></Canvas></div>
  <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.58),transparent_24%,transparent_69%,rgba(0,0,0,.75))]"/>
  <header className="absolute inset-x-0 top-0 z-30 flex items-center justify-between gap-2 p-3 sm:p-4"><Link href="/herramientas/metalcon" className="inline-flex h-11 items-center gap-2 rounded-full border border-white/12 bg-black/62 px-4 text-[10px] font-black backdrop-blur-xl"><ArrowLeft size={15}/> Metalcon</Link><div className="hidden rounded-full border border-white/10 bg-black/58 px-4 py-2 text-center backdrop-blur-xl sm:block"><span className="block text-[8px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Metalcon Lab 4D</span><b className="text-[10px]">{preset.shortLabel} · {stage.name}</b></div><button onClick={()=>setDrawer(v=>v?null:'layers')} className="inline-flex h-11 items-center gap-2 rounded-full border border-white/12 bg-black/62 px-4 text-[10px] font-black backdrop-blur-xl"><Menu size={15}/> Menú</button></header>
  <div className="absolute left-3 top-[70px] z-30 flex max-w-[calc(100%-86px)] gap-1 overflow-x-auto rounded-full border border-white/10 bg-black/58 p-1 backdrop-blur-xl [scrollbar-width:none]"><Quick active={cutaway} onClick={()=>setCutaway(true)} icon={<Eye size={12}/>} label="Corte"/><Quick active={!cutaway} onClick={()=>setCutaway(false)} icon={<Home size={12}/>} label="Exterior"/><Quick active={walk} onClick={()=>{setWalk(v=>!v);setAutoRotate(false)}} icon={<Footprints size={12}/>} label="Caminar"/><Quick active={layers.sanitary} onClick={()=>toggle('sanitary')} icon={<Droplets size={12}/>} label="Sanitaria"/><Quick active={drawer==='breakdown'} onClick={()=>setDrawer('breakdown')} icon={<Table2 size={12}/>} label="Desglose"/></div>
  {walk?<div className="absolute bottom-[96px] left-3 z-30 grid grid-cols-3 gap-1 rounded-2xl border border-white/10 bg-black/58 p-2 backdrop-blur-xl"><span/><Hold label="Avanzar" onChange={v=>setMovement(m=>({...m,forward:v}))}>▲</Hold><span/><Hold label="Girar izquierda" onChange={v=>setMovement(m=>({...m,turnLeft:v}))}>↶</Hold><Hold label="Retroceder" onChange={v=>setMovement(m=>({...m,back:v}))}>▼</Hold><Hold label="Girar derecha" onChange={v=>setMovement(m=>({...m,turnRight:v}))}>↷</Hold><Hold label="Paso izquierda" onChange={v=>setMovement(m=>({...m,left:v}))}>◀</Hold><span/><Hold label="Paso derecha" onChange={v=>setMovement(m=>({...m,right:v}))}>▶</Hold></div>:null}
  {walk?<div className="pointer-events-none absolute bottom-[98px] right-3 z-20 max-w-[230px] rounded-xl border border-white/10 bg-black/58 px-3 py-2 text-[8px] leading-4 text-white/52 backdrop-blur-xl">Primera persona · altura 1,62 m · cámara limitada al entorno. WASD para moverte, Q/E o flechas para girar.</div>:null}
  {drawer?<aside className="absolute bottom-[98px] right-3 top-[68px] z-40 w-[min(420px,calc(100vw-24px))] overflow-y-auto rounded-[1.5rem] border border-white/12 bg-[#071017]/96 p-4 shadow-2xl backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Laboratorio constructivo</p><h2 className="mt-1 text-lg font-black">{drawer==='layers'?'Capas':drawer==='breakdown'?'Desglose aproximado':drawer==='systems'?'Instalaciones':'Entorno'}</h2></div><button onClick={()=>setDrawer(null)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.06]"><X size={15}/></button></div><div className="mt-4 grid grid-cols-4 gap-1"><Tab active={drawer==='layers'} onClick={()=>setDrawer('layers')} label="Capas"/><Tab active={drawer==='breakdown'} onClick={()=>setDrawer('breakdown')} label="Tabla"/><Tab active={drawer==='systems'} onClick={()=>setDrawer('systems')} label="Sistemas"/><Tab active={drawer==='environment'} onClick={()=>setDrawer('environment')} label="Entorno"/></div>
   {drawer==='layers'?<div className="mt-4 space-y-2">{METALCON_LAYERS.filter(x=>!['fixtures','sanitary','vegetation'].includes(x.id)).map(x=><Toggle key={x.id} label={x.label} active={layers[x.id]} onClick={()=>toggle(x.id)}/>)}</div>:null}
   {drawer==='breakdown'?<div className="mt-4 overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[1.2fr_.8fr_.42fr_.5fr] gap-1 bg-white/[.06] px-2 py-2 text-[7px] font-black uppercase text-white/45"><span>Material</span><span>Referencia</span><span>Un.</span><span>Cant.</span></div>{rows.map((r,i)=><div key={r.material} className={`grid grid-cols-[1.2fr_.8fr_.42fr_.5fr] gap-1 px-2 py-2 text-[8px] ${i%2?'bg-white/[.025]':''}`}><b className="text-white/72">{r.material}</b><span className="text-white/42">{r.spec}</span><span className="text-white/36">{r.unit}</span><b className="text-[#F6C64A]">{r.qty}</b><p className="col-span-4 text-[7px] leading-3 text-white/28">{r.note}</p></div>)}</div>:null}
   {drawer==='systems'?<div className="mt-4 space-y-2"><Toggle label="Baño + cocina" active={layers.fixtures} onClick={()=>toggle('fixtures')}/><Toggle label="Sanitaria + fosa 800 L" active={layers.sanitary} onClick={()=>toggle('sanitary')}/><p className="rounded-xl border border-cyan-300/12 bg-cyan-300/[.04] p-3 text-[8px] leading-4 text-white/44">Trazado sanitario, fosa y artefactos son una representación educativa; pendientes, ventilaciones, dimensionamiento y permisos requieren proyecto sanitario.</p></div>:null}
   {drawer==='environment'?<div className="mt-4 space-y-3"><div className="grid gap-1">{METALCON_HOUSE_PRESET_ORDER.map(id=><button key={id} onClick={()=>setModelId(id)} className={`rounded-xl border px-3 py-3 text-left text-[9px] font-black ${id===modelId?'border-[#F6C64A]/40 bg-[#F6C64A]/10 text-[#F6C64A]':'border-white/8 bg-white/[.025] text-white/52'}`}>{METALCON_HOUSE_PRESETS[id].label}</button>)}</div><div className="grid grid-cols-3 gap-1">{(['day','sunset','night'] as MetalconLightMode[]).map(m=><button key={m} onClick={()=>setLight(m)} className={`rounded-xl py-2 text-[9px] font-black ${m===light?'bg-[#F6C64A] text-black':'bg-white/[.05] text-white/48'}`}>{m==='day'?'Día':m==='sunset'?'Atardecer':'Noche'}</button>)}</div><Toggle label="Vegetación reforzada" active={layers.vegetation} onClick={()=>toggle('vegetation')}/><Toggle label="Giro automático" active={autoRotate} onClick={()=>setAutoRotate(v=>!v)}/></div>:null}
  </aside>:null}
  <div className="absolute bottom-3 left-3 right-3 z-30 rounded-[1.35rem] border border-white/12 bg-black/72 p-3 backdrop-blur-2xl"><div className="flex items-center gap-2"><button onClick={playing?()=>setPlaying(false):play} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#F6C64A] text-black">{playing?<Pause size={16}/>:<Play size={16}/>}</button><button onClick={()=>jump(-1)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.07]"><ChevronLeft size={15}/></button><div className="min-w-0 flex-1"><div className="mb-1 flex justify-between"><b className="truncate text-[8px] uppercase text-[#F6C64A]">{stage.name}</b><span className="text-[8px] text-white/38">{timeline}%</span></div><input aria-label="Secuencia constructiva Metalcon" type="range" min={0} max={100} value={timeline} onChange={e=>{setPlaying(false);setTimeline(Number(e.target.value))}} className="w-full accent-[#F6C64A]"/></div><button onClick={()=>jump(1)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.07]"><ChevronRight size={15}/></button><button onClick={reset} className="grid h-11 w-11 place-items-center rounded-full bg-white/[.07]"><RotateCcw size={15}/></button></div></div>
 </div>
}
function Quick({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:ReactNode;label:string}){return <button onClick={onClick} className={`inline-flex shrink-0 items-center gap-1 rounded-full px-3 py-2 text-[8px] font-black ${active?'bg-[#F6C64A] text-black':'text-white/55'}`}>{icon}{label}</button>}
function Tab({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-xl py-2 text-[8px] font-black ${active?'bg-white text-black':'bg-white/[.05] text-white/45'}`}>{label}</button>}
function Toggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center justify-between rounded-xl border border-white/8 bg-white/[.025] px-3 py-3"><span className="text-[9px] text-white/65">{label}</span><span className={`rounded-full px-2 py-1 text-[7px] font-black ${active?'bg-[#F6C64A] text-black':'bg-white/10'}`}>{active?'ON':'OFF'}</span></button>}
function Hold({children,label,onChange}:{children:ReactNode;label:string;onChange:(v:boolean)=>void}){return <button aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);onChange(true)}} onPointerUp={()=>onChange(false)} onPointerCancel={()=>onChange(false)} onLostPointerCapture={()=>onChange(false)} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-black/60 text-xs font-black active:bg-[#F6C64A] active:text-black">{children}</button>}
