'use client';
import { Html } from '@react-three/drei';
import { Quaternion, Vector3 } from 'three';
import type { ReactNode } from 'react';
import type { MetalconHousePreset } from '@/lib/metalconAssembly';
import type { MetalconLabLayer } from './metalconLabData';

const visible=(timeline:number,start:number)=>Math.min(1,Math.max(0,(timeline-start)/7));
export default function MetalconLabFinishesV2({preset,timeline,layers,cutaway}:{preset:MetalconHousePreset;timeline:number;layers:Record<MetalconLabLayer,boolean>;cutaway:boolean}){
 const scale=Math.min(1,8.4/Math.max(preset.widthM,preset.depthM+(preset.terraceDepthM??0)));
 return <group scale={scale}>
  <Foundation preset={preset} opacity={visible(timeline,0)}/>
  {layers.osb?<Shell preset={preset} offset={.055} thickness={.028} color="#b9824c" opacity={visible(timeline,40)*.9} cutaway={cutaway}/>:null}
  {layers.membrane?<Shell preset={preset} offset={.078} thickness={.012} color="#243b50" opacity={visible(timeline,49)*.62} cutaway={cutaway}/>:null}
  {layers.battens?<Battens preset={preset} opacity={visible(timeline,56)} cutaway={cutaway}/>:null}
  {layers.insulation?<Shell preset={preset} offset={-.025} thickness={.065} color="#e5c761" opacity={visible(timeline,62)*.52} cutaway={cutaway}/>:null}
  {layers.electrical?<Electrical preset={preset} opacity={visible(timeline,66)}/>:null}
  {layers.gypsum?<Shell preset={preset} offset={-.082} thickness={.016} color="#e7e3d8" opacity={visible(timeline,72)*.92} cutaway={cutaway}/>:null}
  {layers.floor?<Floor preset={preset} opacity={visible(timeline,78)}/>:null}
  {layers.ceiling?<Ceiling preset={preset} opacity={visible(timeline,83)}/>:null}
  {layers.fixtures?<Fixtures preset={preset} opacity={visible(timeline,87)}/>:null}
  {layers.sanitary?<Sanitary preset={preset} opacity={visible(timeline,91)}/>:null}
  {layers.siding?<Siding preset={preset} opacity={visible(timeline,95)} cutaway={cutaway}/>:null}
  {layers.roof?<Roof preset={preset} opacity={visible(timeline,98)} cutaway={cutaway}/>:null}
 </group>
}
function mat(color:string,opacity:number,metalness=0,roughness=.78){return <meshStandardMaterial color={color} roughness={roughness} metalness={metalness} transparent={opacity<.99} opacity={opacity}/>}
function Foundation({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){return <group><mesh position={[0,-.17,0]} receiveShadow><boxGeometry args={[preset.widthM+1,.18,preset.depthM+1]}/>{mat('#6c4b34',opacity*.72)}</mesh><mesh position={[0,-.04,0]} receiveShadow><boxGeometry args={[preset.widthM+.28,.22,preset.depthM+.28]}/>{mat('#747a7e',opacity*.7)}</mesh></group>}
function Shell({preset,offset,thickness,color,opacity,cutaway}:{preset:MetalconHousePreset;offset:number;thickness:number;color:string;opacity:number;cutaway:boolean}){if(opacity<=.01)return null;const y=preset.heightM/2;return <group><mesh position={[0,y,-preset.depthM/2-offset]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,thickness]}/>{mat(color,opacity)}</mesh>{!cutaway?<mesh position={[0,y,preset.depthM/2+offset]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,thickness]}/>{mat(color,opacity)}</mesh>:null}<mesh position={[-preset.widthM/2-offset,y,0]} castShadow><boxGeometry args={[thickness,preset.heightM,preset.depthM]}/>{mat(color,opacity)}</mesh><mesh position={[preset.widthM/2+offset,y,0]} castShadow><boxGeometry args={[thickness,preset.heightM,preset.depthM]}/>{mat(color,opacity)}</mesh></group>}
function Battens({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){const xs=Array.from({length:Math.ceil(preset.widthM/.6)+1},(_,i)=>-preset.widthM/2+i*preset.widthM/Math.ceil(preset.widthM/.6));const zs=Array.from({length:Math.ceil(preset.depthM/.6)+1},(_,i)=>-preset.depthM/2+i*preset.depthM/Math.ceil(preset.depthM/.6));return <group>{xs.map(x=><mesh key={`n${x}`} position={[x,preset.heightM/2,-preset.depthM/2-.098]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>)}{!cutaway?xs.map(x=><mesh key={`s${x}`} position={[x,preset.heightM/2,preset.depthM/2+.098]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>):null}{zs.flatMap(z=>[<mesh key={`w${z}`} position={[-preset.widthM/2-.098,preset.heightM/2,z]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>,<mesh key={`e${z}`} position={[preset.widthM/2+.098,preset.heightM/2,z]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>])}</group>}
function Floor({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const sx=Math.max(1,Math.floor(preset.widthM/.6)),sz=Math.max(1,Math.floor(preset.depthM/.6));return <group>{Array.from({length:sx},(_,x)=>Array.from({length:sz},(_,z)=><mesh key={`${x}-${z}`} position={[-preset.widthM/2+.3+x*.6,.045,-preset.depthM/2+.3+z*.6]} receiveShadow><boxGeometry args={[.585,.035,.585]}/>{mat((x+z)%2?'#d2d4d3':'#c5c8c8',opacity,0,.5)}</mesh>))}</group>}
function Ceiling({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const n=Math.ceil(preset.widthM/.6);return <group>{Array.from({length:n+1},(_,i)=>-preset.widthM/2+i*preset.widthM/n).map(x=><mesh key={x} position={[x,preset.heightM-.12,0]}><boxGeometry args={[.035,.035,preset.depthM]}/>{mat('#bcc4ca',opacity,.7,.3)}</mesh>)}<mesh position={[0,preset.heightM-.17,0]}><boxGeometry args={[preset.widthM-.08,.025,preset.depthM-.08]}/>{mat('#e9e5db',opacity*.9)}</mesh></group>}
function Electrical({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){if(opacity<=.01)return null;const w=preset.widthM,d=preset.depthM,h=preset.heightM,outlets:Array<[number,number,number]>=[[-w*.31,.34,-d/2+.11],[0,.34,-d/2+.11],[w*.31,.34,-d/2+.11],[-w/2+.11,.34,-d*.18],[w/2-.11,.34,d*.14]],switches:Array<[number,number,number]>=[[-w*.34,1.12,-d/2+.11],[w*.34,1.12,-d/2+.11]],lights:Array<[number,number,number]>=[[-w*.22,h-.2,-d*.12],[w*.22,h-.2,d*.12]];return <group>{outlets.map((p,i)=><group key={`o${i}`} position={p}><mesh><boxGeometry args={[.13,.095,.035]}/>{mat('#f4f0df',opacity,0,.45)}</mesh><mesh position={[0,0,.021]}><boxGeometry args={[.055,.025,.008]}/>{mat('#252b2e',opacity)}</mesh><mesh position={[0,(h-p[1])/2-.02,-.02]}><cylinderGeometry args={[.018,.018,h-p[1]-.18,8]}/>{mat('#f6c64a',opacity*.9,.15,.45)}</mesh></group>)}{switches.map((p,i)=><group key={`s${i}`} position={p}><mesh><boxGeometry args={[.11,.16,.035]}/>{mat('#f4f0df',opacity)}</mesh><mesh position={[0,.01,.021]}><boxGeometry args={[.045,.075,.008]}/>{mat('#596168',opacity)}</mesh><mesh position={[0,(h-p[1])/2-.03,-.02]}><cylinderGeometry args={[.016,.016,h-p[1]-.16,8]}/>{mat('#f6c64a',opacity*.85,.15,.45)}</mesh></group>)}{lights.map((p,i)=><group key={`l${i}`} position={p}><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.07,.07,.025,16]}/>{mat('#f6c64a',opacity,.15,.35)}</mesh><mesh position={[0,.03,0]}><sphereGeometry args={[.035,12,8]}/>{mat('#fff3b0',opacity)}</mesh></group>)}<mesh position={[0,h-.28,-d/2+.12]}><boxGeometry args={[w*.78,.025,.025]}/>{mat('#f6c64a',opacity*.72,.1,.5)}</mesh><Html center distanceFactor={9} position={[0,h-.54,-d/2+.06]}><Tag>Puntos eléctricos · referencia visual SEC</Tag></Html></group>}
function Siding({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){if(opacity<=.01)return null;const h=.19,rows=Math.ceil(preset.heightM/h),off=.135,rowYs=Array.from({length:rows},(_,i)=>Math.min(preset.heightM-.095,.095+i*h));return <group>{rowYs.map((y,i)=>{const lift=(i%2)*.004;return <group key={i}><StripWall length={preset.widthM} pos={[0,y,-preset.depthM/2-off-lift]} rot={0} opacity={opacity}/>{!cutaway?<StripWall length={preset.widthM} pos={[0,y,preset.depthM/2+off+lift]} rot={0} opacity={opacity}/>:null}<StripWall length={preset.depthM} pos={[-preset.widthM/2-off-lift,y,0]} rot={Math.PI/2} opacity={opacity}/><StripWall length={preset.depthM} pos={[preset.widthM/2+off+lift,y,0]} rot={Math.PI/2} opacity={opacity}/></group>})}<CornerTrim preset={preset} opacity={opacity}/><Html center distanceFactor={10} position={[0,preset.heightM+.22,-preset.depthM/2-.2]}><Tag>Siding ref. 6×190×3.660 mm · traslape visual</Tag></Html></group>}
function StripWall({length,pos,rot,opacity}:{length:number;pos:[number,number,number];rot:number;opacity:number}){const max=3.66,count=Math.ceil(length/max),segment=length/count;return <group>{Array.from({length:count},(_,i)=><mesh key={i} position={[pos[0]+(rot?0:-length/2+segment/2+i*segment),pos[1],pos[2]+(rot?-length/2+segment/2+i*segment:0)]} rotation={[0,rot,0]} castShadow receiveShadow><boxGeometry args={[segment-.012,.176,.032]}/>{mat(i%2?'#aeb6b3':'#c3c9c6',opacity,0,.68)}</mesh>)}</group>}
function CornerTrim({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const x=preset.widthM/2+.155,z=preset.depthM/2+.155,y=preset.heightM/2;return <group>{[[-x,-z],[-x,z],[x,-z],[x,z]].map(([px,pz],i)=><mesh key={i} position={[px,y,pz]} castShadow><boxGeometry args={[.065,preset.heightM+.04,.065]}/>{mat('#767f80',opacity,.1,.55)}</mesh>)}</group>}
function Roof({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){
 if(opacity<=.01)return null;
 const run=preset.depthM/2+.48,rise=run*.275,eaveY=preset.heightM+.08,ridgeY=eaveY+rise,panelWidth=preset.widthM+.9;
 const trussSteps=Math.max(2,Math.ceil(preset.widthM/.6)),xs=Array.from({length:trussSteps+1},(_,i)=>-preset.widthM/2+i*preset.widthM/trussSteps);
 const slope=Math.sqrt(run*run+rise*rise),angle=Math.atan2(rise,run),midY=eaveY+rise/2;
 const purlinFractions=[.78,.52,.26],ribSteps=Math.max(5,Math.ceil(panelWidth/.52)),ribXs=Array.from({length:ribSteps+1},(_,i)=>-panelWidth/2+i*panelWidth/ribSteps);
 return <group>
  {xs.map(x=><group key={x}>
   <Beam3D from={[x,eaveY,-run]} to={[x,ridgeY,0]} opacity={opacity} thickness={.06}/>
   {!cutaway?<Beam3D from={[x,eaveY,run]} to={[x,ridgeY,0]} opacity={opacity} thickness={.06}/>:null}
   <Beam3D from={[x,eaveY,-run]} to={[x,eaveY,run]} opacity={opacity} thickness={.06}/>
   <Beam3D from={[x,eaveY,0]} to={[x,ridgeY,0]} opacity={opacity} thickness={.052}/>
   <Beam3D from={[x,eaveY,-run*.58]} to={[x,ridgeY-.08,0]} opacity={opacity*.95} thickness={.044} color="#909ba1"/>
   {!cutaway?<Beam3D from={[x,eaveY,run*.58]} to={[x,ridgeY-.08,0]} opacity={opacity*.95} thickness={.044} color="#909ba1"/>:null}
  </group>)}
  <mesh position={[0,ridgeY,0]}><boxGeometry args={[panelWidth,.075,.075]}/>{mat('#aeb8bf',opacity,.78,.3)}</mesh>
  <mesh position={[0,eaveY,-run]}><boxGeometry args={[panelWidth,.075,.075]}/>{mat('#aeb8bf',opacity,.78,.3)}</mesh>
  {!cutaway?<mesh position={[0,eaveY,run]}><boxGeometry args={[panelWidth,.075,.075]}/>{mat('#aeb8bf',opacity,.78,.3)}</mesh>:null}
  {purlinFractions.map(f=>{const z=-run*f,y=eaveY+rise*(1-f);return <mesh key={`pf${f}`} position={[0,y+.035,z]}><boxGeometry args={[panelWidth,.055,.07]}/>{mat('#9da8ae',opacity,.72,.34)}</mesh>})}
  {!cutaway?purlinFractions.map(f=>{const z=run*f,y=eaveY+rise*(1-f);return <mesh key={`pn${f}`} position={[0,y+.035,z]}><boxGeometry args={[panelWidth,.055,.07]}/>{mat('#9da8ae',opacity,.72,.34)}</mesh>}):null}
  <RoofPlane side="far-board" width={panelWidth} slope={slope} angle={-angle} y={midY+.07} z={-run/2} opacity={opacity} color="#a66f3d" thickness={.026}/>
  {!cutaway?<RoofPlane side="near-board" width={panelWidth} slope={slope} angle={angle} y={midY+.07} z={run/2} opacity={opacity} color="#a66f3d" thickness={.026}/>:null}
  <RoofPlane side="far-membrane" width={panelWidth} slope={slope} angle={-angle} y={midY+.105} z={-run/2} opacity={opacity*.84} color="#263a45" thickness={.012}/>
  {!cutaway?<RoofPlane side="near-membrane" width={panelWidth} slope={slope} angle={angle} y={midY+.105} z={run/2} opacity={opacity*.84} color="#263a45" thickness={.012}/>:null}
  <RoofPlane side="far-cover" width={panelWidth} slope={slope} angle={-angle} y={midY+.14} z={-run/2} opacity={opacity} color="#59666b" thickness={.035} metalness={.5}/>
  {!cutaway?<RoofPlane side="near-cover" width={panelWidth} slope={slope} angle={angle} y={midY+.14} z={run/2} opacity={opacity} color="#59666b" thickness={.035} metalness={.5}/>:null}
  {ribXs.map(x=><mesh key={`rf${x}`} position={[x,midY+.165,-run/2]} rotation={[-angle,0,0]}><boxGeometry args={[.018,.026,slope]}/>{mat('#849197',opacity,.65,.28)}</mesh>)}
  {!cutaway?ribXs.map(x=><mesh key={`rn${x}`} position={[x,midY+.165,run/2]} rotation={[angle,0,0]}><boxGeometry args={[.018,.026,slope]}/>{mat('#849197',opacity,.65,.28)}</mesh>):null}
  <mesh position={[0,ridgeY+.115,0]}><boxGeometry args={[panelWidth+.08,.095,.18]}/>{mat('#737f84',opacity,.65,.28)}</mesh>
  <mesh position={[0,eaveY-.02,-run]}><boxGeometry args={[panelWidth,.2,.065]}/>{mat('#657176',opacity,.62,.38)}</mesh>
  {!cutaway?<mesh position={[0,eaveY-.02,run]}><boxGeometry args={[panelWidth,.2,.065]}/>{mat('#657176',opacity,.62,.38)}</mesh>:null}
  <mesh position={[0,eaveY-.15,-run-.1]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.055,.055,panelWidth,12]}/>{mat('#606c71',opacity,.7,.3)}</mesh>
  {!cutaway?<mesh position={[0,eaveY-.15,run+.1]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.055,.055,panelWidth,12]}/>{mat('#606c71',opacity,.7,.3)}</mesh>:null}
  <mesh position={[panelWidth/2-.08,preset.heightM/2,-run-.1]}><cylinderGeometry args={[.038,.038,preset.heightM,10]}/>{mat('#606c71',opacity,.7,.3)}</mesh>
  <Html center distanceFactor={10} position={[0,ridgeY+.46,0]}><Tag>Cumbrera · cerchas/cabios ~0,60 m</Tag></Html>
  <Html center distanceFactor={10} position={[0,eaveY+rise*.5+.34,-run*.5]}><Tag>Correas + tablero + membrana + cubierta</Tag></Html>
  <Html center distanceFactor={10} position={[0,eaveY-.42,-run-.1]}><Tag>Alero · tapacán · canaleta</Tag></Html>
 </group>
}
function Beam3D({from,to,opacity,thickness,color='#aeb8bf'}:{from:[number,number,number];to:[number,number,number];opacity:number;thickness:number;color?:string}){const a=new Vector3(...from),b=new Vector3(...to),dir=b.clone().sub(a),len=dir.length(),mid=a.clone().add(b).multiplyScalar(.5),q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),dir.clone().normalize());return <mesh position={mid} quaternion={q} castShadow><boxGeometry args={[thickness,len,thickness]}/>{mat(color,opacity,.76,.32)}</mesh>}
function RoofPlane({side,width,slope,angle,y,z,opacity,color,thickness,metalness=0}:{side:string;width:number;slope:number;angle:number;y:number;z:number;opacity:number;color:string;thickness:number;metalness?:number}){return <mesh name={side} position={[0,y,z]} rotation={[angle,0,0]} castShadow receiveShadow><boxGeometry args={[width,thickness,slope]}/>{mat(color,opacity,metalness,metalness>.2?.42:.7)}</mesh>}
function Fixtures({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const bx=preset.widthM/2-.85,bz=-preset.depthM/2+Math.min(2.05,preset.depthM*.34),kx=-preset.widthM/2+Math.min(1.25,preset.widthM*.28),kz=-preset.depthM/2+.42;return <group><mesh position={[bx,.28,bz]}><cylinderGeometry args={[.22,.28,.34,20]}/>{mat('#f2f3ef',opacity)}</mesh><mesh position={[bx-.95,.06,bz+.2]}><boxGeometry args={[.88,.1,.88]}/>{mat('#d6d8d7',opacity)}</mesh><mesh position={[kx,.46,kz]}><boxGeometry args={[2.1,.9,.62]}/>{mat('#8c755f',opacity)}</mesh><mesh position={[kx+.35,.94,kz]}><boxGeometry args={[.7,.07,.42]}/>{mat('#a7b0b5',opacity,.5,.3)}</mesh><Html center distanceFactor={9} position={[bx,1,bz]}><Tag>Baño</Tag></Html><Html center distanceFactor={9} position={[kx,1.25,kz]}><Tag>Mesón + grifería</Tag></Html></group>}
function Sanitary({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const tx=preset.widthM/2+2.3,tz=preset.depthM/2-1.15;return <group><mesh position={[0,-.16,.45]}><boxGeometry args={[preset.widthM+1.8,.08,.12]}/>{mat('#d9e3e8',opacity)}</mesh><mesh position={[preset.widthM/2+.72,-.08,.45]}><boxGeometry args={[.55,.38,.55]}/>{mat('#737c80',opacity)}</mesh><mesh position={[-preset.widthM/2-.8,-.1,-preset.depthM/2+.8]}><boxGeometry args={[.58,.42,.58]}/>{mat('#8a7a61',opacity)}</mesh><group position={[tx,-.18,tz]}><mesh rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.58,.58,1.35,28]}/>{mat('#568896',opacity)}</mesh><Html center distanceFactor={10} position={[0,.9,0]}><Tag>Fosa 800 L · visual</Tag></Html></group></group>}
function Tag({children}:{children:ReactNode}){return <span className="whitespace-nowrap rounded-full border border-white/10 bg-black/82 px-2 py-1 text-[7px] font-black uppercase tracking-[.07em] text-white/78">{children}</span>}
