'use client';

import { useMemo, useState } from 'react';
import { Check, HardHat, Info, Ruler, ShieldCheck } from 'lucide-react';
import { calculateMetalcon, type MetalconInput } from '@/lib/metalconCalculator';
import { MetalconCinematicViewer } from '@/components/store/MetalconCinematicViewer';
import { StoreBottomNav, StorefrontHeader } from '@/components/store/StorefrontChrome';

export function MetalconCalculator() {
  const [input,setInput]=useState<MetalconInput>({widthM:6,heightM:2.4,spacingCm:40,osbWidthCm:122,hasDoor:true,hasWindow:true});
  const estimate=useMemo(()=>calculateMetalcon(input),[input]);
  const set=<K extends keyof MetalconInput>(key:K,value:MetalconInput[K])=>setInput(current=>({...current,[key]:value}));
  return <div className="min-h-screen bg-[#05090C] text-white"><StorefrontHeader/><main className="pb-28 md:pb-16">
    <section className="relative overflow-hidden border-b border-white/10 px-4 py-12 sm:px-8 sm:py-20"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(246,198,74,.15),transparent_38%),radial-gradient(circle_at_15%_80%,rgba(87,212,255,.1),transparent_35%)]"/><div className="relative mx-auto max-w-[1500px]"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#F6C64A]">Sistema constructivo · Metalcon</p><h1 className="mt-4 max-w-5xl text-[clamp(3rem,8vw,7.5rem)] font-black leading-[.86] tracking-[-.07em]">Diseña el panel antes de construirlo.</h1><p className="mt-6 max-w-2xl text-sm leading-6 text-white/60 sm:text-lg sm:leading-8">Configura medidas, revisa la modulación y entiende cómo se refuerzan puertas y ventanas en una vista clara por capas.</p></div></section>
    <section className="mx-auto grid max-w-[1500px] gap-5 px-3 py-6 sm:px-6 lg:grid-cols-[minmax(320px,.7fr)_minmax(0,1.3fr)] lg:gap-8 lg:py-10">
      <div className="rounded-[1.6rem] border border-white/10 bg-[#0A0F13] p-4 sm:p-6"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#57D4FF]">Calculadora preliminar</p><h2 className="mt-2 text-3xl font-black tracking-[-.05em]">Medidas del muro</h2><div className="mt-6 grid grid-cols-2 gap-3"><Field label="Largo (m)" value={input.widthM} min={.8} max={20} step={.1} onChange={value=>set('widthM',value)}/><Field label="Alto (m)" value={input.heightM} min={1.8} max={5} step={.1} onChange={value=>set('heightM',value)}/></div>
        <Choice label="Separación entre montantes" values={[40,60]} value={input.spacingCm} suffix=" cm" onChange={value=>set('spacingCm',value as 40|60)}/><Choice label="Ancho de plancha OSB" values={[120,122]} value={input.osbWidthCm} suffix=" cm" onChange={value=>set('osbWidthCm',value as 120|122)}/>
        <div className="mt-5 grid grid-cols-2 gap-2"><Toggle label="Incluir puerta" active={input.hasDoor} onClick={()=>set('hasDoor',!input.hasDoor)}/><Toggle label="Incluir ventana" active={input.hasWindow} onClick={()=>set('hasWindow',!input.hasWindow)}/></div>
        <div className="mt-6 grid grid-cols-2 gap-2"><Metric value={estimate.totalStuds} label="perfiles C aprox."/><Metric value={`${estimate.trackMeters} m`} label="canales sup./inf."/><Metric value={estimate.osbSheets} label="planchas OSB aprox."/><Metric value={estimate.openingReinforcements} label="refuerzos laterales"/></div>
        <div className="mt-5 flex gap-3 rounded-xl border border-[#F6C64A]/20 bg-[#F6C64A]/[.06] p-3 text-[10px] leading-4 text-white/56"><Info className="mt-0.5 shrink-0 text-[#F6C64A]" size={15}/><p>Estimación educativa con 10% de merma en OSB. Perfiles, espesores, dinteles, anclajes y cargas deben validarse mediante cálculo estructural y normativa chilena vigente.</p></div>
      </div><MetalconCinematicViewer input={input}/>
    </section>
    <section className="mx-auto max-w-[1500px] px-3 pb-10 sm:px-6"><div className="grid gap-3 md:grid-cols-3"><Benefit icon={<Ruler/>} title="Modulación clara" text="40 cm corresponde a la separación entre montantes verticales, no entre dinteles."/><Benefit icon={<ShieldCheck/>} title="Aberturas reforzadas" text="La vista resalta dos perfiles C por cada lateral de puerta y ventana."/><Benefit icon={<HardHat/>} title="Diseño responsable" text="El dintel horizontal superior se dimensiona según luz, cargas y especificación profesional."/></div><div className="mt-5 rounded-[1.6rem] border border-white/10 bg-gradient-to-br from-[#111A20] to-[#070B0E] p-5 sm:p-8"><h2 className="text-2xl font-black tracking-[-.04em]">Cómo leer la simulación</h2><ol className="mt-4 grid gap-4 text-xs leading-5 text-white/54 md:grid-cols-3"><li><b className="block text-[#F6C64A]">01 · Estructura</b>Canales superior e inferior y montantes distribuidos según la modulación seleccionada.</li><li><b className="block text-[#F6C64A]">02 · Refuerzos</b>Jambas dobles tipo C en ambos costados; dintel visible sobre cada vano.</li><li><b className="block text-[#F6C64A]">03 · Revestimiento</b>OSB de 120 o 122 cm mostrado por paños; las juntas deben coincidir con apoyos según especificación.</li></ol><p className="mt-5 text-[9px] text-white/28">Visualización web cinemática inspirada en herramientas 3D de obra. No ejecuta Cinema 4D ni Unreal Engine y no reemplaza planos de fabricación.</p></div></section>
  </main><StoreBottomNav/></div>;
}

function Field({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}){return <label className="text-[9px] font-bold text-white/48">{label}<input type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))} className="mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-base font-black text-white outline-none focus:border-[#F6C64A]/60"/></label>}
function Choice({label,values,value,suffix,onChange}:{label:string;values:number[];value:number;suffix:string;onChange:(value:number)=>void}){return <div className="mt-5"><p className="text-[9px] font-bold text-white/48">{label}</p><div className="mt-2 grid grid-cols-2 gap-2">{values.map(item=><button key={item} onClick={()=>onChange(item)} className={`h-11 rounded-xl text-xs font-black ${value===item?'bg-[#F6C64A] text-black':'border border-white/10 bg-white/[.03] text-white/60'}`}>{item}{suffix}</button>)}</div></div>}
function Toggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl border text-[10px] font-black ${active?'border-emerald-400/35 bg-emerald-400/10 text-emerald-300':'border-white/10 text-white/38'}`}>{active?<Check size={14}/>:null}{label}</button>}
function Metric({value,label}:{value:string|number;label:string}){return <div className="rounded-xl bg-white/[.045] p-3"><b className="text-xl text-[#F6C64A]">{value}</b><small className="mt-1 block text-[8px] leading-3 text-white/38">{label}</small></div>}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-[1.4rem] border border-white/10 bg-[#0A0F13] p-5"><span className="text-[#F6C64A] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-white/44">{text}</p></article>}
