'use client';
import { Html } from '@react-three/drei';
import type { ReactNode } from 'react';
import type { MetalconHousePreset } from '@/lib/metalconAssembly';
import type { MetalconLabLayer } from './metalconLabData';

const visible=(timeline:number,start:number)=>Math.min(1,Math.max(0,(timeline-start)/7));
export default function MetalconLabFinishesV2({preset,timeline,layers,cutaway}:{preset:MetalconHousePreset;timeline:number;layers:Record<MetalconLabLayer,boolean>;cutaway:boolean}){
 const scale=Math.min(1,8.4/Math.max(preset.widthM,preset.depthM+(preset.terraceDepthM??0)));
 return <group scale={scale}>
  <Foundation preset={preset} opacity={visible(timeline,0)}/>
  {layers.osb?<Shell preset={preset} offset={.055} thickness={.028} color="#b9824c" opacity={visible(timeline,40)*.9} cutaway={cutaway}/>:null}
  {layers.membrane?<Shell preset={preset} offset={.078} thickness={.012} color="#243b50" opacity={visible(timeline,49)*.62} cutaway={cutaway}/>:null}
  {layers.battens?<Battens preset={preset} opacity={visible(timeline,56)} cutaway={cutaway}/>:null}
  {layers.insulation?<Shell preset={preset} offset={-.025} thickness={.065} color="#e5c761" opacity={visible(timeline,62)*.52} cutaway={cutaway}/>:null}
  {layers.gypsum?<Shell preset={preset} offset={-.082} thickness={.016} color="#e7e3d8" opacity={visible(timeline,69)*.92} cutaway={cutaway}/>:null}
  {layers.floor?<Floor preset={preset} opacity={visible(timeline,75)}/>:null}
  {layers.ceiling?<Ceiling preset={preset} opacity={visible(timeline,81)}/>:null}
  {layers.fixtures?<Fixtures preset={preset} opacity={visible(timeline,86)}/>:null}
  {layers.sanitary?<Sanitary preset={preset} opacity={visible(timeline,91)}/>:null}
  {layers.siding?<Siding preset={preset} opacity={visible(timeline,95)} cutaway={cutaway}/>:null}
  {layers.roof?<Roof preset={preset} opacity={visible(timeline,98)} cutaway={cutaway}/>:null}
 </group>
}
function mat(color:string,opacity:number,metalness=0,roughness=.78){return <meshStandardMaterial color={color} roughness={roughness} metalness={metalness} transparent={opacity<.99} opacity={opacity}/>}
function Foundation({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){return <group><mesh position={[0,-.17,0]} receiveShadow><boxGeometry args={[preset.widthM+1,.18,preset.depthM+1]}/>{mat('#6c4b34',opacity*.72)}</mesh><mesh position={[0,-.04,0]} receiveShadow><boxGeometry args={[preset.widthM+.28,.22,preset.depthM+.28]}/>{mat('#747a7e',opacity*.7)}</mesh></group>}
function Shell({preset,offset,thickness,color,opacity,cutaway}:{preset:MetalconHousePreset;offset:number;thickness:number;color:string;opacity:number;cutaway:boolean}){if(opacity<=.01)return null;const y=preset.heightM/2;return <group><mesh position={[0,y,-preset.depthM/2-offset]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,thickness]}/>{mat(color,opacity)}</mesh>{!cutaway?<mesh position={[0,y,preset.depthM/2+offset]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,thickness]}/>{mat(color,opacity)}</mesh>:null}<mesh position={[-preset.widthM/2-offset,y,0]} castShadow><boxGeometry args={[thickness,preset.heightM,preset.depthM]}/>{mat(color,opacity)}</mesh><mesh position={[preset.widthM/2+offset,y,0]} castShadow><boxGeometry args={[thickness,preset.heightM,preset.depthM]}/>{mat(color,opacity)}</mesh></group>}
function Battens({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){const xs=Array.from({length:Math.ceil(preset.widthM/.6)+1},(_,i)=>-preset.widthM/2+i*preset.widthM/Math.ceil(preset.widthM/.6));const zs=Array.from({length:Math.ceil(preset.depthM/.6)+1},(_,i)=>-preset.depthM/2+i*preset.depthM/Math.ceil(preset.depthM/.6));return <group>{xs.map(x=><mesh key={`n${x}`} position={[x,preset.heightM/2,-preset.depthM/2-.098]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>)}{!cutaway?xs.map(x=><mesh key={`s${x}`} position={[x,preset.heightM/2,preset.depthM/2+.098]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>):null}{zs.flatMap(z=>[<mesh key={`w${z}`} position={[-preset.widthM/2-.098,preset.heightM/2,z]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>,<mesh key={`e${z}`} position={[preset.widthM/2+.098,preset.heightM/2,z]}><boxGeometry args={[.04,preset.heightM,.04]}/>{mat('#8b5a35',opacity)}</mesh>])}</group>}
function Floor({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const sx=Math.max(1,Math.floor(preset.widthM/.6)),sz=Math.max(1,Math.floor(preset.depthM/.6));return <group>{Array.from({length:sx},(_,x)=>Array.from({length:sz},(_,z)=><mesh key={`${x}-${z}`} position={[-preset.widthM/2+.3+x*.6,.045,-preset.depthM/2+.3+z*.6]} receiveShadow><boxGeometry args={[.585,.035,.585]}/>{mat((x+z)%2?'#d2d4d3':'#c5c8c8',opacity,0,.5)}</mesh>))}</group>}
function Ceiling({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const n=Math.ceil(preset.widthM/.6);return <group>{Array.from({length:n+1},(_,i)=>-preset.widthM/2+i*preset.widthM/n).map(x=><mesh key={x} position={[x,preset.heightM-.12,0]}><boxGeometry args={[.035,.035,preset.depthM]}/>{mat('#bcc4ca',opacity,.7,.3)}</mesh>)}<mesh position={[0,preset.heightM-.17,0]}><boxGeometry args={[preset.widthM-.08,.025,preset.depthM-.08]}/>{mat('#e9e5db',opacity*.9)}</mesh></group>}
function Siding({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){if(opacity<=.01)return null;const h=.19,rows=Math.ceil(preset.heightM/h),board=.025,off=.135;const rowYs=Array.from({length:rows},(_,i)=>Math.min(preset.heightM-.095,.095+i*h));return <group>{rowYs.map((y,i)=><group key={i}><StripWall length={preset.widthM} y={y} pos={[0,y,-preset.depthM/2-off]} rot={0} opacity={opacity}/>{!cutaway?<StripWall length={preset.widthM} y={y} pos={[0,y,preset.depthM/2+off]} rot={0} opacity={opacity}/>:null}<StripWall length={preset.depthM} y={y} pos={[-preset.widthM/2-off,y,0]} rot={Math.PI/2} opacity={opacity}/><StripWall length={preset.depthM} y={y} pos={[preset.widthM/2+off,y,0]} rot={Math.PI/2} opacity={opacity}/></group>)}<Html center distanceFactor={10} position={[0,preset.heightM+.22,-preset.depthM/2-.2]}><Tag>Siding ref. 6×190×3.660 mm</Tag></Html></group>}
function StripWall({length,pos,rot,opacity}:{length:number;y:number;pos:[number,number,number];rot:number;opacity:number}){const max=3.66,count=Math.ceil(length/max),segment=length/count;return <group>{Array.from({length:count},(_,i)=><mesh key={i} position={[pos[0]+(rot?0:-length/2+segment/2+i*segment),pos[1],pos[2]+(rot?-length/2+segment/2+i*segment:0)]} rotation={[0,rot,0]} castShadow><boxGeometry args={[segment-.012,.17,.025]}/>{mat(i%2?'#b5bbb9':'#c1c6c4',opacity,0,.72)}</mesh>)}</group>}
function Roof({preset,opacity,cutaway}:{preset:MetalconHousePreset;opacity:number;cutaway:boolean}){const rise=Math.max(.72,preset.widthM*.16),half=preset.depthM/2+.42,slope=Math.sqrt(half*half+rise*rise),angle=Math.atan2(rise,half),top=preset.heightM+rise/2+.06;const rafters=Array.from({length:Math.max(5,Math.ceil(preset.widthM/.6)+1)},(_,i)=>-preset.widthM/2+i*preset.widthM/Math.max(1,Math.ceil(preset.widthM/.6)));return <group position={[0,top,0]}>{rafters.map(x=><group key={x}><mesh position={[x,-.04,-preset.depthM/4]} rotation={[angle,0,0]}><boxGeometry args={[.04,.06,slope]}/>{mat('#b7c0c6',opacity,.72,.32)}</mesh>{!cutaway?<mesh position={[x,-.04,preset.depthM/4]} rotation={[-angle,0,0]}><boxGeometry args={[.04,.06,slope]}/>{mat('#b7c0c6',opacity,.72,.32)}</mesh>:null}</group>)}<mesh position={[0,0,-preset.depthM/4]} rotation={[angle,0,0]} castShadow><boxGeometry args={[preset.widthM+.75,.055,slope]}/>{mat('#4e5960',opacity,.35,.55)}</mesh>{!cutaway?<mesh position={[0,0,preset.depthM/4]} rotation={[-angle,0,0]} castShadow><boxGeometry args={[preset.widthM+.75,.055,slope]}/>{mat('#4e5960',opacity,.35,.55)}</mesh>:null}{Array.from({length:Math.ceil((preset.widthM+.6)/.52)},(_,i)=>-preset.widthM/2-.2+i*.52).map(x=><mesh key={x} position={[x,.035,-preset.depthM/4]} rotation={[angle,0,0]}><boxGeometry args={[.018,.02,slope]}/>{mat('#76848b',opacity,.7,.3)}</mesh>)}<mesh position={[0,rise/2+.02,0]}><boxGeometry args={[preset.widthM+.8,.07,.09]}/>{mat('#6f7c82',opacity,.7,.3)}</mesh><Html center distanceFactor={10} position={[0,rise/2+.32,0]}><Tag>Cubierta continua ref. 2–6 m</Tag></Html></group>}
function Fixtures({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const bx=preset.widthM/2-.85,bz=-preset.depthM/2+Math.min(2.05,preset.depthM*.34),kx=-preset.widthM/2+Math.min(1.25,preset.widthM*.28),kz=-preset.depthM/2+.42;return <group><mesh position={[bx,.28,bz]}><cylinderGeometry args={[.22,.28,.34,20]}/>{mat('#f2f3ef',opacity)}</mesh><mesh position={[bx-.95,.06,bz+.2]}><boxGeometry args={[.88,.1,.88]}/>{mat('#d6d8d7',opacity)}</mesh><mesh position={[kx,.46,kz]}><boxGeometry args={[2.1,.9,.62]}/>{mat('#8c755f',opacity)}</mesh><mesh position={[kx+.35,.94,kz]}><boxGeometry args={[.7,.07,.42]}/>{mat('#a7b0b5',opacity,.5,.3)}</mesh><Html center distanceFactor={9} position={[bx,1,bz]}><Tag>Baño</Tag></Html><Html center distanceFactor={9} position={[kx,1.25,kz]}><Tag>Mesón + grifería</Tag></Html></group>}
function Sanitary({preset,opacity}:{preset:MetalconHousePreset;opacity:number}){const tx=preset.widthM/2+2.3,tz=preset.depthM/2-1.15;return <group><mesh position={[0,-.16,.45]}><boxGeometry args={[preset.widthM+1.8,.08,.12]}/>{mat('#d9e3e8',opacity)}</mesh><mesh position={[preset.widthM/2+.72,-.08,.45]}><boxGeometry args={[.55,.38,.55]}/>{mat('#737c80',opacity)}</mesh><mesh position={[-preset.widthM/2-.8,-.1,-preset.depthM/2+.8]}><boxGeometry args={[.58,.42,.58]}/>{mat('#8a7a61',opacity)}</mesh><group position={[tx,-.18,tz]}><mesh rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.58,.58,1.35,28]}/>{mat('#568896',opacity)}</mesh><Html center distanceFactor={10} position={[0,.9,0]}><Tag>Fosa 800 L · visual</Tag></Html></group></group>}
function Tag({children}:{children:ReactNode}){return <span className="whitespace-nowrap rounded-full border border-white/10 bg-black/82 px-2 py-1 text-[7px] font-black uppercase tracking-[.07em] text-white/78">{children}</span>}
