'use client';

/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, BadgeCheck, Calculator, Check, ChevronRight, CreditCard, Minus, PackageCheck, Plus, ShieldCheck, ShoppingCart, Star, Truck } from 'lucide-react';
import { CART_SESSION_KEY, useCartContext } from '@/context/CartContext';
import { useCatalogProducts, type CatalogProduct } from '@/hooks/useCatalogProducts';
import { StoreBottomNav, StorefrontHeader } from '@/components/store/StorefrontChrome';
import { displayProductName, finalProductPrice, toCartProduct } from '@/components/store/featuredProducts';
import { navigateWithTransition } from '@/lib/routeTransition';

const CLP = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
const FALLBACK = 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1000&auto=format&fit=crop';
function img(product: CatalogProduct) { return product.img || product.image_url || FALLBACK; }
function discount(product: CatalogProduct) { return Math.max(0, Number(product.discountPercentage ?? product.discount_percentage ?? 0)); }
function categoryOf(product: CatalogProduct) { return product.category_name || product.category || product.category_id || 'Producto'; }
function isPrimitive(value: unknown): value is string | number | boolean { return ['string','number','boolean'].includes(typeof value); }
function humanizeKey(key:string){return key.replace(/[_-]+/g,' ').replace(/\b\w/g,l=>l.toUpperCase());}
function projectText(product:CatalogProduct){return `${product.name} ${product.description||''} ${product.tagline||''} ${categoryOf(product)}`.toLowerCase();}
function isRadierRelated(product:CatalogProduct){return /cement|radier|hormig|malla acma|gravilla|moldaje|barrera de humedad/.test(projectText(product));}
function isAirRelated(product:CatalogProduct){return /climat|aire acondicionado|btu|split/.test(projectText(product));}
function galleryFor(product:CatalogProduct){const candidates=[img(product)];const specs=product.specifications??{};for(const key of ['gallery','images','imagenes','imágenes']){const value=specs[key];if(Array.isArray(value)) value.forEach(v=>{if(typeof v==='string'&&v.trim())candidates.push(v.trim());});}return Array.from(new Set(candidates)).slice(0,6);}
function specificationRows(product:CatalogProduct){const ignored=new Set(['merchandising','gallery','images','imagenes','imágenes','seed']);const rows=Object.entries(product.specifications??{}).flatMap(([key,value])=>{if(ignored.has(key))return [];if(isPrimitive(value))return [[humanizeKey(key),String(value)] as [string,string]];if(Array.isArray(value)&&value.every(isPrimitive))return [[humanizeKey(key),value.map(String).join(' · ')] as [string,string]];return [];});if(product.dimensions&&product.dimensions!=='Especificación en ficha técnica'&&!rows.some(([k])=>k.toLowerCase().includes('medid')))rows.unshift(['Medidas',product.dimensions]);rows.push(['Categoría',categoryOf(product)]);return rows.slice(0,10);}
function isReferenceSeed(product:CatalogProduct){const seed=product.specifications?.seed;return Boolean(seed&&typeof seed==='object'&&!Array.isArray(seed)&&(seed as Record<string,unknown>).initialPriceOnly===true);}

export default function ProductDetailClientV2(){
  const params=useParams<{id:string}>();const router=useRouter();const {products,loading}=useCatalogProducts();const {items,addToCart,closeCart}=useCartContext();const [qty,setQty]=useState(1);const [added,setAdded]=useState(false);const [selectedImage,setSelectedImage]=useState('');
  const product=useMemo(()=>products.find(item=>String(item.id)===String(params?.id)),[products,params?.id]);
  useEffect(()=>{setQty(1);setSelectedImage('');},[params?.id]);
  const related=useMemo(()=>{if(!product)return [];const same=products.filter(item=>item.id!==product.id&&categoryOf(item)===categoryOf(product));const others=products.filter(item=>item.id!==product.id&&categoryOf(item)!==categoryOf(product));return [...same,...others].slice(0,4);},[product,products]);
  const nav=(href:string)=>navigateWithTransition(href,router);
  if(!product)return <div className="min-h-screen bg-[#05090C] text-white"><StorefrontHeader/><main className="grid min-h-[70vh] place-items-center px-5 text-center"><div><p className="text-sm text-white/45">{loading?'Cargando producto…':'Este producto ya no está disponible.'}</p><button onClick={()=>nav('/tienda')} className="mt-5 rounded-full bg-[#F6C64A] px-6 py-3 text-xs font-black text-black">Volver a la tienda</button></div></main><StoreBottomNav/></div>;

  const gross=finalProductPrice(product);const net=Math.round(gross/1.19);const iva=gross-net;const d=discount(product);const stock=Number.isFinite(Number(product.stock))?Number(product.stock):null;const rating=Math.max(0,Math.min(5,Number(product.rating||4.8)));const gallery=galleryFor(product);const visibleImage=selectedImage||gallery[0];const specs=specificationRows(product);const productName=displayProductName(product.name);const cartProduct=toCartProduct(product);const reference=isReferenceSeed(product);
  function add(openCheckout=false){if(stock===0)return;addToCart(cartProduct,qty);setAdded(true);window.setTimeout(()=>setAdded(false),1200);if(!openCheckout)return;const index=items.findIndex(item=>item.product.id===cartProduct.id);const next=index===-1?[...items,{product:cartProduct,quantity:qty}]:items.map((item,i)=>i===index?{...item,product:cartProduct,quantity:item.quantity+qty}:item);try{sessionStorage.setItem(CART_SESSION_KEY,JSON.stringify(next));}catch{}closeCart();router.push('/checkout?cart=1');}

  return <div className="min-h-screen bg-[#05090C] text-white">
    <StorefrontHeader onSearch={()=>nav('/tienda/catalogo')}/>
    <main className="mx-auto max-w-[1380px] px-4 pb-28 pt-5 sm:px-6 lg:px-8">
      <div className="mb-4 flex items-center justify-between"><button onClick={()=>router.back()} className="inline-flex items-center gap-2 text-[10px] font-black text-white/50"><ArrowLeft size={14}/> Volver</button><span className="text-[9px] uppercase tracking-[.14em] text-white/28">Código · {String(product.id).slice(-10)}</span></div>
      <section className="overflow-hidden rounded-[1.7rem] border border-white/10 bg-[#0A0F13] shadow-[0_32px_100px_rgba(0,0,0,.34)] lg:grid lg:grid-cols-[1.05fr_.95fr]">
        <div className="border-b border-white/[.07] bg-[#0D1418] p-3 lg:border-b-0 lg:border-r"><div className="grid gap-3 sm:grid-cols-[72px_1fr]">{gallery.length>1?<div className="order-2 flex gap-2 overflow-x-auto sm:order-1 sm:flex-col">{gallery.map(src=><button key={src} onClick={()=>setSelectedImage(src)} className={`h-16 w-16 shrink-0 rounded-xl border bg-white p-1 ${visibleImage===src?'border-[#F6C64A]':'border-white/10'}`}><img src={src} alt="" className="h-full w-full object-contain"/></button>)}</div>:null}<div className={`${gallery.length>1?'order-1 sm:order-2':''} relative grid min-h-[350px] place-items-center overflow-hidden rounded-[1.25rem] bg-[radial-gradient(circle_at_50%_35%,rgba(246,198,74,.07),transparent_45%)] p-5 sm:min-h-[540px]`}><img src={visibleImage} alt={productName} className="max-h-[520px] w-full object-contain drop-shadow-[0_35px_45px_rgba(0,0,0,.45)]"/>{d>0?<span className="absolute left-4 top-4 rounded-full bg-[#57D4FF] px-3 py-1.5 text-[9px] font-black text-black">-{Math.round(d)}%</span>:product.placement==='best_seller'?<span className="absolute left-4 top-4 rounded-full bg-[#F6C64A] px-3 py-1.5 text-[9px] font-black text-black">Más vendido</span>:null}</div></div></div>
        <div className="p-5 sm:p-8 lg:p-9"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#F6C64A]">{categoryOf(product)}</p><h1 className="mt-3 text-[clamp(2.2rem,6vw,4rem)] font-black leading-[.92] tracking-[-.06em]">{productName}</h1>{product.tagline?<p className="mt-3 text-sm text-white/48">{product.tagline}</p>:null}<div className="mt-4 flex flex-wrap items-center gap-3"><div className="flex">{Array.from({length:5},(_,i)=><Star key={i} className={`h-4 w-4 ${i<Math.round(rating)?'fill-[#F6C64A] text-[#F6C64A]':'text-white/12'}`}/>)}</div><span className="text-xs font-bold text-white/50">{rating.toFixed(1)}</span><span className={`rounded-full border px-3 py-1 text-[9px] font-black ${stock===0?'border-red-400/30 bg-red-400/10 text-red-300':'border-emerald-400/25 bg-emerald-400/10 text-emerald-300'}`}>{stock===0?'Sin stock':stock==null?'Stock por confirmar':'En stock'}</span></div>
          <div className="mt-6 rounded-[1.2rem] border border-white/10 bg-white/[.025] p-4"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/38">{reference?'Precio referencial':'Precio publicado · IVA incluido'}</p><b className="mt-1 block text-4xl tracking-[-.055em] sm:text-5xl">{CLP.format(gross)}</b>{reference?<p className="mt-2 text-[10px] leading-4 text-white/38">Valor inicial del catálogo. Puedes modificar precio, descripción e imágenes desde administración.</p>:null}<div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div className="rounded-xl bg-black/22 p-3"><span className="text-white/35">Neto contenido</span><b className="mt-1 block">{CLP.format(net)}</b></div><div className="rounded-xl bg-black/22 p-3"><span className="text-white/35">IVA 19%</span><b className="mt-1 block">{CLP.format(iva)}</b></div></div></div>
          <p className="mt-5 text-sm leading-6 text-white/48">{product.description||'Producto seleccionado para completar tu proyecto.'}</p>
          <div className="mt-5 grid gap-2"><Trust icon={<Truck/>} title="Despacho por región" text="El checkout calcula la tarifa configurada antes de abrir el pago."/><Trust icon={<ShieldCheck/>} title="Compra protegida" text="Stock reservado y pago conciliado antes de confirmar el pedido."/><Trust icon={<BadgeCheck/>} title="Catálogo administrable" text="Stock, imagen, descripción y precio se gestionan desde el panel."/></div>
          <div className="mt-5 flex items-end justify-between gap-4 border-t border-white/10 pt-5"><div><p className="text-[9px] uppercase tracking-[.12em] text-white/35">Cantidad</p><div className="mt-2 flex items-center rounded-xl border border-white/10 bg-white/[.035] p-1"><button onClick={()=>setQty(q=>Math.max(1,q-1))} className="grid h-9 w-9 place-items-center"><Minus size={15}/></button><b className="w-10 text-center">{qty}</b><button onClick={()=>setQty(q=>stock==null?q+1:Math.min(stock,q+1))} className="grid h-9 w-9 place-items-center"><Plus size={15}/></button></div></div><div className="text-right"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">Subtotal</p><b className="mt-1 block text-xl">{CLP.format(gross*qty)}</b></div></div>
          <div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>add(false)} disabled={stock===0} className={`flex min-h-14 items-center justify-center gap-2 rounded-full border px-5 text-sm font-black ${added?'border-emerald-400 bg-emerald-400 text-black':'border-[#F6C64A] bg-[#F6C64A] text-black'} disabled:opacity-35`}>{added?<Check size={18}/>:<ShoppingCart size={18}/>} {added?'Añadido':'Agregar al carrito'}</button><button onClick={()=>add(true)} disabled={stock===0} className="flex min-h-14 items-center justify-center gap-2 rounded-full border border-white/15 bg-white/[.035] px-5 text-sm font-black disabled:opacity-35"><CreditCard size={18}/> Comprar ahora <ChevronRight size={15}/></button></div>
          {isRadierRelated(product)?<button onClick={()=>nav('/herramientas/radier')} className="mt-2 flex min-h-12 w-full items-center justify-center gap-2 rounded-full border border-[#F6C64A]/35 bg-[#F6C64A]/[.06] text-xs font-black text-[#F6C64A]"><Calculator size={16}/> Calcular mi radier <ChevronRight size={15}/></button>:null}{isAirRelated(product)?<button onClick={()=>nav('/herramientas/aire-acondicionado')} className="mt-2 flex min-h-12 w-full items-center justify-center gap-2 rounded-full border border-[#57D4FF]/35 bg-[#57D4FF]/[.06] text-xs font-black text-[#57D4FF]"><Calculator size={16}/> Calcular mi aire ideal <ChevronRight size={15}/></button>:null}
        </div>
      </section>

      <section className="mt-5 grid gap-3 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[1.5rem] border border-white/10 bg-[#0A0F13] p-5 sm:p-6"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Características principales</p><div className="mt-4 divide-y divide-white/[.07]">{specs.map(([label,value])=><div key={`${label}-${value}`} className="grid grid-cols-[.8fr_1.2fr] gap-3 py-3 text-xs"><span className="text-white/38">{label}</span><b>{value}</b></div>)}</div></article><article className="rounded-[1.5rem] border border-white/10 bg-[#0A0F13] p-5 sm:p-6"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Antes de comprar</p><h2 className="mt-2 text-xl font-black">Revisa tu proyecto primero.</h2><p className="mt-3 text-xs leading-5 text-white/42">Si este producto depende de medidas, usa la calculadora correspondiente. Así reduces compras de capacidad o cantidades equivocadas.</p><div className="mt-4 grid gap-2"><div className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 p-3"><PackageCheck className="h-5 w-5 text-[#F6C64A]"/><span className="text-[10px]">Stock confirmado nuevamente en checkout</span></div><div className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/20 p-3"><ShieldCheck className="h-5 w-5 text-[#F6C64A]"/><span className="text-[10px]">El servidor valida precio y disponibilidad</span></div></div></article></section>

      {related.length?<section className="mt-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">También te puede servir</h2><button onClick={()=>nav('/tienda/catalogo')} className="text-[10px] font-black text-[#F6C64A]">Ver todos →</button></div><div className="mt-4 grid grid-cols-2 gap-2.5 sm:grid-cols-4">{related.map(item=><Related key={item.id} product={item} onOpen={()=>nav(`/tienda/${item.id}`)}/>)}</div></section>:null}
    </main><StoreBottomNav/>
  </div>;
}

function Trust({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3 rounded-xl border border-white/[.07] bg-white/[.025] p-3"><span className="text-[#F6C64A] [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><b className="block text-[10px]">{title}</b><small className="mt-1 block text-[9px] leading-4 text-white/35">{text}</small></div></div>;}
function Related({product,onOpen}:{product:CatalogProduct;onOpen:()=>void}){return <article className="overflow-hidden rounded-[1.15rem] border border-white/10 bg-[#0A0F13]"><button onClick={onOpen} className="aspect-[1.1/1] w-full bg-[#0E1418] p-3"><img src={img(product)} alt={product.name} loading="lazy" className="h-full w-full object-contain"/></button><div className="p-3"><p className="text-[8px] uppercase text-[#57D4FF]">{categoryOf(product)}</p><button onClick={onOpen} className="mt-1 line-clamp-2 min-h-[2.3rem] text-left text-xs font-black">{product.name}</button><b className="mt-3 block text-base">{CLP.format(finalProductPrice(product))}</b></div></article>;}
