'use client';
import Link from 'next/link';
import { Canvas } from '@react-three/fiber';
import { ArrowLeft, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Layers3, Menu, Mountain, PackageOpen, Pause, Play, RotateCcw, TreePine, X } from 'lucide-react';
import { Suspense, useEffect, useMemo, useState, type ReactNode } from 'react';
import { calculateRadier, RADIER_SHAPES, type RadierShape } from '@/lib/radierCalculator';
import RadierLabSceneV2, { type RadierLabLayer, type RadierLightMode } from './RadierLabSceneV2';
import { RADIER_LAB_STAGES, radierStageIndex, radierStageStats } from './radierLabStages';

type Drawer='measures'|'materials'|'layers'|'environment'|null;
export default function RadierConstructionLabV2(){
 const[length,setLength]=useState(6),[width,setWidth]=useState(4),[thickness,setThickness]=useState(10),[baseDepth,setBaseDepth]=useState(10),[gravelDepth,setGravelDepth]=useState(5);
 const[shape,setShape]=useState<RadierShape>('rectangular'),[timeline,setTimeline]=useState(100),[playing,setPlaying]=useState(false),[drawer,setDrawer]=useState<Drawer>(null),[light,setLight]=useState<RadierLightMode>('day'),[exploded,setExploded]=useState(false),[autoRotate,setAutoRotate]=useState(false),[stageOpen,setStageOpen]=useState(false);
 const[layers,setLayers]=useState<Record<RadierLabLayer,boolean>>({excavation:true,fill:true,base:true,gravel:true,barrier:true,mesh:true,concrete:true,formwork:true,vegetation:true});
 const result=useMemo(()=>calculateRadier({length,width,thickness,baseDepth,gravelDepth,shape}),[length,width,thickness,baseDepth,gravelDepth,shape]);
 const stageIndex=radierStageIndex(timeline),stage=RADIER_LAB_STAGES[stageIndex],stats=useMemo(()=>radierStageStats({result,stage,baseDepth,gravelDepth,thickness}),[result,stage,baseDepth,gravelDepth,thickness]);
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setTimeline(v=>{if(v>=100){setPlaying(false);return 100}return Math.min(100,v+1)}),115);return()=>window.clearInterval(id)},[playing]);
 const play=()=>{setTimeline(v=>v>=100?0:v);setPlaying(true);setAutoRotate(false);setStageOpen(false)},reset=()=>{setPlaying(false);setTimeline(0)},jump=(d:number)=>{setPlaying(false);setTimeline(RADIER_LAB_STAGES[Math.max(0,Math.min(RADIER_LAB_STAGES.length-1,stageIndex+d))].start)},toggle=(id:RadierLabLayer)=>setLayers(v=>({...v,[id]:!v[id]}));
 const status=timeline>=100?'Terminado':playing?'Ejecutando':'Pausado';
 return <div className="fixed inset-0 z-[120] overflow-hidden bg-[#020507] text-white">
  <div className="absolute inset-0"><Canvas shadows dpr={[1,1.55]} camera={{position:[8,5.3,9],fov:43,near:.05,far:150}}><Suspense fallback={null}><RadierLabSceneV2 length={length} width={width} thickness={thickness} baseDepth={baseDepth} gravelDepth={gravelDepth} shape={shape} timeline={timeline} layers={layers} exploded={exploded} light={light} autoRotate={autoRotate}/></Suspense></Canvas></div>
  <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.6),transparent_27%,transparent_68%,rgba(0,0,0,.76))]"/>
  <header className="absolute inset-x-0 top-0 z-30 flex items-center justify-between gap-2 p-3 sm:p-4"><Link href="/herramientas/radier" className="inline-flex h-11 items-center gap-2 rounded-full border border-white/12 bg-black/62 px-4 text-[10px] font-black backdrop-blur-xl"><ArrowLeft size={15}/> Radier</Link><div className="hidden rounded-full border border-white/10 bg-black/58 px-4 py-2 text-center backdrop-blur-xl sm:block"><span className="block text-[8px] font-black uppercase tracking-[.2em] text-[#F6C64A]">Radier Lab 4D</span><b className="text-[10px]">{stage.name} · +0,30 m</b></div><button onClick={()=>setDrawer(v=>v?null:'measures')} className="inline-flex h-11 items-center gap-2 rounded-full border border-white/12 bg-black/62 px-4 text-[10px] font-black backdrop-blur-xl"><Menu size={15}/> Menú</button></header>
  <div className="absolute left-3 top-[70px] z-30 flex gap-1 rounded-full border border-white/10 bg-black/56 p-1 backdrop-blur-xl sm:left-4 sm:top-[76px]"><Quick active={exploded} onClick={()=>setExploded(v=>!v)} icon={<Layers3 size={12}/>} label="Capas"/><Quick active={layers.excavation} onClick={()=>toggle('excavation')} icon={<Mountain size={12}/>} label="Excavación"/><Quick active={layers.vegetation} onClick={()=>toggle('vegetation')} icon={<TreePine size={12}/>} label="Vegetación"/></div>
  <div className="absolute left-3 top-[118px] z-20 w-[min(330px,calc(100vw-24px))] sm:left-4 sm:top-[124px]"><div className={`overflow-hidden rounded-[1.1rem] border border-white/12 shadow-xl backdrop-blur-xl transition-colors ${stageOpen?'bg-[#071017]/90':'bg-black/64'}`}><button onClick={()=>setStageOpen(v=>!v)} aria-expanded={stageOpen} className="flex w-full items-center justify-between gap-3 px-3 py-2.5 text-left"><div className="min-w-0"><p className="text-[7px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Etapa actual</p><h2 className="mt-0.5 truncate text-[13px] font-black">{stage.name}</h2></div><div className="flex shrink-0 items-center gap-1.5"><span className="rounded-full bg-white/10 px-2 py-1 text-[6px] font-black uppercase text-white/60">{status}</span>{stageOpen?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</div></button><div className="grid grid-cols-3 gap-1 border-t border-white/8 px-2.5 py-2"><StageMetricCompact label="Espesor" value={stats.thickness}/><StageMetricCompact label="Cota" value={stats.depth}/><StageMetricCompact label="Volumen" value={stats.quantity}/></div>{stageOpen?<div className="max-h-[26dvh] overflow-y-auto border-t border-white/8 px-3 py-2.5"><p className="text-[8px] leading-4 text-white/48">{stage.description}</p><div className="mt-2 grid grid-cols-2 gap-1.5"><StageMetric label="Área" value={stats.area}/><StageMetric label="Volumen / medida" value={stats.quantity}/></div><p className="mt-2 text-[7px] leading-3 text-white/32">Toca la cabecera para volver al modo compacto y liberar el visor.</p></div>:null}</div></div>
  {drawer?<aside className="absolute bottom-[98px] right-3 top-[68px] z-40 w-[min(390px,calc(100vw-24px))] overflow-y-auto rounded-[1.5rem] border border-white/12 bg-[#071017]/96 p-4 shadow-2xl backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#F6C64A]">Controles</p><h2 className="mt-1 text-lg font-black">{drawer==='measures'?'Medidas y forma':drawer==='materials'?'Materiales y costos':drawer==='layers'?'Capas':'Entorno'}</h2></div><button onClick={()=>setDrawer(null)} aria-label="Cerrar menú" className="grid h-9 w-9 place-items-center rounded-full bg-white/[.06]"><X size={15}/></button></div><div className="mt-4 grid grid-cols-4 gap-1"><Tab active={drawer==='measures'} onClick={()=>setDrawer('measures')} label="Medidas"/><Tab active={drawer==='materials'} onClick={()=>setDrawer('materials')} label="Análisis"/><Tab active={drawer==='layers'} onClick={()=>setDrawer('layers')} label="Capas"/><Tab active={drawer==='environment'} onClick={()=>setDrawer('environment')} label="Entorno"/></div>
   {drawer==='measures'?<div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-2"><Num label="Largo (m)" value={length} min={1} max={20} step={.5} onChange={setLength}/><Num label="Ancho (m)" value={width} min={1} max={20} step={.5} onChange={setWidth}/><Num label="Espesor (cm)" value={thickness} min={5} max={30} step={1} onChange={setThickness}/><Num label="Base (cm)" value={baseDepth} min={5} max={30} step={1} onChange={setBaseDepth}/><Num label="Gravilla (cm)" value={gravelDepth} min={3} max={20} step={1} onChange={setGravelDepth}/></div><div className="flex flex-wrap gap-1">{RADIER_SHAPES.map(s=><button key={s.id} onClick={()=>setShape(s.id)} className={`rounded-full px-3 py-2 text-[8px] font-black ${shape===s.id?'bg-[#F6C64A] text-black':'bg-white/[.05] text-white/48'}`}>{s.label}</button>)}</div></div>:null}
   {drawer==='materials'?<MaterialsAnalysis result={result}/>:null}
   {drawer==='layers'?<div className="mt-4 space-y-2">{([['excavation','Excavación'],['fill','Relleno'],['base','Base'],['gravel','Gravilla'],['barrier','Barrera'],['mesh','Malla ACMA'],['concrete','Hormigón'],['formwork','Moldaje'],['vegetation','Vegetación']] as Array<[RadierLabLayer,string]>).map(([id,label])=><Toggle key={id} label={label} active={layers[id]} onClick={()=>toggle(id)}/>)}</div>:null}
   {drawer==='environment'?<div className="mt-4 space-y-3"><div className="grid grid-cols-3 gap-1">{(['day','sunset','night'] as RadierLightMode[]).map(m=><button key={m} onClick={()=>setLight(m)} className={`rounded-xl py-2 text-[9px] font-black ${light===m?'bg-[#F6C64A] text-black':'bg-white/[.05] text-white/48'}`}>{m==='day'?'Día':m==='sunset'?'Atardecer':'Noche'}</button>)}</div><Toggle label="Giro automático" active={autoRotate} onClick={()=>setAutoRotate(v=>!v)}/></div>:null}
  </aside>:null}
  <div className="absolute bottom-3 left-3 right-3 z-30 rounded-[1.35rem] border border-white/12 bg-black/72 p-3 backdrop-blur-2xl"><div className="flex items-center gap-2"><button onClick={playing?()=>setPlaying(false):play} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#F6C64A] text-black">{playing?<Pause size={16}/>:<Play size={16}/>}</button><button onClick={()=>jump(-1)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.07]"><ChevronLeft size={15}/></button><div className="min-w-0 flex-1"><div className="mb-1 flex justify-between"><b className="truncate text-[8px] uppercase text-[#F6C64A]">{stage.name}</b><span className="text-[8px] text-white/38">{timeline}%</span></div><input aria-label="Secuencia constructiva del radier" type="range" min={0} max={100} value={timeline} onChange={e=>{setPlaying(false);setTimeline(Number(e.target.value))}} className="w-full accent-[#F6C64A]"/></div><button onClick={()=>jump(1)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.07]"><ChevronRight size={15}/></button><button onClick={reset} className="grid h-11 w-11 place-items-center rounded-full bg-white/[.07]"><RotateCcw size={15}/></button></div></div>
 </div>
}
function Quick({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:ReactNode;label:string}){return <button onClick={onClick} className={`inline-flex items-center gap-1 rounded-full px-3 py-2 text-[8px] font-black ${active?'bg-[#F6C64A] text-black':'text-white/55'}`}>{icon}{label}</button>}
function Tab({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-xl py-2 text-[8px] font-black ${active?'bg-white text-black':'bg-white/[.05] text-white/45'}`}>{label}</button>}
function Toggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center justify-between rounded-xl border border-white/8 bg-white/[.025] px-3 py-3"><span className="text-[9px] text-white/65">{label}</span><span className={`rounded-full px-2 py-1 text-[7px] font-black ${active?'bg-[#F6C64A] text-black':'bg-white/10'}`}>{active?'ON':'OFF'}</span></button>}
function Num({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void}){return <label className="rounded-xl border border-white/8 bg-white/[.025] p-3"><span className="text-[8px] uppercase text-white/38">{label}</span><input type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Math.min(max,Math.max(min,Number(e.target.value)||min)))} className="mt-2 w-full bg-transparent text-lg font-black outline-none"/></label>}
function StageMetric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-white/8 bg-black/28 p-2"><span className="block text-[7px] uppercase text-white/30">{label}</span><b className="mt-1 block text-[9px] text-white/80">{value}</b></div>}
function StageMetricCompact({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-lg bg-white/[.045] px-2 py-1.5"><span className="block truncate text-[6px] font-bold uppercase text-white/28">{label}</span><b className="mt-0.5 block truncate text-[8px] text-white/78">{value}</b></div>}

type RadierResult=ReturnType<typeof calculateRadier>;
const decimal=(value:number,digits=1)=>value.toLocaleString('es-CL',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const money=(value:number)=>value.toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
function MaterialsAnalysis({result}:{result:RadierResult}){
 const completePlans=result.plans.filter(plan=>plan.id!=='materiales');
 const priceFrom=Math.min(...completePlans.map(plan=>plan.total)),priceTo=Math.max(...completePlans.map(plan=>plan.total));
 return <div className="mt-4 space-y-3">
  <section className="rounded-2xl border border-cyan-300/20 bg-cyan-400/[.07] p-3"><div className="flex items-center gap-2 text-cyan-200"><PackageOpen size={15}/><h3 className="text-[10px] font-black uppercase tracking-[.12em]">Cubicación de hormigón</h3></div><div className="mt-3 grid grid-cols-2 gap-2"><AnalysisMetric tone="yellow" label="Hormigón" value={`${decimal(result.concrete,2)} m³`}/><AnalysisMetric tone="red" label="Cemento 25 kg" value={`${result.cementBags25} sacos`}/><AnalysisMetric tone="cyan" label="Arena mezcla" value={`${decimal(result.sand,2)} m³`}/><AnalysisMetric tone="green" label="Gravilla mezcla" value={`${decimal(result.mixGravel,2)} m³`}/></div><p className="mt-2 text-[8px] leading-4 text-cyan-50/65">Cada saco rinde aprox. <b className="text-white">{decimal(result.cementBagCoverageLiters,0)} L</b> ({decimal(result.cementBagCoverageM3,3)} m³) con dosificación volumétrica referencial 4×8×9: 4 partes cemento, 8 arena y 9 gravilla.</p></section>
  <section className="rounded-2xl border border-violet-300/20 bg-violet-400/[.07] p-3"><h3 className="text-[10px] font-black uppercase tracking-[.12em] text-violet-200">Mezclado y transporte</h3><div className="mt-3 grid grid-cols-2 gap-2"><AnalysisMetric tone="cyan" label="Trompo útil 130 L" value={`${result.mixerBatches} cargas`}/><AnalysisMetric tone="yellow" label="Mezclado manual" value={`≈ ${result.manualMixHours} h`}/><AnalysisMetric tone="green" label="Camión mixer 7 m³" value={`${result.mixerTrucks} despacho${result.mixerTrucks===1?'':'s'}`}/><AnalysisMetric tone="red" label="Volumen a pedir" value={`${decimal(result.concrete,2)} m³`}/></div><p className="mt-2 text-[8px] leading-4 text-violet-50/60">Para trompo: mantén siempre la proporción 4:8:9 y mide todas las partes con el mismo recipiente. En camión, confirma resistencia, asentamiento, acceso y mínimo de despacho con la planta.</p></section>
  <section className="rounded-2xl border border-emerald-300/20 bg-emerald-400/[.07] p-3"><h3 className="text-[10px] font-black uppercase tracking-[.12em] text-emerald-200">Tiempo y precio comparativo</h3><div className="mt-3 grid grid-cols-2 gap-2"><AnalysisMetric tone="green" label="Ejecución estimada" value={`${result.executionDaysFrom}–${result.executionDaysTo} días`}/><AnalysisMetric tone="cyan" label="Hormigonado" value={`≈ ${result.pourHours} h`}/></div><div className="mt-2 rounded-xl border border-emerald-200/15 bg-black/25 p-3"><span className="text-[7px] font-black uppercase tracking-[.12em] text-emerald-100/55">Completo, desde–hasta</span><b className="mt-1 block text-base text-emerald-200">{money(priceFrom)} – {money(priceTo)}</b><span className="mt-1 block text-[8px] text-white/50">Referencia con IVA según planes estándar y reforzado del simulador.</span></div><p className="mt-2 text-[8px] leading-4 text-white/45">Considera curado inicial mínimo de 7 días y resistencia de referencia a 28 días. Cálculo educativo: validar dosificación y refuerzo con profesional según suelo, uso y proyecto.</p></section>
 </div>
}
function AnalysisMetric({label,value,tone}:{label:string;value:string;tone:'yellow'|'red'|'cyan'|'green'}){const styles={yellow:'border-yellow-300/20 bg-yellow-300/10 text-yellow-200',red:'border-red-400/20 bg-red-500/10 text-red-300',cyan:'border-cyan-300/20 bg-cyan-300/10 text-cyan-200',green:'border-emerald-300/20 bg-emerald-300/10 text-emerald-200'};return <div className={`rounded-xl border p-2.5 ${styles[tone]}`}><span className="block text-[7px] font-black uppercase tracking-[.1em] opacity-60">{label}</span><b className="mt-1 block text-[11px] text-current">{value}</b></div>}
