'use client';
import Link from 'next/link';
import { Canvas } from '@react-three/fiber';
import { Html, OrbitControls, Sky } from '@react-three/drei';
import { ChevronLeft, Menu, Pause, Play, RotateCcw, X } from 'lucide-react';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { METALCON_HOUSE_PRESET_ORDER, METALCON_HOUSE_PRESETS, type MetalconHousePresetId } from '@/lib/metalconAssembly';
import { MetalconAssembly3D, type MetalconSeismicVisual } from './MetalconAssembly3D';
import MetalconLabFinishesV2 from './MetalconLabFinishesV2';
import MetalconSanitaryNetworkV2 from './MetalconSanitaryNetworkV2';
import WoodFrameSeismicModelV2 from './WoodFrameSeismicModelV2';
import { compareSystems, SEISMIC_SOILS, type SeismicConfig, type SeismicSoil, type SystemResult } from './seismicComparisonModel';
import type { MetalconLabLayer } from './metalconLabData';

type Drawer='controls'|'comparison'|'layers'|null;
type DamageRow={system:'Metalcon'|'Madera';element:string;percent:number;mode:string;action:string};
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v));
function phase(p:number){return p<=.01?'Listo':p<.25?'Ruptura y propagación':p<.55?'Llegada a superficie':p<.82?'Respuesta estructural':p<1?'Evaluando afectación':'Comparación completa'}
export default function StructuralMonitoringComparisonShellV3(){
 const[modelId,setModelId]=useState<MetalconHousePresetId>('family-6x8'),[config,setConfig]=useState<SeismicConfig>({magnitude:7.2,depthKm:28,distanceKm:35,duration:22,soil:'firm',directionDeg:25,frequencyHz:2.4}),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[drawer,setDrawer]=useState<Drawer>(null),[showDamage,setShowDamage]=useState(true),[showRoof,setShowRoof]=useState(true),[showPanels,setShowPanels]=useState(true),[showCeiling,setShowCeiling]=useState(false),[showSanitary,setShowSanitary]=useState(false);
 const preset=METALCON_HOUSE_PRESETS[modelId],result=useMemo(()=>compareSystems(config),[config]);
 useEffect(()=>{if(!playing)return;const ms=50,seconds=clamp(10+config.duration*.22,10,24),id=window.setInterval(()=>setProgress(v=>{const n=v+ms/(seconds*1000);if(n>=1){setPlaying(false);return 1}return n}),ms);return()=>window.clearInterval(id)},[playing,config.duration]);
 useEffect(()=>{setPlaying(false);setProgress(0);setDrawer(null)},[modelId]);
 const play=()=>{setProgress(v=>v>=.999?0:v);setDrawer(null);setPlaying(true)},reset=()=>{setPlaying(false);setProgress(0);setDrawer(null)};
 const damageVisible=showDamage&&progress>.62;
 const panelScores=useMemo(()=>Object.fromEntries(preset.walls.map((w,i)=>{const score=clamp(result.metal.response*(.84+(i%4)*.07));return[w.id,damageVisible&&score>.39?(score>.72?.94:.82):0]})),[preset,result.metal.response,damageVisible]);
 const visual:MetalconSeismicVisual={active:playing,progress,amplitude:result.metal.response*.22,frequencyHz:config.frequencyHz,directionDeg:config.directionDeg,panelScores,showDamage,showSupports:true};
 const finishLayers=useMemo<Record<MetalconLabLayer,boolean>>(()=>({structure:false,osb:showPanels,membrane:showPanels,battens:false,insulation:showPanels,electrical:false,gypsum:showPanels,ceiling:showCeiling,floor:false,siding:false,roof:showRoof,fixtures:false,sanitary:false,vegetation:false}),[showPanels,showCeiling,showRoof]);
 const damageRows=useMemo(()=>buildDamageRows(result.metal,result.wood,progress),[result.metal,result.wood,progress]);
 return <section className="relative h-[100dvh] min-h-[620px] overflow-hidden bg-[#05090d] text-white">
  <Canvas shadows dpr={[1,1.55]} camera={{position:[0,6.4,17.5],fov:48,near:.05,far:200}}><Suspense fallback={null}><color attach="background" args={['#8fb8d3']}/><Sky distance={450000} sunPosition={[45,42,28]} turbidity={5} rayleigh={2}/><ambientLight intensity={.5}/><hemisphereLight args={['#dceffc','#3a2d25',.55]}/><directionalLight position={[45,42,28]} intensity={2.1} castShadow shadow-mapSize={[2048,2048]}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.13,0]} receiveShadow><planeGeometry args={[55,44]}/><meshStandardMaterial color="#617d50" roughness={1}/></mesh><group position={[-5.1,0,0]}><MetalconAssembly3D preset={preset} spacingCm={40} profileDepthMm={90} displayMode="bracing" seismic={visual}/><MetalconLabFinishesV2 preset={preset} timeline={100} layers={finishLayers} cutaway/>{showSanitary?<MetalconSanitaryNetworkV2 preset={preset}/>:null}<Html center distanceFactor={11} position={[0,preset.heightM+1.45,0]}><SystemLabel title="Metalcon" detail="acero galvanizado · daño en rojo"/></Html></group><group position={[5.1,0,0]}><WoodFrameSeismicModelV2 preset={preset} active={playing} progress={progress} response={result.wood.response} frequencyHz={config.frequencyHz} directionDeg={config.directionDeg} showDamage={showDamage} showRoof={showRoof} showPanels={showPanels}/></group><OrbitControls makeDefault target={[0,1.1,0]} enableDamping dampingFactor={.08} minDistance={7} maxDistance={30} maxPolarAngle={Math.PI*.86}/></Suspense></Canvas>
  <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.55),transparent_25%,transparent_70%,rgba(0,0,0,.72))]"/>
  <header className="absolute inset-x-0 top-0 z-20 flex items-center justify-between gap-2 p-3 sm:p-5"><div className="flex items-center gap-2"><Link href="/herramientas/metalcon" className="grid h-10 w-10 place-items-center rounded-full border border-white/12 bg-black/58 backdrop-blur-xl"><ChevronLeft size={17}/></Link><div className="rounded-2xl border border-white/10 bg-black/58 px-3 py-2 backdrop-blur-xl"><p className="text-[8px] font-black uppercase tracking-[.15em] text-[#F6C64A]">Comparador sísmico 4D</p><b className="mt-1 block text-[10px]">Metalcon ↔ madera · mismo escenario</b></div></div><button aria-label="Abrir menú" onClick={()=>setDrawer(v=>v?null:'controls')} className={`grid h-10 w-10 place-items-center rounded-full border backdrop-blur-xl ${drawer?'border-[#F6C64A]/50 bg-[#F6C64A] text-black':'border-white/10 bg-black/58 text-white/70'}`}><Menu size={16}/></button></header>
  <div className="absolute left-3 top-[82px] z-20 rounded-xl border border-white/10 bg-black/58 px-3 py-2 backdrop-blur-xl"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${playing?'animate-pulse bg-[#F6C64A]':progress>=1?'bg-emerald-400':'bg-white/35'}`}/><b className="text-[8px] uppercase tracking-[.1em]">{phase(progress)}</b></div><p className="mt-1 text-[7px] text-white/45">Mw {config.magnitude.toFixed(1)} · MMI {result.scenario.mmi.toFixed(1)} · PGA proxy {result.scenario.pga}g</p></div>
  <div className="absolute left-3 right-3 top-[132px] z-10 grid grid-cols-2 gap-2 sm:left-5 sm:right-auto sm:w-[500px]"><SystemCard result={result.metal}/><SystemCard result={result.wood}/></div>
  {drawer?<aside className="absolute inset-x-3 bottom-[92px] z-30 max-h-[68dvh] overflow-y-auto rounded-[1.4rem] border border-white/12 bg-[#071016]/95 p-4 shadow-2xl backdrop-blur-2xl sm:inset-x-auto sm:right-5 sm:top-[82px] sm:bottom-auto sm:w-[430px] sm:max-h-[calc(100dvh-110px)]"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.16em] text-[#F6C64A]">Laboratorio sísmico</p><h2 className="mt-1 text-base font-black">{drawer==='controls'?'Configura el sismo':drawer==='layers'?'Capas visibles':'Daño y reparación'}</h2></div><button onClick={()=>setDrawer(null)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.06]"><X size={15}/></button></div><div className="mt-3 grid grid-cols-3 gap-1"><Tab active={drawer==='controls'} label="Escenario" onClick={()=>setDrawer('controls')}/><Tab active={drawer==='layers'} label="Capas" onClick={()=>setDrawer('layers')}/><Tab active={drawer==='comparison'} label="Analítica" onClick={()=>setDrawer('comparison')}/></div>{drawer==='controls'?<Controls config={config} setConfig={setConfig} modelId={modelId} setModelId={setModelId} showDamage={showDamage} setShowDamage={setShowDamage}/>:drawer==='layers'?<LayerControls showRoof={showRoof} setShowRoof={setShowRoof} showPanels={showPanels} setShowPanels={setShowPanels} showCeiling={showCeiling} setShowCeiling={setShowCeiling} showSanitary={showSanitary} setShowSanitary={setShowSanitary}/>:<Comparison metal={result.metal} wood={result.wood} rows={damageRows}/>}</aside>:null}
  <div className="absolute bottom-3 left-1/2 z-20 w-[min(720px,calc(100%-24px))] -translate-x-1/2 rounded-2xl border border-white/10 bg-black/68 p-3 backdrop-blur-xl"><div className="flex items-center gap-2"><button aria-label={playing?'Pausar simulación':'Iniciar simulación'} onClick={playing?()=>setPlaying(false):play} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#F6C64A] text-black">{playing?<Pause size={16}/>:<Play size={16}/>}</button><div className="min-w-0 flex-1"><div className="mb-1 flex justify-between text-[7px] font-black uppercase text-white/45"><span>{phase(progress)}</span><span>{Math.round(progress*100)}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#F6C64A]" style={{width:`${progress*100}%`}}/></div></div><button aria-label="Reiniciar simulación" onClick={reset} className="grid h-10 w-10 place-items-center rounded-full bg-white/[.07]"><RotateCcw size={15}/></button></div></div>
 </section>
}
function SystemLabel({title,detail}:{title:string;detail:string}){return <div className="rounded-full border border-cyan-200/25 bg-black/80 px-3 py-1.5 text-center"><b className="text-[8px] uppercase text-cyan-100">{title}</b><small className="ml-2 text-[7px] text-white/45">{detail}</small></div>}
function SystemCard({result}:{result:SystemResult}){const c=result.damage==='Crítico'?'text-red-200':result.damage==='Alto'?'text-orange-200':result.damage==='Moderado'?'text-yellow-100':'text-emerald-200';return <div className="rounded-xl border border-white/10 bg-black/58 p-2.5 backdrop-blur-xl"><div className="flex justify-between gap-2"><b className="text-[9px]">{result.name}</b><span className={`text-[8px] font-black ${c}`}>{result.damage}</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#F6C64A]" style={{width:`${Math.round(result.response*100)}%`}}/></div><p className="mt-1 text-[7px] text-white/38">respuesta visual {Math.round(result.response*100)}% · deriva proxy {result.drift}%</p></div>}
function Tab({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}){return <button onClick={onClick} className={`rounded-xl py-2 text-[8px] font-black ${active?'bg-[#F6C64A] text-black':'bg-white/[.05] text-white/50'}`}>{label}</button>}
function Controls({config,setConfig,modelId,setModelId,showDamage,setShowDamage}:{config:SeismicConfig;setConfig:(u:(v:SeismicConfig)=>SeismicConfig)=>void;modelId:MetalconHousePresetId;setModelId:(v:MetalconHousePresetId)=>void;showDamage:boolean;setShowDamage:(v:boolean)=>void}){return <div className="mt-4 space-y-3"><label className="block"><span className="text-[8px] uppercase text-white/38">Vivienda</span><select value={modelId} onChange={e=>setModelId(e.target.value as MetalconHousePresetId)} className="mt-1 h-10 w-full rounded-xl bg-[#11181d] px-3 text-[10px] font-bold">{METALCON_HOUSE_PRESET_ORDER.map(id=><option key={id} value={id}>{METALCON_HOUSE_PRESETS[id].label}</option>)}</select></label><Range label="Magnitud" value={`Mw ${config.magnitude.toFixed(1)}`} n={config.magnitude} min={4} max={9.5} step={.1} onChange={magnitude=>setConfig(v=>({...v,magnitude}))}/><Range label="Profundidad" value={`${config.depthKm} km`} n={config.depthKm} min={5} max={120} step={1} onChange={depthKm=>setConfig(v=>({...v,depthKm}))}/><Range label="Distancia" value={`${config.distanceKm} km`} n={config.distanceKm} min={0} max={250} step={5} onChange={distanceKm=>setConfig(v=>({...v,distanceKm}))}/><Range label="Duración" value={`${config.duration} s`} n={config.duration} min={5} max={60} step={1} onChange={duration=>setConfig(v=>({...v,duration}))}/><Range label="Dirección" value={`${config.directionDeg}°`} n={config.directionDeg} min={0} max={350} step={10} onChange={directionDeg=>setConfig(v=>({...v,directionDeg}))}/><label className="block"><span className="text-[8px] uppercase text-white/38">Suelo</span><select value={config.soil} onChange={e=>setConfig(v=>({...v,soil:e.target.value as SeismicSoil}))} className="mt-1 h-10 w-full rounded-xl bg-[#11181d] px-3 text-[10px] font-bold">{Object.entries(SEISMIC_SOILS).map(([k,s])=><option key={k} value={k}>{s.label}</option>)}</select></label><button onClick={()=>setShowDamage(!showDamage)} className={`w-full rounded-xl px-3 py-3 text-[9px] font-black ${showDamage?'bg-[#F6C64A] text-black':'bg-white/[.06] text-white/60'}`}>Mapa de afectación {showDamage?'ON':'OFF'}</button><p className="rounded-xl border border-amber-300/15 bg-amber-300/[.04] p-3 text-[8px] leading-4 text-white/45">Comparación educativa. Rojo indica piezas visualmente afectadas dentro del escenario proxy; no representa una verificación normativa ni predice colapso real.</p></div>}
function LayerControls({showRoof,setShowRoof,showPanels,setShowPanels,showCeiling,setShowCeiling,showSanitary,setShowSanitary}:{showRoof:boolean;setShowRoof:(v:boolean)=>void;showPanels:boolean;setShowPanels:(v:boolean)=>void;showCeiling:boolean;setShowCeiling:(v:boolean)=>void;showSanitary:boolean;setShowSanitary:(v:boolean)=>void}){return <div className="mt-4 space-y-2"><LayerToggle label="Techumbre / cubierta" detail="Oculta la cubierta para inspeccionar cerchas y cabios." active={showRoof} onClick={()=>setShowRoof(!showRoof)}/><LayerToggle label="Planchas y envolvente" detail="OSB, aislación y revestimientos semitransparentes." active={showPanels} onClick={()=>setShowPanels(!showPanels)}/><LayerToggle label="Cielo interior Metalcon" detail="Permite retirar el cielo y mirar la estructura superior." active={showCeiling} onClick={()=>setShowCeiling(!showCeiling)}/><LayerToggle label="Sanitaria + fosa" detail="Bajadas, colector, cámara, desgrasadora, fosa y drenaje esquemático." active={showSanitary} onClick={()=>setShowSanitary(!showSanitary)}/><p className="rounded-xl border border-white/8 bg-white/[.025] p-3 text-[8px] leading-4 text-white/40">La vista de capas es didáctica: espesores, fijaciones, pendientes y dimensionamientos definitivos corresponden al proyecto estructural, térmico y sanitario.</p></div>}
function LayerToggle({label,detail,active,onClick}:{label:string;detail:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`w-full rounded-xl border p-3 text-left ${active?'border-[#F6C64A]/30 bg-[#F6C64A]/[.07]':'border-white/8 bg-white/[.025]'}`}><span className="flex items-center justify-between gap-3"><b className="text-[9px]">{label}</b><span className={`rounded-full px-2 py-1 text-[7px] font-black ${active?'bg-[#F6C64A] text-black':'bg-white/10 text-white/40'}`}>{active?'ON':'OFF'}</span></span><small className="mt-1 block text-[7px] leading-3 text-white/35">{detail}</small></button>}
function Comparison({metal,wood,rows}:{metal:SystemResult;wood:SystemResult;rows:DamageRow[]}){return <div className="mt-4 space-y-3"><div className="overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[.8fr_.55fr_.55fr] bg-white/[.06] px-3 py-2 text-[7px] font-black uppercase text-white/45"><span>Sistema</span><span>Daño proxy</span><span>Deriva</span></div>{[metal,wood].map(r=><div key={r.name} className="grid grid-cols-[.8fr_.55fr_.55fr] gap-1 border-t border-white/8 px-3 py-3 text-[9px]"><b>{r.name}</b><span>{r.damage}</span><b className="text-[#F6C64A]">{r.drift}%</b><p className="col-span-3 mt-1 text-[8px] text-white/42"><b className="text-white/65">Revisar:</b> {r.criticalZones}. {r.inspection}</p></div>)}</div><div className="overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[.72fr_1fr_.42fr] bg-white/[.06] px-2 py-2 text-[7px] font-black uppercase text-white/42"><span>Sistema</span><span>Elemento</span><span>Daño</span></div>{rows.map((r,i)=><div key={`${r.system}-${r.element}`} className={`grid grid-cols-[.72fr_1fr_.42fr] gap-1 border-t border-white/8 px-2 py-2 ${i%2?'bg-white/[.02]':''}`}><b className="text-[8px]">{r.system}</b><span className="text-[8px] text-white/62">{r.element}</span><b className={`text-right text-[8px] ${r.percent>=65?'text-red-300':r.percent>=40?'text-amber-200':'text-emerald-200'}`}>{r.percent}%</b><p className="col-span-3 text-[7px] leading-3 text-white/35"><b className="text-white/55">Modo:</b> {r.mode} · <b className="text-white/55">Acción:</b> {r.action}</p></div>)}</div><p className="text-[8px] leading-4 text-white/38">Los porcentajes son proxies visuales del escenario, no capacidad resistente, deriva normativa ni predicción de colapso. La inspección y reparación real requiere profesional competente.</p></div>}
function buildDamageRows(metal:SystemResult,wood:SystemResult,progress:number):DamageRow[]{const gate=clamp((progress-.52)/.4);const pct=(r:SystemResult,f:number)=>Math.round(clamp(r.response*f*gate)*100);return[{system:'Metalcon',element:'Montantes / soleras',percent:pct(metal,1.06),mode:'pandeo o deformación localizada',action:'revisar continuidad C/U y reemplazar perfil deformado'},{system:'Metalcon',element:'Anclajes y vanos',percent:pct(metal,1.12),mode:'concentración en uniones',action:'revisar fijaciones, jambas y dinteles'},{system:'Metalcon',element:'Placas / revestimiento',percent:pct(metal,.82),mode:'fisuras o desprendimiento',action:'revisar tornillos y reponer placa dañada'},{system:'Metalcon',element:'Techumbre',percent:pct(metal,.76),mode:'desalineación de uniones',action:'inspeccionar cerchas, correas y anclajes'},{system:'Madera',element:'Montantes',percent:pct(wood,1.05),mode:'fisura, separación o rotura',action:'revisar fibras, uniones y reemplazar pieza rota'},{system:'Madera',element:'OSB / placas',percent:pct(wood,.94),mode:'desclavado o corte de borde',action:'revisar fijaciones y continuidad de placa'},{system:'Madera',element:'Uniones / anclajes',percent:pct(wood,1.14),mode:'holgura o arrancamiento',action:'revisar conectores y fijaciones'},{system:'Madera',element:'Cerchas / cubierta',percent:pct(wood,1.02),mode:'fisura, desplazamiento o pérdida de apoyo',action:'inspeccionar rafters, cumbrera y apoyos'}]}
function Range({label,value,n,min,max,step,onChange}:{label:string;value:string;n:number;min:number;max:number;step:number;onChange:(v:number)=>void}){return <label className="block"><span className="flex justify-between text-[8px] uppercase text-white/38"><b>{label}</b><b className="text-[#F6C64A]">{value}</b></span><input type="range" value={n} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full accent-[#F6C64A]"/></label>}
