'use client';
import { Html } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
import type { Group } from 'three';
import type { MetalconHousePreset } from '@/lib/metalconAssembly';

const clamp=(v:number)=>Math.min(1,Math.max(0,v));
export default function WoodFrameSeismicModel({preset,active,progress,response,frequencyHz,directionDeg,showDamage=true}:{preset:MetalconHousePreset;active:boolean;progress:number;response:number;frequencyHz:number;directionDeg:number;showDamage?:boolean}){
 const ref=useRef<Group>(null),scale=Math.min(1,8.4/Math.max(preset.widthM,preset.depthM+(preset.terraceDepthM??0))),studsX=useMemo(()=>Array.from({length:Math.ceil(preset.widthM/.4)+1},(_,i)=>-preset.widthM/2+i*preset.widthM/Math.ceil(preset.widthM/.4)),[preset.widthM]),studsZ=useMemo(()=>Array.from({length:Math.ceil(preset.depthM/.4)+1},(_,i)=>-preset.depthM/2+i*preset.depthM/Math.ceil(preset.depthM/.4)),[preset.depthM]);
 useFrame(({clock},delta)=>{if(!ref.current)return;const envelope=active?clamp((progress-.42)/.16)*clamp((.94-progress)/.12):0,dir=directionDeg*Math.PI/180,wave=Math.sin(clock.elapsedTime*Math.max(.8,frequencyHz)*Math.PI*2)*response*.22*envelope,lerp=Math.min(1,delta*14),damage=showDamage&&progress>.7?response*.045:0;ref.current.position.x+=(Math.cos(dir)*wave-ref.current.position.x)*lerp;ref.current.position.z+=(Math.sin(dir)*wave-ref.current.position.z)*lerp;ref.current.rotation.z+=(Math.cos(dir)*wave*.075+damage-ref.current.rotation.z)*lerp;ref.current.rotation.x+=(-Math.sin(dir)*wave*.075-ref.current.rotation.x)*lerp});
 const damage=Math.max(0,response-.34),boardColor=damage>.42?'#a94d3c':damage>.22?'#c88b55':'#d2b184',panelOpacity=showDamage&&progress>.65?.72:.46;
 return <group scale={scale}><group ref={ref}><mesh position={[0,-.045,0]} receiveShadow><boxGeometry args={[preset.widthM+.18,.09,preset.depthM+.18]}/><meshStandardMaterial color="#61666a" roughness={.9}/></mesh><group>
  {studsX.flatMap(x=>[<WoodMember key={`n${x}`} pos={[x,preset.heightM/2,-preset.depthM/2]} size={[.045,preset.heightM,.09]}/>,<WoodMember key={`s${x}`} pos={[x,preset.heightM/2,preset.depthM/2]} size={[.045,preset.heightM,.09]}/>])}
  {studsZ.flatMap(z=>[<WoodMember key={`w${z}`} pos={[-preset.widthM/2,preset.heightM/2,z]} size={[.09,preset.heightM,.045]}/>,<WoodMember key={`e${z}`} pos={[preset.widthM/2,preset.heightM/2,z]} size={[.09,preset.heightM,.045]}/>])}
  <WoodMember pos={[0,.05,-preset.depthM/2]} size={[preset.widthM,.08,.09]}/><WoodMember pos={[0,preset.heightM-.05,-preset.depthM/2]} size={[preset.widthM,.08,.09]}/><WoodMember pos={[0,.05,preset.depthM/2]} size={[preset.widthM,.08,.09]}/><WoodMember pos={[0,preset.heightM-.05,preset.depthM/2]} size={[preset.widthM,.08,.09]}/>
  <mesh position={[0,preset.heightM/2,-preset.depthM/2-.055]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,.025]}/><meshStandardMaterial color={boardColor} roughness={.75} transparent opacity={panelOpacity}/></mesh>
  <mesh position={[0,preset.heightM/2,preset.depthM/2+.055]} castShadow><boxGeometry args={[preset.widthM,preset.heightM,.025]}/><meshStandardMaterial color={boardColor} roughness={.75} transparent opacity={panelOpacity}/></mesh>
  <mesh position={[-preset.widthM/2-.055,preset.heightM/2,0]} castShadow><boxGeometry args={[.025,preset.heightM,preset.depthM]}/><meshStandardMaterial color={boardColor} roughness={.75} transparent opacity={.5}/></mesh><mesh position={[preset.widthM/2+.055,preset.heightM/2,0]} castShadow><boxGeometry args={[.025,preset.heightM,preset.depthM]}/><meshStandardMaterial color={boardColor} roughness={.75} transparent opacity={.5}/></mesh>
  <WoodRoof preset={preset} response={response} progress={progress}/>
 </group></group><Html center distanceFactor={11} position={[0,preset.heightM+1.2,0]}><div className="rounded-full border border-amber-200/30 bg-black/80 px-3 py-1.5 text-[8px] font-black uppercase tracking-[.12em] text-amber-100">Madera · entramado visual</div></Html></group>
}
function WoodMember({pos,size}:{pos:[number,number,number];size:[number,number,number]}){return <mesh position={pos} castShadow><boxGeometry args={size}/><meshStandardMaterial color="#bc8651" roughness={.72}/></mesh>}
function WoodRoof({preset,response,progress}:{preset:MetalconHousePreset;response:number;progress:number}){const rise=Math.max(.65,preset.widthM*.15),half=preset.depthM/2+.3,slope=Math.sqrt(half*half+rise*rise),angle=Math.atan2(rise,half),shift=progress>.74?Math.max(0,response-.52)*.22:0;return <group position={[shift,preset.heightM+rise/2,0]} rotation={[0,0,shift*.12]}><mesh position={[0,0,-preset.depthM/4]} rotation={[angle,0,0]}><boxGeometry args={[preset.widthM+.5,.07,slope]}/><meshStandardMaterial color="#71543b" roughness={.8}/></mesh><mesh position={[0,0,preset.depthM/4]} rotation={[-angle,0,0]}><boxGeometry args={[preset.widthM+.5,.07,slope]}/><meshStandardMaterial color="#71543b" roughness={.8}/></mesh></group>}
