'use client';
import { Html } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
import { Quaternion, Vector3 } from 'three';
import type { Group } from 'three';
import type { MetalconHousePreset } from '@/lib/metalconAssembly';

const clamp=(v:number)=>Math.min(1,Math.max(0,v));
type Props={preset:MetalconHousePreset;active:boolean;progress:number;response:number;frequencyHz:number;directionDeg:number;showDamage?:boolean;showRoof?:boolean;showPanels?:boolean;showLabels?:boolean};
export default function WoodFrameSeismicModelV2({preset,active,progress,response,frequencyHz,directionDeg,showDamage=true,showRoof=true,showPanels=true,showLabels=true}:Props){
 const ref=useRef<Group>(null),scale=Math.min(1,8.4/Math.max(preset.widthM,preset.depthM+(preset.terraceDepthM??0))),studsX=useMemo(()=>Array.from({length:Math.ceil(preset.widthM/.4)+1},(_,i)=>-preset.widthM/2+i*preset.widthM/Math.ceil(preset.widthM/.4)),[preset.widthM]),studsZ=useMemo(()=>Array.from({length:Math.ceil(preset.depthM/.4)+1},(_,i)=>-preset.depthM/2+i*preset.depthM/Math.ceil(preset.depthM/.4)),[preset.depthM]);
 const damageGate=showDamage?clamp((progress-.6)/.28):0,damage=clamp(response*damageGate);
 useFrame(({clock},delta)=>{if(!ref.current)return;const envelope=active?clamp((progress-.42)/.16)*clamp((.94-progress)/.12):0,dir=directionDeg*Math.PI/180,wave=Math.sin(clock.elapsedTime*Math.max(.8,frequencyHz)*Math.PI*2)*response*.22*envelope,lerp=Math.min(1,delta*14),permanent=damage>.62?(damage-.62)*.055:0;ref.current.position.x+=(Math.cos(dir)*wave-ref.current.position.x)*lerp;ref.current.position.z+=(Math.sin(dir)*wave-ref.current.position.z)*lerp;ref.current.rotation.z+=(Math.cos(dir)*wave*.075+permanent-ref.current.rotation.z)*lerp;ref.current.rotation.x+=(-Math.sin(dir)*wave*.075-ref.current.rotation.x)*lerp});
 return <group scale={scale}><group ref={ref}><mesh position={[0,-.045,0]} receiveShadow><boxGeometry args={[preset.widthM+.18,.09,preset.depthM+.18]}/><meshStandardMaterial color="#61666a" roughness={.9}/></mesh><group>
  {studsX.flatMap((x,i)=>[<WoodMember key={`n${x}`} pos={[x,preset.heightM/2,-preset.depthM/2]} size={[.045,preset.heightM,.09]} damage={damage*(.82+(i%4)*.06)} seed={i}/>,<WoodMember key={`s${x}`} pos={[x,preset.heightM/2,preset.depthM/2]} size={[.045,preset.heightM,.09]} damage={damage*(.86+((i+2)%4)*.05)} seed={i+31}/>])}
  {studsZ.flatMap((z,i)=>[<WoodMember key={`w${z}`} pos={[-preset.widthM/2,preset.heightM/2,z]} size={[.09,preset.heightM,.045]} damage={damage*(.84+(i%3)*.07)} seed={i+61}/>,<WoodMember key={`e${z}`} pos={[preset.widthM/2,preset.heightM/2,z]} size={[.09,preset.heightM,.045]} damage={damage*(.9+((i+1)%3)*.05)} seed={i+91}/>])}
  <WoodMember pos={[0,.05,-preset.depthM/2]} size={[preset.widthM,.08,.09]} damage={damage*.75} seed={121}/><WoodMember pos={[0,preset.heightM-.05,-preset.depthM/2]} size={[preset.widthM,.08,.09]} damage={damage*.9} seed={122}/><WoodMember pos={[0,.05,preset.depthM/2]} size={[preset.widthM,.08,.09]} damage={damage*.78} seed={123}/><WoodMember pos={[0,preset.heightM-.05,preset.depthM/2]} size={[preset.widthM,.08,.09]} damage={damage*.93} seed={124}/>
  {showPanels?<WoodWallLayers preset={preset} damage={damage}/>:null}
  {showRoof?<WoodRoof preset={preset} damage={damage} showCover={showPanels}/>:null}
 </group></group>{showLabels?<Html center distanceFactor={11} position={[0,preset.heightM+1.55,0]}><div className="rounded-full border border-amber-200/30 bg-black/80 px-3 py-1.5 text-[8px] font-black uppercase tracking-[.12em] text-amber-100">Madera · marco plataforma visual</div></Html>:null}</group>
}
function WoodMember({pos,size,damage=0,seed=0}:{pos:[number,number,number];size:[number,number,number];damage?:number;seed?:number}){const stressed=damage>.36&&(seed%3===0||damage>.78),broken=damage>.72&&size[1]>.7&&seed%5===0,color=stressed?'#ff3b30':'#bc8651',tilt=stressed?(seed%2?1:-1)*damage*.045:0;if(broken){const h=size[1]*.46;return <group position={pos}><mesh position={[0,-size[1]*.26,0]} rotation={[0,0,tilt-.055]} castShadow><boxGeometry args={[size[0],h,size[2]]}/><meshStandardMaterial color="#ff332f" roughness={.68}/></mesh><mesh position={[.035,size[1]*.26,0]} rotation={[0,0,tilt+.065]} castShadow><boxGeometry args={[size[0],h,size[2]]}/><meshStandardMaterial color="#ff332f" roughness={.68}/></mesh><mesh position={[.018,0,0]}><sphereGeometry args={[.045,10,8]}/><meshStandardMaterial color="#ff1100" emissive="#ff1100" emissiveIntensity={1.7}/></mesh></group>}return <mesh position={pos} rotation={[0,0,tilt]} castShadow><boxGeometry args={size}/><meshStandardMaterial color={color} roughness={.72} emissive={stressed?'#6b0905':'#000000'} emissiveIntensity={stressed?.45:0}/></mesh>}
function WoodWallLayers({preset,damage}:{preset:MetalconHousePreset;damage:number}){const panelColor=damage>.7?'#ff4438':'#b9824c',opacity=.28;return <group><mesh position={[0,preset.heightM/2,-preset.depthM/2-.06]}><boxGeometry args={[preset.widthM,preset.heightM,.035]}/><meshStandardMaterial color={panelColor} transparent opacity={opacity} roughness={.82}/></mesh><mesh position={[-preset.widthM/2-.06,preset.heightM/2,0]}><boxGeometry args={[.035,preset.heightM,preset.depthM]}/><meshStandardMaterial color={panelColor} transparent opacity={opacity*.9} roughness={.82}/></mesh><mesh position={[preset.widthM/2+.06,preset.heightM/2,0]}><boxGeometry args={[.035,preset.heightM,preset.depthM]}/><meshStandardMaterial color={panelColor} transparent opacity={opacity*.9} roughness={.82}/></mesh></group>}
function WoodRoof({preset,damage,showCover}:{preset:MetalconHousePreset;damage:number;showCover:boolean}){const run=preset.depthM/2+.42,rise=Math.max(.7,run*.3),eaveY=preset.heightM+.08,ridgeY=eaveY+rise,panelWidth=preset.widthM+.8,trussCount=Math.max(2,Math.ceil(preset.widthM/.6)),xs=Array.from({length:trussCount+1},(_,i)=>-preset.widthM/2+i*preset.widthM/trussCount),slope=Math.sqrt(run*run+rise*rise),angle=Math.atan2(rise,run),midY=eaveY+rise/2,purlinFractions=[.76,.5,.24],coverColor=damage>.76?'#d92f2a':'#704a34';return <group>{xs.map((x,i)=>{const stressed=damage>.48&&(i%4===1||damage>.82),broken=damage>.76&&i%5===2;return <group key={x}><WoodBeam from={[x,eaveY,-run]} to={[x,ridgeY,0]} damage={stressed?damage:0} broken={broken}/><WoodBeam from={[x,eaveY,run]} to={[x,ridgeY,0]} damage={stressed?damage*.95:0} broken={broken&&damage>.86}/><WoodBeam from={[x,eaveY,-run]} to={[x,eaveY,run]} damage={stressed?damage*.7:0}/><WoodBeam from={[x,eaveY,0]} to={[x,ridgeY,0]} damage={stressed?damage*.8:0}/><WoodBeam from={[x,eaveY,-run*.52]} to={[x,ridgeY-.08,0]} damage={stressed?damage*.8:0}/><WoodBeam from={[x,eaveY,run*.52]} to={[x,ridgeY-.08,0]} damage={stressed?damage*.8:0}/></group>})}<mesh position={[0,ridgeY,0]}><boxGeometry args={[panelWidth,.09,.09]}/><meshStandardMaterial color={damage>.7?'#ff3b30':'#9d6f42'} roughness={.72}/></mesh>{purlinFractions.flatMap(f=>{const y=eaveY+rise*(1-f);return [<mesh key={`p-${f}`} position={[0,y,-run*f]}><boxGeometry args={[panelWidth,.055,.075]}/><meshStandardMaterial color="#9d6f42" roughness={.74}/></mesh>,<mesh key={`q-${f}`} position={[0,y,run*f]}><boxGeometry args={[panelWidth,.055,.075]}/><meshStandardMaterial color="#9d6f42" roughness={.74}/></mesh>]})}{showCover?<><mesh position={[0,midY+.07,-run/2]} rotation={[-angle,0,0]} castShadow><boxGeometry args={[panelWidth,.045,slope]}/><meshStandardMaterial color={coverColor} roughness={.84} transparent opacity={.72}/></mesh><mesh position={[0,midY+.07,run/2]} rotation={[angle,0,0]} castShadow><boxGeometry args={[panelWidth,.045,slope]}/><meshStandardMaterial color={coverColor} roughness={.84} transparent opacity={.72}/></mesh><mesh position={[0,ridgeY+.06,0]}><boxGeometry args={[panelWidth+.04,.07,.16]}/><meshStandardMaterial color={damage>.76?'#ff302a':'#5e3d2b'} roughness={.8}/></mesh></>:null}<mesh position={[0,eaveY-.02,-run]}><boxGeometry args={[panelWidth,.18,.055]}/><meshStandardMaterial color="#8d603c" roughness={.75}/></mesh><mesh position={[0,eaveY-.02,run]}><boxGeometry args={[panelWidth,.18,.055]}/><meshStandardMaterial color="#8d603c" roughness={.75}/></mesh><Html center distanceFactor={10} position={[0,ridgeY+.42,0]}><span className="whitespace-nowrap rounded-full border border-white/10 bg-black/82 px-2 py-1 text-[7px] font-black uppercase text-white/80">Cercha madera · cumbrera · rafters · correas</span></Html></group>}
function WoodBeam({from,to,damage=0,broken=false}:{from:[number,number,number];to:[number,number,number];damage?:number;broken?:boolean}){const a=new Vector3(...from),b=new Vector3(...to),mid=a.clone().lerp(b,.5);if(broken){const gap=new Vector3(.035,-.055,.018);return <><BeamSegment from={a} to={mid.clone().add(gap)} color="#ff342f"/><BeamSegment from={mid.clone().sub(gap)} to={b} color="#ff342f"/></>}return <BeamSegment from={a} to={b} color={damage>.42?'#ff3b30':'#a87545'}/>}
function BeamSegment({from,to,color}:{from:Vector3;to:Vector3;color:string}){const dir=to.clone().sub(from),len=dir.length(),mid=from.clone().add(to).multiplyScalar(.5),q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),dir.clone().normalize());return <mesh position={mid} quaternion={q} castShadow><boxGeometry args={[.055,len,.075]}/><meshStandardMaterial color={color} roughness={.7} emissive={color==='#ff3b30'||color==='#ff342f'?'#690704':'#000'} emissiveIntensity={color.startsWith('#ff3')?.4:0}/></mesh>}
