'use client';

import { type FormEvent, useMemo, useState } from 'react';
import { AirVent, ArrowRight, Check, ChevronDown, CircleCheck, ClipboardList, Fence, Hammer, Home, HousePlug, Info, Layers3, PackageCheck, PaintRoller, Ruler, Send, ShieldCheck, Sparkles, TentTree, type LucideIcon } from 'lucide-react';

type Unit = 'm2' | 'ml' | 'unidad' | 'punto';
type Group = 'Kits y casas' | 'Instalaciones' | 'Exterior y perímetro';
type Service = { id: string; name: string; short: string; group: Group; unit: Unit; low: number; high: number; defaultQuantity: number; icon: LucideIcon; summary: string; includes: string[]; note: string };

const SERVICES: Service[] = [
  { id: 'kit-basico', name: 'Kit prefabricado básico', short: 'Kit básico', group: 'Kits y casas', unit: 'm2', low: 160000, high: 230000, defaultQuantity: 36, icon: PackageCheck, summary: 'La base para construir y avanzar por etapas.', includes: ['Paneles interiores y exteriores forrados por una cara', 'Cerchas en madera o Metalcon según definición', 'Zinc 0,35 mm, costaneras y estructura principal'], note: 'No incluye fundaciones, montaje, traslado, ventanas, puertas ni instalaciones.' },
  { id: 'kit-avanzado', name: 'Kit prefabricado avanzado', short: 'Kit avanzado', group: 'Kits y casas', unit: 'm2', low: 320000, high: 460000, defaultQuantity: 54, icon: Layers3, summary: 'Una base más completa para reducir trabajos posteriores.', includes: ['Todo lo incluido en el kit básico', 'Ventanas estándar y puertas interiores', 'Forro interior, puerta principal y salida de emergencia', 'Puntos eléctricos básicos y cielos considerados'], note: 'No incluye fundaciones, fosa, conexiones exteriores, pisos ni pintura.' },
  { id: 'llave-en-mano', name: 'Casa llave en mano estándar', short: 'Llave en mano', group: 'Kits y casas', unit: 'm2', low: 540000, high: 780000, defaultQuantity: 72, icon: Home, summary: 'Vivienda terminada con estándar acordado y redes interiores listas.', includes: ['Todo lo incluido en el kit avanzado', 'Cerámica o porcelanato de marca acordada', 'Dos capas de pintura', 'Conexión sanitaria y agua potable listas para conectar'], note: 'No incluye fosa séptica, pozo de agua, empalmes exteriores, permisos ni obras de terreno.' },
  { id: 'montaje-kit', name: 'Instalación de kit prefabricado', short: 'Montaje de kit', group: 'Instalaciones', unit: 'm2', low: 45000, high: 75000, defaultQuantity: 36, icon: Hammer, summary: 'Montaje técnico de estructura y componentes definidos del kit.', includes: ['Revisión previa del kit y área de montaje', 'Armado de estructura según alcance', 'Fijaciones y orden de trabajo base'], note: 'Altura, acceso, fundación disponible y modelo cambian el valor final.' },
  { id: 'fosa-septica', name: 'Instalación de fosa séptica', short: 'Fosa séptica', group: 'Instalaciones', unit: 'unidad', low: 900000, high: 1800000, defaultQuantity: 1, icon: ShieldCheck, summary: 'Solución sanitaria exterior según terreno y capacidad.', includes: ['Revisión técnica inicial', 'Excavación y nivelación según alcance', 'Instalación y conexión definida en cotización'], note: 'Capacidad, terreno, distancia, permisos y disposición final se confirman antes de iniciar.' },
  { id: 'siding', name: 'Instalación de revestimiento siding', short: 'Revestimiento siding', group: 'Instalaciones', unit: 'm2', low: 35000, high: 65000, defaultQuantity: 30, icon: PaintRoller, summary: 'Fachada renovada, protegida y con una terminación clara.', includes: ['Revisión de superficie existente', 'Fijación e instalación de siding', 'Remates estándar definidos en el alcance'], note: 'Aislación, humedad, retiro previo, altura y reparaciones se revisan en terreno.' },
  { id: 'techumbre', name: 'Instalación o renovación de techumbre', short: 'Techumbre', group: 'Instalaciones', unit: 'm2', low: 55000, high: 95000, defaultQuantity: 45, icon: HousePlug, summary: 'Cubierta y protección para el área que necesitas intervenir.', includes: ['Evaluación de estructura existente', 'Cubierta y fijaciones según propuesta', 'Remates básicos del área intervenida'], note: 'Canaletas, aislación, reparación estructural, altura y acceso se revisan aparte.' },
  { id: 'aire', name: 'Instalación de aire acondicionado', short: 'Aire acondicionado', group: 'Instalaciones', unit: 'unidad', low: 130000, high: 240000, defaultQuantity: 1, icon: AirVent, summary: 'Instalación profesional para un equipo split con recorrido estándar.', includes: ['Montaje de unidad interior y exterior', 'Tubería y cableado en recorrido estándar', 'Prueba básica de funcionamiento'], note: 'Equipo, metros extra, altura, canaleta y obras eléctricas se validan en visita.' },
  { id: 'electricidad', name: 'Instalación eléctrica domiciliaria', short: 'Electricidad domiciliaria', group: 'Instalaciones', unit: 'punto', low: 35000, high: 85000, defaultQuantity: 8, icon: HousePlug, summary: 'Puntos eléctricos para habilitar y ordenar tus espacios.', includes: ['Puntos considerados en propuesta', 'Canalización y accesorios estándar', 'Pruebas básicas de operación'], note: 'Tablero, aumento de carga, distancias, muros y certificaciones se revisan aparte.' },
  { id: 'cierre', name: 'Cierre perimetral', short: 'Cierre perimetral', group: 'Exterior y perímetro', unit: 'ml', low: 45000, high: 90000, defaultQuantity: 20, icon: Fence, summary: 'Delimitación y protección según el trazado de tu terreno.', includes: ['Trazado del tramo a intervenir', 'Postes y estructura según propuesta', 'Instalación del cierre definido'], note: 'Portones, desniveles, tipo de suelo y material final se confirman al evaluar el lugar.' },
];

const GROUPS: Group[] = ['Kits y casas', 'Instalaciones', 'Exterior y perímetro'];
const PRESETS = [{ label: 'Cabaña', value: 15, icon: TentTree }, { label: 'Compacta', value: 36, icon: Home }, { label: 'Familiar', value: 54, icon: Home }, { label: 'Ampliada', value: 72, icon: Home }];
const money = (value: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(Math.round(value || 0));
const unitLabel = (unit: Unit) => ({ m2: 'm²', ml: 'metro lineal', unidad: 'unidad', punto: 'punto' }[unit]);
const quantityLabel = (unit: Unit) => unit === 'm2' ? 'Superficie a intervenir' : unit === 'ml' ? 'Metros lineales' : unit === 'punto' ? 'Cantidad de puntos' : 'Cantidad de unidades';

export default function ConstructionM2Calculator() {
  const [serviceId, setServiceId] = useState('kit-basico');
  const [showServices, setShowServices] = useState(false);
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [quantity, setQuantity] = useState(36);
  const [customer, setCustomer] = useState({ name: '', phone: '', place: '', detail: '' });
  const [sent, setSent] = useState(false);
  const service = SERVICES.find((item) => item.id === serviceId) ?? SERVICES[0];
  const Icon = service.icon;
  const cleanQuantity = Math.max(service.unit === 'unidad' ? 1 : 0, Math.min(5000, Number(quantity) || 0));
  const low = cleanQuantity * service.low;
  const high = cleanQuantity * service.high;
  const average = (low + high) / 2;
  const message = useMemo(() => [
    'Hola Soluciones Fabrick, quiero una cotización real.', '', `Servicio: ${service.name}`, `${quantityLabel(service.unit)}: ${cleanQuantity} ${unitLabel(service.unit)}`, `Rango referencial mostrado: ${money(low)} a ${money(high)}`,
    customer.name && `Nombre: ${customer.name}`, customer.phone && `Teléfono: ${customer.phone}`, customer.place && `Comuna / ubicación: ${customer.place}`, customer.detail && `Detalle: ${customer.detail}`, '', 'Entiendo que es una referencia y quiero validar alcance, visita y precio final.',
  ].filter(Boolean).join('\n'), [cleanQuantity, customer, high, low, service]);
  const choose = (next: Service) => { setServiceId(next.id); setQuantity(next.defaultQuantity); setShowServices(false); setSent(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); window.open(`https://wa.me/56930121625?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer'); };

  return <section id="calculadora-m2" className="relative overflow-hidden bg-[#0b0906] px-4 py-14 text-white sm:px-6 lg:px-8 lg:py-20">
    <div aria-hidden className="pointer-events-none absolute inset-0"><div className="absolute -left-36 top-12 h-80 w-80 rounded-full bg-yellow-300/10 blur-[110px]" /><div className="absolute -right-36 top-0 h-[30rem] w-[30rem] rounded-full bg-orange-500/10 blur-[130px]" /></div>
    <div className="relative mx-auto max-w-6xl"><header className="mx-auto max-w-3xl text-center"><p className="inline-flex items-center gap-2 rounded-full bg-yellow-300/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.28em] text-yellow-200"><Sparkles className="h-3.5 w-3.5" /> Cotiza con una ruta clara</p><h2 className="mt-4 text-4xl font-black tracking-[-.055em] sm:text-6xl">Cuéntanos qué necesitas. Te guiamos a una cotización real.</h2><p className="mt-4 text-sm leading-7 text-zinc-400 sm:text-base">Elige el servicio, indica la medida y revisa una boleta referencial antes de hablar con Fabrick.</p></header>
      <div className="mx-auto mt-9 max-w-5xl rounded-[2rem] bg-[#16120c]/80 p-4 shadow-[0_28px_95px_rgba(0,0,0,.42)] backdrop-blur-xl sm:p-6 lg:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-yellow-300 text-black"><ClipboardList className="h-5 w-5" /></span><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-yellow-300">Presupuesto guiado</p><p className="mt-1 text-sm font-bold text-zinc-300">Paso {step} de 3 · {step === 1 ? 'Servicio' : step === 2 ? 'Medida' : 'Cotización real'}</p></div></div><p className="hidden text-[10px] font-black uppercase tracking-[.16em] text-zinc-500 sm:block">Servicio · Alcance · Envío</p></div><div className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-yellow-300 via-amber-400 to-orange-500 transition-all duration-500" style={{ width: `${step * 33.33}%` }} /></div>
        <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_390px]"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-zinc-500">{step === 1 ? '1 · Selecciona el servicio' : step === 2 ? '2 · Indica el alcance' : '3 · Solicita tu revisión real'}</p>
          {step === 1 && <div className="mt-4"><button type="button" onClick={() => setShowServices((current) => !current)} className="flex w-full items-center justify-between rounded-[1.5rem] bg-gradient-to-br from-[#282013] to-[#15110b] p-5 text-left transition hover:-translate-y-0.5"><span className="flex min-w-0 items-center gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-yellow-300 text-black"><Icon className="h-5 w-5" /></span><span className="min-w-0"><span className="block text-[10px] font-black uppercase tracking-[.2em] text-yellow-300">Servicio seleccionado</span><strong className="mt-1 block truncate text-lg">{service.name}</strong><span className="mt-1 block truncate text-xs text-zinc-400">{service.summary}</span></span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-white/8 text-yellow-200"><ChevronDown className={`h-5 w-5 transition ${showServices ? 'rotate-180' : ''}`} /></span></button>
            {showServices && <div className="mt-3 space-y-4">{GROUPS.map((group) => <div key={group}><p className="mb-2 px-1 text-[9px] font-black uppercase tracking-[.22em] text-zinc-500">{group}</p><div className="grid gap-2 sm:grid-cols-2">{SERVICES.filter((item) => item.group === group).map((item) => { const ItemIcon = item.icon; const active = item.id === service.id; return <button key={item.id} type="button" onClick={() => choose(item)} className={`flex items-start gap-3 rounded-2xl p-3 text-left transition ${active ? 'bg-yellow-300 text-black' : 'bg-white/[.045] text-zinc-200 hover:bg-white/10'}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${active ? 'bg-black/10' : 'bg-yellow-300/10 text-yellow-300'}`}><ItemIcon className="h-4 w-4" /></span><span><b className="block text-xs leading-5">{item.short}</b><small className={`mt-0.5 block text-[10px] leading-4 ${active ? 'text-black/60' : 'text-zinc-500'}`}>{item.group}</small></span></button>; })}</div></div>)}</div>}
            <div className="mt-6 rounded-[1.4rem] bg-black/20 p-5"><p className="text-[10px] font-black uppercase tracking-[.22em] text-yellow-300">Qué considera este servicio</p><ul className="mt-4 grid gap-3 sm:grid-cols-2">{service.includes.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-zinc-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-yellow-300" />{item}</li>)}</ul><p className="mt-4 flex gap-2 text-[11px] leading-5 text-zinc-500"><Info className="mt-0.5 h-4 w-4 shrink-0 text-orange-300" />{service.note}</p></div><button type="button" onClick={() => setStep(2)} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-yellow-300 px-5 py-4 text-sm font-black text-black transition hover:bg-white">Continuar con la medida <ArrowRight className="h-4 w-4" /></button></div>}
          {step === 2 && <div className="mt-4 rounded-[1.5rem] bg-black/20 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-yellow-300/10 text-yellow-300"><Ruler className="h-5 w-5" /></span><div><h3 className="text-lg font-black">Define el alcance aproximado</h3><p className="mt-1 text-xs text-zinc-500">Usaremos este dato para orientarte, no para cerrar un precio final.</p></div></div>{service.unit === 'm2' && <div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-4">{PRESETS.map(({ label, value, icon: PresetIcon }) => <button key={value} type="button" onClick={() => setQuantity(value)} className={`flex items-center gap-2 rounded-xl px-3 py-3 text-left transition ${cleanQuantity === value ? 'bg-yellow-300 text-black' : 'bg-white/[.055] text-zinc-300 hover:bg-white/10'}`}><PresetIcon className="h-4 w-4" /><span><b className="block text-xs">{label}</b><small className={cleanQuantity === value ? 'text-black/55' : 'text-zinc-500'}>{value} m²</small></span></button>)}</div>}<label className="mt-5 block"><span className="text-[10px] font-black uppercase tracking-[.22em] text-zinc-500">{quantityLabel(service.unit)}</span><div className="mt-2 flex items-center gap-3 rounded-2xl bg-[#080705] px-4 py-3 focus-within:ring-1 focus-within:ring-yellow-300/60"><input type="number" min={service.unit === 'unidad' ? 1 : 0} inputMode="decimal" value={quantity || ''} onChange={(event) => setQuantity(Number(event.target.value) || 0)} className="w-full bg-transparent text-3xl font-black text-white outline-none" /><strong className="text-sm uppercase tracking-widest text-yellow-300">{unitLabel(service.unit)}</strong></div></label><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => setStep(1)} className="rounded-2xl bg-white/7 px-5 py-3 text-sm font-bold text-zinc-300">Cambiar servicio</button><button type="button" onClick={() => setStep(3)} disabled={!cleanQuantity} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-yellow-300 px-5 py-3 text-sm font-black text-black disabled:opacity-40">Ver boleta referencial <ArrowRight className="h-4 w-4" /></button></div></div>}
          {step === 3 && <form onSubmit={submit} className="mt-4 rounded-[1.5rem] bg-black/20 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-yellow-300/10 text-yellow-300"><Send className="h-5 w-5" /></span><div><h3 className="text-lg font-black">Pidamos el precio real</h3><p className="mt-1 text-xs text-zinc-500">El mensaje sale a WhatsApp con este servicio y su referencia.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Field label="Tu nombre" value={customer.name} onChange={(value) => setCustomer((current) => ({ ...current, name: value }))} placeholder="Nombre y apellido" required /><Field label="Teléfono" value={customer.phone} onChange={(value) => setCustomer((current) => ({ ...current, phone: value }))} placeholder="+56 9..." required /><Field label="Comuna o ciudad" value={customer.place} onChange={(value) => setCustomer((current) => ({ ...current, place: value }))} placeholder="Ej. Linares" required /></div><label className="mt-3 block"><span className="text-[10px] font-black uppercase tracking-[.2em] text-zinc-500">Cuéntanos un poco más</span><textarea value={customer.detail} onChange={(event) => setCustomer((current) => ({ ...current, detail: event.target.value }))} placeholder="Medidas, dirección aproximada, fotos o fecha ideal para comenzar…" className="mt-2 min-h-24 w-full resize-y rounded-2xl bg-[#080705] px-4 py-3 text-sm text-white outline-none placeholder:text-zinc-600 focus:ring-1 focus:ring-yellow-300/60" /></label><button type="submit" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-yellow-300 via-amber-300 to-orange-400 px-5 py-4 text-sm font-black text-black">Enviar solicitud por WhatsApp <ArrowRight className="h-4 w-4" /></button>{sent && <p className="mt-3 flex items-center justify-center gap-2 text-xs font-bold text-yellow-200"><CircleCheck className="h-4 w-4" /> Abrimos WhatsApp con tu solicitud lista para enviar.</p>}<button type="button" onClick={() => setStep(2)} className="mt-4 w-full text-xs font-bold text-zinc-500">Volver y modificar alcance</button></form>}
        </div><QuoteTicket service={service} quantity={cleanQuantity} low={low} high={high} average={average} /></div></div></div>
    <style jsx>{`.receipt { position:relative; isolation:isolate; } .receipt::after { content:''; position:absolute; z-index:2; left:0; right:0; bottom:-1px; height:14px; background:linear-gradient(135deg,transparent 7px,#fff4dd 0) 0 0/14px 14px repeat-x; transform:rotate(180deg); } @media (prefers-reduced-motion:no-preference) { .receipt { animation:print .56s cubic-bezier(.16,1,.3,1) both; } } @keyframes print { from { opacity:0; transform:translateY(-16px) scaleY(.94); transform-origin:top; } to { opacity:1; transform:translateY(0) scaleY(1); } }`}</style>
  </section>;
}

function QuoteTicket({ service, quantity, low, high, average }: { service: Service; quantity: number; low: number; high: number; average: number }) {
  const Icon = service.icon;
  return <aside className="lg:sticky lg:top-24 lg:self-start"><div className="receipt overflow-hidden rounded-t-[1.75rem] bg-[#fff4dd] px-5 pb-9 pt-6 text-[#17120c] shadow-[0_28px_65px_rgba(0,0,0,.35)] sm:px-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.23em] text-orange-700">Boleta referencial</p><h3 className="mt-2 text-xl font-black tracking-[-.04em]">Soluciones Fabrick</h3><p className="mt-1 text-[11px] text-[#6b5c4a]">Presupuesto de orientación · no tributario</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[#1a140d] text-yellow-300"><Icon className="h-4 w-4" /></span></div><div className="my-5 border-t border-dashed border-[#2d2519]/30" /><div className="flex items-start justify-between gap-5 text-sm"><div><p className="font-black">{service.name}</p><p className="mt-1 text-xs leading-5 text-[#6b5c4a]">{quantity} {unitLabel(service.unit)}</p></div><p className="text-right text-xs font-black text-[#6b5c4a]">Rango<br />estimado</p></div><div className="my-5 border-t border-dashed border-[#2d2519]/30" /><div className="space-y-3 text-xs"><Line label="Alcance aproximado" value={`${quantity} ${unitLabel(service.unit)}`} /><Line label="Referencia de mercado" value={`${money(low)} – ${money(high)}`} /><Line label="Valor medio orientativo" value={money(average)} bold /></div><div className="mt-5 rounded-2xl bg-[#1b160f] p-4 text-[#fff4dd]"><p className="text-[9px] font-black uppercase tracking-[.2em] text-yellow-300">Incluye en esta referencia</p><ul className="mt-3 space-y-2">{service.includes.slice(0, 3).map((item) => <li key={item} className="flex gap-2 text-[11px] leading-4 text-[#f6e8d3]/78"><Check className="h-3.5 w-3.5 shrink-0 text-yellow-300" />{item}</li>)}</ul></div><p className="mt-5 text-[10px] leading-4 text-[#6b5c4a]">El precio final depende de ubicación, acceso, medidas, estado existente, materiales y partidas adicionales. Se confirma todo antes de iniciar.</p></div></aside>;
}

function Line({ label, value, bold = false }: { label: string; value: string; bold?: boolean }) { return <div className="flex items-start justify-between gap-3"><span className="text-[#6b5c4a]">{label}</span><span className={`max-w-[58%] text-right ${bold ? 'font-black text-[#17120c]' : 'font-bold text-[#302719]'}`}>{value}</span></div>; }
function Field({ label, value, onChange, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) { return <label className="block"><span className="text-[10px] font-black uppercase tracking-[.2em] text-zinc-500">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} className="mt-2 w-full rounded-2xl bg-[#080705] px-4 py-3 text-sm text-white outline-none placeholder:text-zinc-600 focus:ring-1 focus:ring-yellow-300/60" /></label>; }
