import type { CatalogProduct } from '@/hooks/useCatalogProducts';
export type Capacity=9000|12000|18000|24000;
export type Mode='frio'|'ventilacion'|'seco'|'auto';
export type MoveState={forward:boolean;back:boolean;left:boolean;right:boolean};
export type Air={id:string;cap:Capacity;name:string;desc:string;image:string;coverage:number;people:string;energy:string;energyColor:string;inverter:boolean;power:number;width:number;source:'catalogo'|'referencia';features:string[]};
export const CAPS:Capacity[]=[9000,12000,18000,24000];
export const COVER:Record<Capacity,number>={9000:18,12000:24,18000:36,24000:48};
export const PBR={wood:['https://res.cloudinary.com/disghf6xc/image/upload/v1788666541/wood-floor-diff-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666550/wood-floor-normal-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666558/wood-floor-rough-1k.jpg'],wall:['https://res.cloudinary.com/disghf6xc/image/upload/v1788666566/painted-plaster-diff-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666573/painted-plaster-normal-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666580/painted-plaster-rough-1k.jpg'],fabric:['https://res.cloudinary.com/disghf6xc/image/upload/v1788666589/fabric-pattern-diff-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666597/fabric-pattern-normal-1k.jpg','https://res.cloudinary.com/disghf6xc/image/upload/v1788666605/fabric-pattern-rough-1k.jpg']} as const;
export const MODES:Record<Mode,{label:string;color:string;factor:number}>={frio:{label:'Frío',color:'#72D9FF',factor:1},ventilacion:{label:'Vent.',color:'#DDF6FF',factor:.3},seco:{label:'Deshum.',color:'#70E6C7',factor:.66},auto:{label:'Auto',color:'#C8B4FF',factor:.82}};
export const clamp=(n:number,a:number,b:number)=>Math.min(b,Math.max(a,n));
const all=(p:CatalogProduct)=>`${p.name} ${p.description||''} ${p.tagline||''} ${p.category||''} ${p.category_name||''} ${(p.features||[]).join(' ')} ${p.dimensions||''} ${JSON.stringify(p.specifications||{})}`;
function capFrom(s:string):Capacity|null{const n=s.toLowerCase().replace(/[.,\s]/g,'');for(const c of CAPS)if(n.includes(String(c))||n.includes(`${c/1000}k`))return c;return null}
function num(s:string,re:RegExp){const m=s.match(re);return m?Number(m[1].replace(',','.')):NaN}
function ecolor(e:string){if(e.includes('+++'))return'#35D46A';if(e.includes('++'))return'#58D985';if(e.includes('+'))return'#9EDC55';if(e==='A')return'#D8D94C';if(e==='B')return'#F0BB45';if(e==='C')return'#ED8D3E';return'#E4614D'}
function make(p:CatalogProduct,cap:Capacity):Air{const t=all(p),spec=JSON.stringify(p.specifications||{}),cv=num(`${spec} ${p.description||''}`,/(\d{1,2}(?:[.,]\d+)?)\s*(?:m2|m²)/i),range=t.match(/(\d+)\s*(?:a|[-–])\s*(\d+)\s*person/i),single=t.match(/(\d+)\s*person/i),energy=(t.toUpperCase().match(/A\+\+\+|A\+\+|A\+|\bA\b|\bB\b|\bC\b/)||[])[0]||(cap<=12000?'A++':cap===18000?'A+':'A'),wat=num(t,/(\d+(?:[.,]\d+)?)\s*(k?w)\b/i),kw=Number.isFinite(wat)?(/\d+(?:[.,]\d+)?\s*kw/i.test(t)?wat:wat/1000):({9000:.82,12000:1.08,18000:1.58,24000:2.2} as Record<Capacity,number>)[cap],coverage=Number.isFinite(cv)?cv:COVER[cap],mx=clamp(Math.round(coverage/7),2,8),rawW=num(`${p.dimensions||''} ${spec}`,/(\d{2,4}(?:[.,]\d+)?)\s*(?:mm|cm)/i);return{id:String(p.id),cap,name:p.name,desc:p.description||'Equipo sincronizado desde el catálogo Fabrick.',image:p.image_url||p.img||'',coverage,people:range?`${range[1]}–${range[2]} personas`:single?`hasta ${single[1]} personas`:`${Math.max(1,mx-1)}–${mx} personas`,energy,energyColor:ecolor(energy),inverter:/inverter/i.test(t),power:clamp(kw,.3,4),width:Number.isFinite(rawW)?clamp(rawW>200?rawW/1000:rawW/100,.65,1.2):({9000:.78,12000:.84,18000:.96,24000:1.08} as Record<Capacity,number>)[cap],source:'catalogo',features:(p.features||[]).slice(0,3)}}
export function buildAirOptions(products:CatalogProduct[]):Air[]{const air=products.filter(p=>/aire|acondicion|clima|split|btu/i.test(all(p)));return CAPS.map(cap=>{const p=air.find(x=>capFrom(all(x))===cap);if(p)return make(p,cap);const cv=COVER[cap],mx=clamp(Math.round(cv/7),2,8),energy=cap<=12000?'A++':cap===18000?'A+':'A';return{id:`ref-${cap}`,cap,name:`Split Inverter ${cap.toLocaleString('es-CL')} BTU`,desc:'Referencia visual. Al existir este equipo en el catálogo, se usarán automáticamente su imagen, descripción y especificaciones reales.',image:'',coverage:cv,people:`${Math.max(1,mx-1)}–${mx} personas`,energy,energyColor:ecolor(energy),inverter:true,power:({9000:.82,12000:1.08,18000:1.58,24000:2.2} as Record<Capacity,number>)[cap],width:({9000:.78,12000:.84,18000:.96,24000:1.08} as Record<Capacity,number>)[cap],source:'referencia',features:['Inverter','Modo ahorro','Control de temperatura']}})}
