'use client';
/* eslint-disable @next/next/no-img-element */
import type { Dispatch,ReactNode,SetStateAction } from 'react';
import { Calculator,Fan,Leaf,Move,Thermometer,Volume2,VolumeX } from 'lucide-react';
import type { Air,Mode,MoveState } from './model';
import { MODES } from './model';
const CLP=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
export function Glass({children,className=''}:{children:ReactNode;className?:string}){return <div className={`border border-white/14 bg-[#0b0d10]/72 shadow-[0_18px_55px_rgba(0,0,0,.42)] backdrop-blur-xl ${className}`}>{children}</div>}
export function Field({label,value,set,suffix='m',step=.1}:{label:string;value:number;set:(n:number)=>void;suffix?:string;step?:number}){return <label className="flex min-h-11 items-center justify-between rounded-xl border border-white/10 bg-white/[.055] px-3"><span className="text-[9px] font-black uppercase tracking-[.12em] text-white/45">{label}</span><span><input className="w-14 bg-transparent text-right text-base font-black outline-none" type="number" min={step} step={step} value={value} onChange={e=>set(Math.max(step,Number(e.target.value)||step))}/><small className="ml-1 text-white/35">{suffix}</small></span></label>}
function Stat({t,v,c}:{t:string;v:string;c?:string}){return <div className="rounded-xl bg-white/[.055] p-2"><small className="block text-[7px] uppercase text-white/35">{t}</small><b className="text-[9px]" style={{color:c}}>{v}</b></div>}
export function Thumb({a}:{a:Air}){return a.image?<img src={a.image} alt={a.name} className="mx-auto h-12 w-[104px] object-contain"/>:<div className="mx-auto grid h-12 w-[104px] place-items-center"><div className="h-7 w-20 rounded-lg border border-white/45 bg-gradient-to-b from-[#f4f3ef] to-[#bfc1c4] shadow-lg"><div className="mx-auto mt-5 h-1 w-14 rounded bg-[#25282c]"/></div></div>}
export function ProductInfo({a}:{a:Air}){return <div className="space-y-2"><div className="flex gap-3">{a.image?<img src={a.image} alt={a.name} className="h-16 w-20 rounded-xl bg-white/5 object-contain"/>:null}<div className="min-w-0"><small className="text-[8px] font-black uppercase tracking-[.14em] text-[#EBA665]">{a.source==='catalogo'?'Ficha de catálogo':'Referencia técnica'}</small><b className="block truncate text-sm">{a.name}</b><span className="text-[9px] text-white/45">{a.cap.toLocaleString('es-CL')} BTU · {a.coverage} m²</span></div></div><p className="line-clamp-3 text-[10px] leading-5 text-white/50">{a.desc}</p><div className="grid grid-cols-3 gap-1.5"><Stat t="Personas" v={a.people}/><Stat t="Tecnología" v={a.inverter?'Inverter':'Estándar'}/><Stat t="Eficiencia" v={a.energy} c={a.energyColor}/></div>{a.features.length?<div className="flex flex-wrap gap-1">{a.features.map(f=><span key={f} className="rounded-full border border-white/8 bg-white/[.04] px-2 py-1 text-[7px] text-white/42">{f}</span>)}</div>:null}</div>}
export function Climate({temp,setTemp,speed,setSpeed,mode,setMode,eco,setEco,sound,setSound,kwh,cost}:{temp:number;setTemp:(n:number)=>void;speed:number;setSpeed:(n:number)=>void;mode:Mode;setMode:(m:Mode)=>void;eco:boolean;setEco:(b:boolean)=>void;sound:boolean;setSound:(b:boolean)=>void;kwh:number;cost:number}){return <div className="space-y-3"><div className="flex items-center justify-between"><span className="flex items-center gap-2"><Thermometer className="h-4 w-4 text-[#EBA665]"/><b className="text-sm">Control de clima</b></span><b className="text-3xl">{temp}°</b></div><input className="w-full accent-[#F5871F]" type="range" min={16} max={28} value={temp} onChange={e=>setTemp(Number(e.target.value))}/><div className="grid grid-cols-4 gap-1">{(Object.keys(MODES) as Mode[]).map(m=><button type="button" key={m} onClick={()=>setMode(m)} className={`rounded-lg border py-2 text-[8px] font-black ${mode===m?'border-white/25 bg-white/12':'border-white/6 bg-white/[.03] text-white/40'}`}>{MODES[m].label}</button>)}</div><div className="grid grid-cols-4 gap-1">{[1,2,3,4].map(n=><button type="button" key={n} onClick={()=>setSpeed(n)} className={`rounded-lg border py-2 text-[9px] ${speed===n?'border-[#72D9FF]/40 bg-[#72D9FF]/10 text-[#72D9FF]':'border-white/6 text-white/40'}`}><Fan className="mr-1 inline h-3 w-3"/>{n}</button>)}</div><div className="grid grid-cols-2 gap-1.5"><button type="button" onClick={()=>setEco(!eco)} className={`rounded-xl border py-2 text-[9px] ${eco?'border-[#75DE9A]/35 text-[#75DE9A]':'border-white/8 text-white/40'}`}><Leaf className="mr-1 inline h-3 w-3"/>Ahorro</button><button type="button" onClick={()=>setSound(!sound)} className={`rounded-xl border py-2 text-[9px] ${sound?'border-[#EBA665]/35 text-[#EBA665]':'border-white/8 text-white/40'}`}>{sound?<Volume2 className="mr-1 inline h-3 w-3"/>:<VolumeX className="mr-1 inline h-3 w-3"/>}Sonido</button></div><div className="grid grid-cols-2 gap-1.5"><Stat t="Consumo estimado" v={`${Math.round(kwh)} kWh/mes`}/><Stat t="Costo estimado" v={CLP.format(cost)}/></div></div>}
export function MovePad({set}:{set:Dispatch<SetStateAction<MoveState>>}){const b=(k:keyof MoveState,t:string,c:string,r:string)=><button type="button" onPointerDown={()=>set(s=>({...s,[k]:true}))} onPointerUp={()=>set(s=>({...s,[k]:false}))} onPointerCancel={()=>set(s=>({...s,[k]:false}))} className={`${c} ${r} grid place-items-center rounded-full bg-white/11 text-lg active:bg-[#F5871F] active:text-black`}>{t}</button>;return <div className="pointer-events-auto absolute bottom-[178px] left-3 z-40 grid h-[108px] w-[108px] grid-cols-3 grid-rows-3 gap-1 rounded-full border border-white/14 bg-black/45 p-2 backdrop-blur-xl md:hidden">{b('forward','↑','col-start-2','row-start-1')}{b('left','←','col-start-1','row-start-2')}<span className="col-start-2 row-start-2 grid place-items-center"><Move className="h-4 w-4 text-white/30"/></span>{b('right','→','col-start-3','row-start-2')}{b('back','↓','col-start-2','row-start-3')}</div>}
export function MeasurePanel({length,setLength,width,setWidth,height,setHeight,people,setPeople,recommended}:{length:number;setLength:(n:number)=>void;width:number;setWidth:(n:number)=>void;height:number;setHeight:(n:number)=>void;people:number;setPeople:(n:number)=>void;recommended:number}){return <><div className="mb-3 flex items-center gap-2"><Calculator className="h-4 w-4 text-[#EBA665]"/><div><b className="block text-xs">Dimensiones reales</b><small className="text-[8px] text-white/35">La geometría cambia en vivo</small></div></div><div className="space-y-1.5"><Field label="Largo" value={length} set={setLength}/><Field label="Ancho" value={width} set={setWidth}/><Field label="Alto" value={height} set={setHeight}/><Field label="Personas" value={people} set={setPeople} suffix="" step={1}/></div><div className="mt-2 rounded-xl bg-[#F5871F] px-3 py-2 text-center text-xs font-black text-black">Recomendado · {recommended.toLocaleString('es-CL')} BTU</div></>}
