export const dynamic = 'force-dynamic';
import type { Metadata, Viewport } from 'next';
import './globals.css';
import './tenant-public-theme.css';
import './responsive-safety.css';
import './remove-obsolete-sections.css';
import InstallAppPrompt from '@/components/InstallAppPrompt';
import SmoothScrollProvider from '@/components/SmoothScrollProvider';

import { ThemeProvider } from '@/context/ThemeContext';
import { AuthProvider } from '@/context/AuthContext';
import { CartProvider } from '@/context/CartContext';
import { QuoteCartProvider } from '@/context/QuoteCartContext';
import { SiteConfigProvider } from '@/context/SiteConfigContext';
import AIAgentChat from '@/components/AIAgentChat';
import ServiceWorkerRegister from '@/components/ServiceWorkerRegister';
import Analytics from '@/components/Analytics';
import CmsRealtimeListener from '@/components/CmsRealtimeListener';
import CustomInjectionRoot from '@/components/CustomInjectionRoot';
import GlobalStylesRoot from '@/components/GlobalStylesRoot';
import VisualCmsRuntime from '@/components/cms/VisualCmsRuntime';
import CmsPreviewOverlay from '@/components/admin/cms/CmsPreviewOverlay';
import { TenantBrandingBar } from '@/components/tenant/TenantBrandingBar';
import { TenantThemeRuntime } from '@/components/tenant/TenantThemeRuntime';
import { TenantCopyRuntime } from '@/components/tenant/TenantCopyRuntime';
import CookieConsentBanner from '@/components/CookieConsentBanner';
import PublicVisitTracker from '@/components/PublicVisitTracker';
import { getSiteSection } from '@/lib/siteStructure';
import { FABRICK_SEO_KEYWORDS, SITE_URL } from '@/lib/seo';

// Per-request rendering keeps the nonce emitted by the strict Content-Security-Policy
// aligned with the inline scripts generated by Next.js during server rendering.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Soluciones Fabrick | Construcción, Remodelación y Reparación en Chile',
    template: '%s | Soluciones Fabrick',
  },
  description:
    'Construcción, remodelación, instalaciones y soluciones para el hogar en Maule, Linares, Talca y proyectos seleccionados en Santiago. Calcula referencias, compara mano de obra y trabajo vendido, y encuentra productos para tu proyecto.',
  keywords: FABRICK_SEO_KEYWORDS,
  authors: [{ name: 'Soluciones Fabrick' }],
  creator: 'Soluciones Fabrick',
  publisher: 'Soluciones Fabrick',
  applicationName: 'Soluciones Fabrick',
  category: 'Construcción, remodelación y reparación del hogar',
  openGraph: {
    title: 'Soluciones Fabrick | Construcción y soluciones para tu hogar',
    description:
      'Construcción, remodelación, instalaciones y productos para el hogar, con referencias de costo claras para resolver una partida o un proyecto completo.',
    url: SITE_URL,
    siteName: 'Soluciones Fabrick',
    locale: 'es_CL',
    type: 'website',
    images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: 'Soluciones Fabrick — construcción, remodelación y reparación del hogar' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Soluciones Fabrick | Construcción y soluciones para tu hogar',
    description: 'Construcción, remodelación, instalaciones y productos con referencias claras de mano de obra y trabajo vendido.',
    images: ['/twitter-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1, 'max-video-preview': -1 },
  },
  alternates: {
    canonical: SITE_URL,
  },
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Fabrick',
  },
  icons: {
    icon: [
      { url: '/app-icon.svg', type: 'image/svg+xml', sizes: 'any' },
      { url: '/app-icon.png', type: 'image/png', sizes: '512x512' },
      { url: '/brand/soluciones-fabrick-on-light.svg', type: 'image/svg+xml', sizes: '1180x310' },
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    shortcut: ['/app-icon.svg'],
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: '#08090A',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [navMenu, globalStyles] = await Promise.all([
    getSiteSection('nav-menu'),
    getSiteSection('global-styles'),
  ]);

  return (
    <html lang="es" className="scroll-smooth bg-[#08090A]" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Sora:wght@600;700;800&display=swap"
        />
        <meta name="mobile-web-app-capable" content="yes" />
        <GlobalStylesRoot />
        <CustomInjectionRoot slot="head" />
      </head>
      <body
        className="bg-[#08090A] text-[#FFF9EE] antialiased app-shell"
        style={{ fontFamily: 'Manrope, ui-sans-serif, system-ui, sans-serif' }}
      >
        <SiteConfigProvider initial={{ 'nav-menu': navMenu, 'global-styles': globalStyles }}>
          <ThemeProvider>
            <AuthProvider>
              <CartProvider>
                <QuoteCartProvider>
                  <SmoothScrollProvider />
                  <TenantThemeRuntime />
                  <TenantCopyRuntime />
                  <VisualCmsRuntime />
                  {children}
                  <TenantBrandingBar />
                  <ServiceWorkerRegister />
                  <InstallAppPrompt />
                  <AIAgentChat hideOn={['/admin', '/auth', '/checkout', '/presupuesto', '/presupuestos', '/p/']} />
                  <CookieConsentBanner />
                  <Analytics />
                  <PublicVisitTracker />
                  <CmsRealtimeListener />
                  <CmsPreviewOverlay />
                </QuoteCartProvider>
              </CartProvider>
            </AuthProvider>
          </ThemeProvider>
        </SiteConfigProvider>
        <CustomInjectionRoot slot="bodyEnd" />
      </body>
    </html>
  );
}
