export const dynamic = 'force-dynamic';
import type { Metadata, Viewport } from 'next';
import './globals.css';
import './tenant-public-theme.css';
import './responsive-safety.css';
import './remove-obsolete-sections.css';
import InstallAppPrompt from '@/components/InstallAppPrompt';
import SmoothScrollProvider from '@/components/SmoothScrollProvider';
import SplashScreen from '@/components/SplashScreen';

import { ThemeProvider } from '@/context/ThemeContext';
import { AuthProvider } from '@/context/AuthContext';
import { CartProvider } from '@/context/CartContext';
import { QuoteCartProvider } from '@/context/QuoteCartContext';
import { SiteConfigProvider } from '@/context/SiteConfigContext';
import AIAgentChat from '@/components/AIAgentChat';
import ServiceWorkerRegister from '@/components/ServiceWorkerRegister';
import Analytics from '@/components/Analytics';
import CmsRealtimeListener from '@/components/CmsRealtimeListener';
import CustomInjectionRoot from '@/components/CustomInjectionRoot';
import GlobalStylesRoot from '@/components/GlobalStylesRoot';
import CmsPreviewOverlay from '@/components/admin/cms/CmsPreviewOverlay';
import { TenantBrandingBar } from '@/components/tenant/TenantBrandingBar';
import { TenantThemeRuntime } from '@/components/tenant/TenantThemeRuntime';
import { TenantCopyRuntime } from '@/components/tenant/TenantCopyRuntime';
import CookieConsentBanner from '@/components/CookieConsentBanner';
import PublicVisitTracker from '@/components/PublicVisitTracker';
import { getSiteSection } from '@/lib/siteStructure';

// Per-request rendering keeps the nonce emitted by the strict Content-Security-Policy
// aligned with the inline scripts generated by Next.js during server rendering.
export const metadata: Metadata = {
  metadataBase: new URL('https://www.solucionesfabrick.com'),
  title: {
    default: 'Soluciones Fabrick | Construcción, Remodelación y Cotización en Chile',
    template: '%s | Soluciones Fabrick',
  },
  description:
    'Cotiza y planifica viviendas, ampliaciones, remodelaciones e instalaciones con Soluciones Fabrick. Rangos claros, alcance definido y evaluación técnica en Maule y proyectos seleccionados en Santiago.',
  keywords: [
    'construcción Maule',
    'remodelación Linares',
    'cotizar casa Chile',
    'construcción llave en mano Maule',
    'ampliación de vivienda',
    'radier precio por metro cuadrado',
    'techumbre y filtraciones',
    'gasfitería Linares',
    'electricidad domiciliaria Maule',
    'instalación aire acondicionado',
  ],
  authors: [{ name: 'Soluciones Fabrick' }],
  openGraph: {
    title: 'Soluciones Fabrick | Calcula, define y construye con claridad',
    description:
      'Obtén un rango inicial, conoce qué incluye cada servicio y solicita una evaluación para construir, ampliar o remodelar.',
    url: 'https://www.solucionesfabrick.com',
    siteName: 'Soluciones Fabrick',
    locale: 'es_CL',
    type: 'website',
    images: [{
      url: '/brand/soluciones-fabrick-social.png',
      width: 1200,
      height: 630,
      alt: 'Soluciones Fabrick — construcción y remodelación con alcance claro',
    }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Soluciones Fabrick | Construcción con un plan claro',
    description: 'Calcula una referencia, revisa servicios y solicita una evaluación técnica para tu proyecto.',
    images: ['/brand/soluciones-fabrick-social.png'],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://www.solucionesfabrick.com',
  },
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Fabrick',
  },
  icons: {
    icon: [
      { url: '/app-icon.svg', type: 'image/svg+xml', sizes: 'any' },
      { url: '/app-icon.png', type: 'image/png', sizes: '512x512' },
      { url: '/brand/soluciones-fabrick.svg', type: 'image/svg+xml', sizes: '1040x260' },
    ],
    apple: [
      { url: '/app-icon.png', sizes: '512x512', type: 'image/png' },
    ],
    shortcut: ['/app-icon.svg'],
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: '#0a0907',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [navMenu, globalStyles] = await Promise.all([
    getSiteSection('nav-menu'),
    getSiteSection('global-styles'),
  ]);

  return (
    <html lang="es" className="scroll-smooth" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Sora:wght@600;700;800&display=swap"
        />
        <meta name="mobile-web-app-capable" content="yes" />
        <GlobalStylesRoot />
        <CustomInjectionRoot slot="head" />
      </head>
      <body
        className="bg-black text-white antialiased app-shell"
        style={{ fontFamily: 'Manrope, ui-sans-serif, system-ui, sans-serif' }}
      >
        <SplashScreen />
        <SiteConfigProvider initial={{ 'nav-menu': navMenu, 'global-styles': globalStyles }}>
          <ThemeProvider>
            <AuthProvider>
              <CartProvider>
                <QuoteCartProvider>
                  <SmoothScrollProvider />
                  <TenantThemeRuntime />
                  <TenantCopyRuntime />
                  {children}
                  <TenantBrandingBar />
                  <ServiceWorkerRegister />
                  <InstallAppPrompt />
                  <AIAgentChat hideOn={['/admin', '/auth', '/checkout', '/presupuestos', '/p/']} />
                  <CookieConsentBanner />
                  <Analytics />
                  <PublicVisitTracker />
                  <CmsRealtimeListener />
                  <CmsPreviewOverlay />
                </QuoteCartProvider>
              </CartProvider>
            </AuthProvider>
          </ThemeProvider>
        </SiteConfigProvider>
        <CustomInjectionRoot slot="bodyEnd" />
      </body>
    </html>
  );
}
