import 'server-only';
import { Resend } from 'resend';
import { insforgeAdmin } from '@/lib/insforge';
import { resolveIntegrationCredentials } from '@/lib/integrationCredentials';
import { getAppBaseUrl } from '@/lib/mercadopago';

export type AdminOrderNotificationResult = { ok: boolean; skipped?: boolean; reason?: string; emailId?: string; error?: string };
function money(value: unknown) { return new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(Math.round(Number(value || 0))); }
function esc(value: unknown) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)); }
function extractEmail(from: string | undefined) { if (!from) return ''; const match = from.match(/<([^>]+)>/); return (match?.[1] || from).trim(); }

export async function sendAdminOrderNotification(orderId: string): Promise<AdminOrderNotificationResult> {
  const resend = await resolveIntegrationCredentials('resend', ['api_key', 'from'], true);
  if (resend.missing.length > 0) return { ok: false, skipped: true, reason: `Resend no configurado: ${resend.missing.join(', ')}` };
  const notifyTo = (resend.values.notify_to || process.env.ORDER_NOTIFICATION_EMAIL || process.env.ADMIN_NOTIFICATION_EMAIL || process.env.ADMIN_EMAIL || extractEmail(resend.values.from)).trim();
  if (!notifyTo) return { ok: false, skipped: true, reason: 'No hay correo administrador configurado.' };
  const { data: order, error } = await insforgeAdmin.database.from('orders').select('id, customer_name, customer_email, customer_phone, region, shipping_address, items, subtotal, tax, shipping_fee, total, currency, payment_id, payment_status, status, dispatch_code, tracking_number, created_at, updated_at').eq('id', orderId).single();
  if (error || !order) return { ok: false, error: error?.message || 'Orden no encontrada.' };
  const { data: invoiceRows } = await insforgeAdmin.database.from('invoices').select('folio, dte_type, provider, sii_status, total').eq('order_id', orderId).order('created_at', { ascending: false }).limit(1);
  const invoice = Array.isArray(invoiceRows) && invoiceRows.length ? invoiceRows[0] as Record<string, unknown> : null;
  const realDte = Boolean(invoice && invoice.provider !== 'mock' && !String(invoice.sii_status || '').includes('mock'));
  const items = Array.isArray(order.items) ? order.items as Array<Record<string, unknown>> : [];
  const rows = items.map((item) => { const qty = Math.max(1, Number(item.cantidad || item.quantity || 1)); const unit = Number(item.precioUnitario || item.unitPrice || 0); return `<tr><td style="padding:9px 0;border-bottom:1px solid #eee;font-weight:700">${esc(item.nombre || item.name || `Producto ${item.productoId || ''}`)}</td><td style="padding:9px;text-align:center;border-bottom:1px solid #eee">${qty}</td><td style="padding:9px 0;text-align:right;border-bottom:1px solid #eee;font-weight:800">${money(qty * unit)}</td></tr>`; }).join('');
  const html = `<!doctype html><html><body style="margin:0;background:#f4f1eb;font-family:Arial,sans-serif;color:#151515"><div style="max-width:760px;margin:auto;padding:24px"><div style="background:#111214;color:#fff;border-radius:26px 26px 0 0;padding:28px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:.18em;color:#ffb000;font-weight:900">Nueva venta confirmada</div><h1 style="margin:10px 0 6px;font-size:32px">${money(order.total)}</h1><p style="margin:0;color:#bbb">Mercado Pago confirmó la compra y Fabrick la pasó a preparación.</p></div><div style="background:white;border-radius:0 0 26px 26px;padding:28px"><table style="width:100%;font-size:14px"><tr><td><b>Pedido</b><br>${esc(order.id)}</td><td><b>Pago MP</b><br>${esc(order.payment_id || '-')}</td></tr><tr><td style="padding-top:14px"><b>Cliente</b><br>${esc(order.customer_name)} · ${esc(order.customer_email)}</td><td style="padding-top:14px"><b>Despacho</b><br>${esc(order.region)} · ${esc(order.shipping_address || '-')}</td></tr></table><h2 style="margin:24px 0 8px;font-size:18px">Productos</h2><table style="width:100%;border-collapse:collapse;font-size:14px">${rows || '<tr><td>Compra registrada</td></tr>'}</table><div style="margin-top:20px;background:#f8f5ef;border-radius:16px;padding:16px"><div style="display:flex;justify-content:space-between"><span>Subtotal productos</span><b>${money(order.subtotal)}</b></div><div style="display:flex;justify-content:space-between;margin-top:6px"><span>Despacho</span><b>${money(order.shipping_fee)}</b></div><div style="display:flex;justify-content:space-between;margin-top:10px;font-size:19px"><strong>Total cobrado</strong><strong>${money(order.total)}</strong></div></div><div style="margin-top:18px;padding:14px;border-radius:14px;background:${realDte ? '#ecfdf5' : '#fff7ed'};color:${realDte ? '#166534' : '#9a3412'}"><b>${realDte ? 'DTE real emitido' : 'DTE real pendiente'}</b><br><span style="font-size:13px">${realDte ? `Folio ${esc(invoice?.folio)} · ${esc(invoice?.sii_status)}` : 'La compra está confirmada, pero la integración tributaria está en modo interno/simulado.'}</span></div><div style="margin-top:22px"><a href="${getAppBaseUrl()}/admin/pedidos" style="display:inline-block;background:#ffb000;color:#111;text-decoration:none;font-weight:900;padding:12px 18px;border-radius:999px">Abrir pedidos</a> <a href="${getAppBaseUrl()}/admin/pagos" style="display:inline-block;background:#111;color:white;text-decoration:none;font-weight:900;padding:12px 18px;border-radius:999px">Abrir pagos</a></div></div></div></body></html>`;
  const client = new Resend(resend.values.api_key);
  const result = await client.emails.send({ from: resend.values.from, to: [notifyTo], subject: `Nueva venta ${money(order.total)} · ${items[0]?.nombre || order.id}`, html });
  if (result.error) return { ok: false, error: result.error.message };
  return { ok: true, emailId: result.data?.id };
}
